### ISSUE TITLE
Release Status

### ISSUE THREAD

**Issue by netbull** [notifee/react-native-notifee#1]
With all this noise in the previous thread the main question still stays without an answer:

Are there any news about the release date /alpha, beta, pre/ ?

**Comment by Ehesp** [comment]
Our goals are to have *something* in place by the end of the year, and we'd reach out to users on the Google Form to see if they'd be interested in giving the library a go with Alpha.

What that *something* is:

- We'd be releasing an Android only version to start with.
- iOS will be released afterwards.
- The public API surface area may change slightly once iOS lands. We're not there yet with iOS so it may cause some bits to change.
- Testing won't be fully complete. We've got the core aspects nailed down, however we're aiming to have automated/manual tests running across a variety of devices/APIs.
- Alpha is about helping us find bugs/problems; we want to get feedback on real life app integration, so we'll be super keen on getting users feedback.
- Documentation will be work in progress. We have a massive documentation plan, and some of it is work in progress. This will be a primary focus once it's in the wild though.

**Comment by defcon8** [comment]
My company is interested in this module too. Please give me shout out when it is available.

**Comment by zacharyweidenbach** [comment]
> Our goals are to have _something_ in place by the end of the year, and we'd reach out to users on the Google Form to see if they'd be interested in giving the library a go with Alpha.

Did you mean by end of 2019 or end of 2020?

**Comment by Ehesp** [comment]
:D 2019

We're super close to putting something in alpha state, just doing some testing/cleanup at the moment.

**Comment by netbull** [comment]
@Ehesp looking forward to see what's cooking :)

**Comment by Ehesp** [comment]
Hey all!

Just a heads up that we're now in the final stages of an alpha release (see above), finishing/tidying up the Android code, documentation & website. 

We'll be reaching out soon (target end of the week), stay tuned.

**Comment by emaxedon** [comment]
Hey, super side note but I think the website should be updated => https://invertase.io/oss/react-native-firebase/releases/v6.0.0#where-is-the-notifications-library?

I was under the impression their would be a notifications module which I believe is definitely no longer the case.

**Comment by Salakar** [comment]
Hey all,

We've just published the documentation which we've been working on alongside the library, this should give you an idea of how to use the APIs and which features we're supporting. We're currently working on getting the SDK in a publishable state and we'll update soon once its live.

**Documentation**: https://notifee.app/react-native/docs/overview

We'd love some feedback on the documentation approach that we've taken with Notifee, so please let us know if you have any thoughts.

---- 

As a side note, you may notice that we've now changed the pricing model so that a single purchase now includes life time access to all updates now without the need for any further purchases. The pricing has remained the same. Hopefully this alleviates some concerns people had about paying for updates.

**Comment by Salakar** [comment]
Hey again all 👋 

The alpha package with Android support is published on NPM 🎉 , however we're still testing a few things and going through docs & types and making sure everything is working well before we open up the account/license management pages, but... you're welcome to try it out in the meantime as a license is not required in development.

You'll also notice that we've open sourced the React Native module code on this repo - we still love open-source so we'll continue trying to open source as much as we can, however; the core internals of Notifee will remain closed source.

We'll update with more info in due course but until then, happy early testing!

**Comment by Salakar** [comment]
Hey again everyone 👋 

Website is now fully live, purchasing, account management, licensing etc is now available. 

Would love for a few people to test it out etc and as a thanks for doing that and for participating in this issue I've created a coupon code you can use at checkout for 60% off, for the next 5 people; `RNNISSUE1`.

If you're a core contributor to any of our Open Source products, or have a fully Open Source app, or a non-profit organisation (e.g. charity) then please [get in touch here](https://notifee.app/contact#license) and we'll be happy to grant you a free license.

iOS is coming along well and we hope to have a release out by the end of the month that includes iOS.

**Comment by lukeggchapman** [comment]
Thanks! I purchased with anticipation of using in a future project. Everything went smoothly, with only 1 small piece of feedback, the text colour when checking out is very dark.
![Screen Shot 2020-02-14 at 9 38 04 am](https://user-images.githubusercontent.com/1396212/74485376-b7340e80-4f0e-11ea-87f9-2c9e620ed2cf.png)

**Comment by Ehesp** [comment]
Ruddy dark mode :D Will sort. Thanks :)

**Comment by Salakar** [comment]
Thanks for the feedback @lukeggchapman - this has been sorted now 🙈

**Comment by Jalson1982** [comment]
Hi there. I want to purchase this for my app, so 2 fast questions. Ios still not ready? And is it clever to use it in production app ?

**Comment by Salakar** [comment]
> Hi there. I want to purchase this for my app, so 2 fast questions. Ios still not ready? And is it clever to use it in production app ?

iOS not ready yet, hoping to have a release end of the month which includes iOS. For production, the current release which is Android only is pretty stable

**Comment by AndrewMorsillo** [comment]
@Ehesp @Salakar now that purchases are available do you have a roadmap and chart of current functionality? For example I need local scheduled notification support for my app which appears to be missing as of now. It would be nice to know, at least roughly, when these features will be available for use.

**Comment by Salakar** [comment]
> @Ehesp @Salakar now that purchases are available do you have a roadmap and chart of current functionality? For example I need local scheduled notification support for my app which appears to be missing as of now. It would be nice to know, at least roughly, when these features will be available for use.

@AndrewMorsillo we'll get a roadmap up this week. Scheduling (or Triggers in Notifee) is next after initial iOS support, there's actually already a fair bit of code for it in place on Android however we held off releasing it so we could make sure the API was viable for both platforms.

**Comment by Salakar** [comment]
Hey all 👋 

Another quick update, iOS support is almost there, see PR #13 - once this PR lands we'll be doing another release to get iOS out there and work on the documentation.

Following the iOS release, we'll begin roadmapping new features, with triggers (e.g. schedules) being being first shortly after iOS (as mentioned above).

**Comment by viniciuscostass** [comment]
I've been testing notifee on a new project from my company (we already bought a license), it works perfectly well on android, a lot of options for customizing our notifications. It's a great solution for notifications integrated with firebase in RN.
Looking forward iOS support so we can achieve production stage.

**Comment by Tyldar** [comment]
Thanks @Salakar for the update. However i'm curious about a thing and before buying license: will the Notifee library be able to display notification from FCM message payload in "background/dead" app state?

I mean for the moment, using only RNF I can send either notification **OR** message to my iPhone version of the app, but not both.

**Comment by Salakar** [comment]
@Tyldar I think this should help clarify FCM behaviour in Notifee; https://notifee.app/react-native/docs/integrations/fcm

> I mean for the moment, using only RNF I can send either notification OR message to my iPhone version of the app, but not both.

This shouldn't be the case on the RNF v6 messaging module, both are supported and we're using both in some of our apps. 

On a side note; we'll be going through RNF messaging after Notifee iOS launch and making sure everything is integrating well with Notifee and also making improvements to it based on code in Notifee, e.g. [better permissions requesting apis](https://notifee.app/react-native/reference/requestpermission) for iOS.

**Comment by perrosnk** [comment]
Any updates on when iOS integration will be ready? At least approximately.
I have already purchased a license, and Notifee looks great!

**Comment by Ehesp** [comment]
Hey all - iOS is almost there, there is a few days more work left so we're hoping a release will be out by the end of next week.

We did plan on getting something out this week, however we ended up spending a considerable amount of time over the last 3 days upgrading the messaging module on React Native Firebase to better support default FCM notifications. 

Sorry for the delay, bit of a balancing act prioritizig the work.

**Comment by kangzeroo** [comment]
@Ehesp I have been reading various threads dating back to x5.x.x and and thrilled to see that iOS is almost here. I see on the Notifee.app banner that the early access code deadline is passed, is this true? Or can I still redeem at discount? 

```
Early access promotion: Use code EAP30OFF at checkout for 30% off all licenses, code valid until 6th March 2020.
```

I have purchased before from the React-Native marketplace https://github.com/react-native-market/firebase-authentication-kit/issues/40#issue-575660625

**Comment by kangzeroo** [comment]
Also, does Notifee.app handle iOS background notifications?

**Comment by jpudysz** [comment]
Hello, my team really need access to iOS (even in alpha) to start implementing it inside our app. We're delayed for almost 1 month. We purchased the license at the beginning of March. Still waiting for your update!

**Comment by Salakar** [comment]
Hey all, I've just merged initial iOS support into master. There's still some things I want to test before I do a release so there's no NPM release just yet - I'll do one in the next couple of days.

Once this is released I'll look at scheduling/triggers next.

**Comment by jpudysz** [comment]
Thanks for the release. I was able to integrate notifee successfully!
It's just a simple use-case: channels, background/foreground notifications consumed from FCM.

What doesn't work is displaying notifee's notification on foreground (only iOS) #24 

Thanks for the alpha!

**Comment by Salakar** [comment]
@jpudysz - thats great to hear, thanks for the feedback - I've responded to your iOS issue - lets discuss there, thanks!

**Comment by VivienTournie** [comment]
Any update on the roadmap ? Are scheduled local notifications ready soon (Triggers in Notifee) ?

Thanks !

**Comment by AnmolShrma** [comment]
@Salakar shall we assume that react-native-firebase V6 will never have a free notification service like V5 had and also we have to be dependent of these third party libraries from now right?

**Comment by mikehardy** [comment]
@AnmolShrma no need to wait for his response on this, the answer is definitively that react-native-firebase will not cover device notification APIs going forward.

There are 2 viable community "free notification service" options (react-native-notifications and react-native-push-notifications) as well as Notifee, all of which may successfully integrate with react-native-firebase

**Comment by vonovak** [comment]
let me just add that it's also possible to use expo's notification module (https://github.com/expo/expo/tree/master/packages/expo-notifications) but this one also requires installing the unimodules dep. 

It'd be really nice to see some progress from notifee on the ios implementation. Or have I just not noticed it? - this repo does not include a changelog so I'm not sure where to track changes. Thank you!

**Comment by mikehardy** [comment]
Hi there @vonovak ! This repo is PR-always so best place to track is PRs and or commit history https://github.com/notifee/react-native-notifee/pulls?q=is%3Apr+is%3Aclosed

iOS is already out, listed as alpha but in general working it seems, as reported by testers.

**Comment by Salakar** [comment]
@vonovak we'll try to be a bit clearer on releases/announcements in future, will get a change log setup.

In terms of iOS support it is up and live; currently only `attachments` support is missing. 

The latest changes for iOS this week introduced the following APIs:

 - [setBadgeCount](https://notifee.app/react-native/reference/setbadgecount)
 - [getBadgeCount](https://notifee.app/react-native/reference/getbadgecount)
 - [incrementBadgeCount](https://notifee.app/react-native/reference/incrementbadgecount)
 - [decrementBadgeCount](https://notifee.app/react-native/reference/decrementbadgecount)
 - [cancelAllNotifications](https://notifee.app/react-native/reference/cancelallnotifications)


Our current high-level roadmap is as follows:

## v1.0.0

- iOS notification attachments support.
- iOS events currently all go to `onForegroundEvent` - needs splitting up to support `onBackgroundEvent`
- Notification triggers (e.g. Schedules).
  - Schedule triggers.
    - Specific point in time.
    - Repeat based on time units.
- Update `cancelAllNotifications` to allow specifying cancelling all currently displayed notifications, or cancelling all scheduled notifications, or both.
- Android fullscreen intent support.

## v2.0.0

 - Media Style Notifications Android.
 - Additional notification triggers.
   - Geo-fencing tiggers (on enter/exit),

**Comment by yardenst** [comment]
@Salakar @Ehesp can you please share a rough release date for v1.0.0? Thanks for your great work

**Comment by Salakar** [comment]
Hey all, there's been a few releases lately, please check out the release notes if you're interested (a few new features on iOS & Android): https://notifee.app/react-native/docs/release-notes

**Comment by Tyki** [comment]
Hi, we are really interested in Notifee ! Just wondering if you have any plan to release Notifee before 15 November since there is a mandatory upgrade from Firebase V5 to Firebase V6 due to crashlytics?

**Comment by afestein** [comment]
>mandatory upgrade from Firebase V5 to Firebase V6 due to crashlytics
@Tyki that's interesting, can you provide some more information please? That will affect us also.

**Comment by mars-lan** [comment]
I believe @Tyki is referring to this: https://firebase.googleblog.com/2020/06/crashlytics-sdk-now-available.html. That said, `react-native-firebase` v6 isn't on Firebase Crashlytics yet (https://github.com/invertase/react-native-firebase/blob/master/packages/crashlytics/RNFBCrashlytics.podspec & https://github.com/invertase/react-native-firebase/blob/master/packages/crashlytics/android/build.gradle). Presumably it will be before Nov 15.

**Comment by lorenc-tomasz** [comment]
> Hi, we are really interested in Notifee ! Just wondering if you have any plan to release Notifee before 15 November since there is a mandatory upgrade from Firebase V5 to Firebase V6 due to crashlytics?

The same question. Just wondering if scheduled notifications will be ready before this date.

**Comment by mikehardy** [comment]
I cannot answer about Notifee but the OP is correct that the migration that started with going from Fabric/Fabric crash reporting and is now at Fabric/Firebase before it ends with Firebase/Firebase crash reporting will drive the upgrade cycle.

It hasn't merged yet upstream but I think it's just a matter of time, it's already gone through review and seems like it works

It is worth noting that a motivated individual could post a PR for react-native-firebase v5 that implemented the same work and though I was the last person maintaining v5 I'd work to get it merged and do a release. I did the same for apple social auth but it would need a very  motivated person because I wouldn't want to spend much time on it - it would need to be a clean PR ready to go already tested etc.

**Comment by mars-lan** [comment]
Not trying to digress the conversation further, but FWIW I was able to get `@react-native-firebase/crashlytics` to coexist with react-native-firebase v5 without much trouble. Unlike other modules (e.g. `auth`, `AdMob`, `perf` etc), there's no class name conflicts here.

**Comment by mikehardy** [comment]
@mars-lan fascinating! We have to focus effort and move forward as developers but I am not insensitive to the struggle some developers have finding time to upgrade complicated, inherited, or zombie code, so that could be useful. Care to post here? https://github.com/invertase/react-native-firebase/issues/3510 or maybe here https://github.com/invertase/react-native-firebase/pull/3580 for any poor souls that are truly stuck and would otherwise lose their crash reporting

**Comment by mikehardy** [comment]
Please don't take offense, commenters - but I am going to collapse some of these comments to focus it on release date. No malice intended :-)

**Comment by lorenc-tomasz** [comment]
Hi,
@Salakar Any timeframe for scheduled / repeating notifications on iOS / Android?

Kind regards,
Tom

**Comment by bugnuker** [comment]
Hello!

@Salakar - Any timeframe or roadmap for timer feature on iOS?

**Comment by AlexeyVlasenko** [comment]
Hi! We are using notifee, but handling remote fcm images in iOS is very needed, hope you will bring it soon

**Comment by helenaford** [comment]
Hi all, there's been a new release (v0.11.0) with Trigger Notifications for Android, introducing the following APIs:
- [createTriggerNotification](https://notifee.app/react-native/reference/createtriggernotification)
- [getTriggerNotificationIds](https://notifee.app/react-native/reference/gettriggernotificationids)
- [cancelAllNotifications](https://notifee.app/react-native/reference/cancelallnotifications)
- [cancelDisplayedNotifications](https://notifee.app/react-native/reference/canceldisplayednotifications)
- [cancelTriggerNotifications](https://notifee.app/react-native/reference/canceltriggernotifications)

More info on how to use them over on the docs (https://notifee.app/react-native/docs/triggers).

**Comment by mars-lan** [comment]
Awesome. Since the core is not open sourced it's difficult to tell the actual implementation. However, we faced some issues when using `react-native-firebase` 5.x, which is based on Android's `AlarmManager`. It turns out that some manufactures adopt aggressive "battery conservation techniques" that prevents scheduled intents to be fired (see https://dontkillmyapp.com/ for more details). I hope notifee uses a different implementation that's not subjected to these limitations.

**Comment by Salakar** [comment]
> Awesome. Since the core is not open sourced it's difficult to tell the actual implementation. However, we faced some issues when using `react-native-firebase` 5.x, which is based on Android's `AlarmManager`. It turns out that some manufactures adopt aggressive "battery conservation techniques" that prevents scheduled intents to be fired (see https://dontkillmyapp.com/ for more details). I hope notifee uses a different implementation that's not subjected to these limitations.

Android uses AndroidX WorkManager under the hood, WorkManager adheres to power-saving features and best practices like Doze mode and should be a lot more reliable. https://developer.android.com/topic/libraries/architecture/workmanager

**Comment by helenaford** [comment]
There's been a new release (v0.13.0) that includes remote image support for iOS attachments, a new `repeatFrequency` property for `TimestampTrigger` to create `hourly`, `daily`, and `weekly` trigger notifications, and the following APIs to help with Android background restrictions:

- [isBatteryOptimizationEnabled](https://notifee.app/react-native/reference/isbatteryoptimizationenabled)  
- [openBatteryOptimizationSettings](https://notifee.app/react-native/reference/openbatteryoptimizationsettings)  
  
Check out release notes for more info. (https://notifee.app/react-native/docs/release-notes).

**Comment by FeXd** [comment]
Just wanted to flag that the latest release has not been tagged (v0.14.0). This caused some confusion on my team this morning when we were trying to update and read about changes. @helenaford

**Comment by helenaford** [comment]
It's now tagged. Thanks for flagging that up, sorry for the confusion.

**Comment by helenaford** [comment]
New release is up (v0.15.0) with some new APIs 😎  

On Android, additional support to prevent the app from being killed has been added:
- getPowerManagerInfo()
- openPowerManagerSettings()

And, on both platforms, it's now possible to cancel either a displayed or trigger notification with the following APIs:
 - cancelTriggerNotification(id)
- cancelDisplayedNotification(id)

Please check out the [release notes](https://notifee.app/react-native/docs/release-notes#0150) for more info.

As always, we appreciate the feedback  😸

**Comment by helenaford** [comment]
Hey Y'all, a pre-release is up (v0.16.0-0) that we'd love feedback on. 

Changes include:
- [iOS]: Added support for Apple Silicon and Mac Catalyst builds (Fixes #162, #215)
- [Android]: Fixed an issue with license validation on Android 6 (Fixes #87)

**Comment by helenaford** [comment]
v0.16.0 has now been released 😄 Notifee now includes support for Apple Silicon (arm64) and Mac Catalyst builds 🔥 

Check out release notes for more info. (https://notifee.app/react-native/docs/release-notes).

**Comment by Salakar** [comment]
Notifee has since shipped to stable release versioning so I'm going to go ahead and close this issue. Thanks everyone :)

Keep an eye on https://notifee.app/react-native/docs/release-notes for releases.
