### ISSUE TITLE
Notification Messages - Overide the default FCM notification manager

### ISSUE THREAD

**Issue by ankitsolanki** [notifee/react-native-notifee#101]
Hi, 
When we use firebase to send message to the device using data payload - if the app has not been started then the background notification are getting dropped. 

This is when we decided to move to Notification message with data payload, the challenge here is with Notification message the default FCM manager kicks in and styling is lost in that case. 

Please advise. Happy to add more data points as and when required. 
Sample Notification 
![image](https://user-images.githubusercontent.com/1607358/86474991-8a6b8100-bd61-11ea-8663-dd846517da14.png)
This is the notification send with data payload and config and works beautifully when the app is in foreground and background. 

If the app is killed it just doesnt work. 

Thanks

**Comment by mikehardy** [comment]
I'm not aware of a technical solution to the force-close state ignoring data-only messages.

I don't believe it's possible on the platform unless you are a VOIP app.

https://stackoverflow.com/questions/19068762/will-ios-launch-my-app-into-the-background-if-it-was-force-quit-by-the-user?rq=1
