### ISSUE TITLE
IOS pod install error: Specs satisfying the RNNotifee (from ../node_modules/@notifee/react-native) dependency was found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by somchithDroppin** [notifee/react-native-notifee#102]
This error happened when I start pod install, I tried to change the deployment target to 10.3 and 13.5 but It still not working. 

Adding a custom script phase for Pod RNNotifee: [NOTIFEE] Config
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Detected React Native module pods for BVLinearGradient, RNCAsyncStorage, RNCCheckbox, RNCustomizedImagePicker, RNDateTimePicker, RNFBApp, RNFBAuth, RNFBMessaging, RNFS, RNGestureHandler, RNNotifee, RNPermissions, RNReanimated, RNSVG, RNScreens, RNVectorIcons, react-native-camera, react-native-camera-kit, react-native-fbsdk, react-native-geolocation, react-native-maps, react-native-netinfo, react-native-slider, react-native-splash-screen, react-native-sqlite-storage, and react-native-viewpager
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "RNNotifee":
  In Podfile:
    RNNotifee (from `../node_modules/@notifee/react-native`)

Specs satisfying the `RNNotifee (from `../node_modules/@notifee/react-native`)` dependency was found, but they required a higher minimum deployment target.
<img width="2075" alt="Screen Shot 2020-07-06 at 17 06 34" src="https://user-images.githubusercontent.com/55729507/86582553-02c58280-bfac-11ea-835e-9c215cd48c6d.png">

Thanks and Regards,
Droppin Team.

**Comment by lkwjohn** [comment]
Facing the same issue too, using 

- "@notifee/react-native": "^0.9.1"
- "react": "16.8.6"
- "react-native": "0.60.4"

**Comment by mikehardy** [comment]
It would help to post relevant files, e.g. the Podfile.
I have 10.0 set in my Podfile and it works fine
You might try deleting Podfile.lock and trying pod install again?

**Comment by somchithDroppin** [comment]
@mikehardy I found the solution. Earlier, I only changed the target in Xcode but not in podfile. Thank you very much.

**Comment by mikehardy** [comment]
multi-platform development is nearly impossible :-), glad you found your problem and are moving forward, cheers
