### ISSUE TITLE
custom sound / no sound doesn't work on Android 7 

### ISSUE THREAD

**Issue by yotam-nots** [notifee/react-native-notifee#105]
Hey,
I'm unable to set a custom sound or no sound on Android 7. No matter what I try the default sound plays.
With `android: {sound: "ring", ...}` the ring.mp3 file doesn't play (instead the default sound plays)
With `android: {sound: undefined, ...}`(or without the sound key), the default sound plays

on Android >= 8.0 both custom sound and no sound work as expected (I didn't test on Android < 7)
I was able to reproduce on a physical device and AVD running Android 7.0 (API 24)

Example code:
```javascript
const displayNotification = async (data) => {
  try {
    const test = await notifee.createChannel({
      id: "test",
      name: "test",
      importance: AndroidImportance.LOW,
    });
    await notifee.displayNotification({
      id: data.tag,
      title: data.title,
      subtitle: data.channelName,
      body: data.body,
      android: {
        importance: AndroidImportance.LOW,
        channelId: test,
        // sound: "ring",
      },
    });
  } catch (error) {
    console.error(error);
  }
};
```

**Comment by helenaford** [comment]
thanks @yotam-nots for reporting this bug. A fix should be coming soon. In the meantime, you can pass in `defaults: [AndroidDefaults.LIGHTS, AndroidDefaults.VIBRATE]` which will let the custom sound to play. By setting these defaults, it will turn off the default sound too.

**Comment by yotam-nots** [comment]
Thanks @helenaford, that solved it

**Comment by helenaford** [comment]
fix has been released. so if you want a custom sound you don't need to set `defaults`. You can have a custom sound, if that fails to resolve, the default sound will play.  To disable default sound, you need to still do the above `defaults: [AndroidDefaults.LIGHTS, AndroidDefaults.VIBRATE]`.

**Comment by mars-lan** [comment]
What if I want the notification to not have sound, lights, or vibration on Android < 8?
Setting `defaults: []` leads to the following error

```
Error: notifee.displayNotification(*) 'notification.android.defaults' expected an array containing AndroidDefaults.
```

Not setting `sound` falls back to the default system sound, which is different from the doc: https://notifee.app/react-native/reference/notificationandroid#sound
