### ISSUE TITLE
Badge notifications are not showing 

### ISSUE THREAD

**Issue by sanjayatms** [notifee/react-native-notifee#108]
I have added complete code in my IOS setup regarding badge notifications , here is below code

```
notifee.setBadgeCount(1).then(() => console.log('Badge count set!'));
    notifee.onBackgroundEvent(async ({ type, detail }) => {
      console.log(type);
        const { notification, pressAction } = detail;
        if (type === EventType.DELIVERED) {
          // Increment the count by 1
          await notifee.incrementBadgeCount();
        }
        // Check if the user pressed the "Mark as read" action
        if (type === EventType.ACTION_PRESS) {
          // Decrement the count by 1
          await notifee.decrementBadgeCount();
          // Remove the notification
          await notifee.cancelNotification(notification.id);
        } 
   });
```

Both background and push notifications modes are enables in xcode as well but i didn't get any badge notifications how can i check using simulator because in simulator i have tried to add button interface to check notiification but i got only banner notification but not showing  badge icon in my application 

Please help

**Comment by helenaford** [comment]
Hi, mmm not sure why it's not showing...  should work the same on a real device and simulator. If you do this (only call   `setBadgeCount`) does it work? 
```
<Button
  title="Set Badge Count"
  onPress={(): any => notifee.setBadgeCount(1)}
 />
```
