### ISSUE TITLE
Duplicated notification

### ISSUE THREAD

**Issue by yangj56** [notifee/react-native-notifee#113]
I am using both react native firebase and add on of notifee to customise notification banner with appearance icon.

However, on android i am receiving 2 banners (1st banner is from the default notification which is the react native firebase which i have no control and the 2nd banner is from notifee.displayNotification method which comes with the customize icon).

Is there any way i can disable the 1st banner or can i modify the 1st banner with customize icon so that i dont call notifee.displayNotification method manually.

Thank you

**Comment by mikehardy** [comment]
Hi there! react-native-firebase documentation should have information on how to alter the default notification (as should the firebase-android-sdk repo's messaging / notification docs) - should be some changes in either AndroidManifest.xml or something in firebase.json I think? Sorry I'm being vague - I know it's possible but haven't done it.

The other option is to use *only* data-only notifications (no `notification` in the JSON payload sent as firebase cloud messages) and then in the handler you register in `firebase.messaging()` for `.onMessage()`, call the Notifee APIs to post what you like.

I personally like complete notification control so I use data-only notifications for almost everything

**Comment by yangj56** [comment]
Hi,
Thanks for you suggestions.
I have tried both and both works well.
I updated Androidmanifest.xml by appending this:
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_notification" />
