### ISSUE TITLE
Does a silent push always call the js code

### ISSUE THREAD

**Issue by supermar1010** [notifee/react-native-notifee#114]
Hello,
we're thinking about migrating from feact-native-push-notifications. The reason is even in a release build our javascript code does not get called on a remote silent notification if the app is dead. So for exampl in android by swiping it away, in iOS for example after a restart. Does this work with this library? Additional question does a silent push start the whole app with this library?
I unfortunately cannot test this, as I cannot do release builds without purchasing a licence.

**Comment by mikehardy** [comment]
All of the platforms make their own "decisions" on whether they will wake your app or not, it can vary on user interaction patterns with the app on that device, how expensive it is to start the app (if the device is slow, for instance), total power usage of the app over time (how many times did you send messages and wake it up?), who the vendor is (Xioami can burn in Dante's inferno in my opinion, they're the worst at not waking) etc etc etc

So there's no short answer I think.

Have you tried a release build to test? I believe you can, and I believe that's the only way to see, for your project use pattern, on your devices

**Comment by supermar1010** [comment]
Ah ok, I thought it wouldn't work in release mode because of the missing license, I'll try.

Ok so there's basically no gurantee that the silent push is delivered. But as I understood you in a best case scenario, i.e. the OS decides to wake the app, it does not matter if the app is running or not for the listener to get called?

**Comment by mikehardy** [comment]
you can try perhaps putting an example string in the license field for a full test.

if the app is already running and your project is configured / coded correctly then there's no wake up problem, your listener should be called

but this is important: you are confusing cloud messages and device notifications, be very careful.

cloud messaging is handled by cloud messaging libraries (like react-native-firebase) and is something almost everyone gets wrong but is out of the scope of this library. It has all the reliability issues I mentioned.

notifications are when a visible thing is popped up for the user and interacted with. That's this library. Those events are very reliable.

Be sure what exactly you are testing

**Comment by supermar1010** [comment]
Ah ok, so this library only handles, the showing of locally invoked notifications? Then sorry to bother you, I confused something. Thank you for your help anyway :)
