### ISSUE TITLE
Images from url in iOS notifications

### ISSUE THREAD

**Issue by ANIBIT14** [notifee/react-native-notifee#118]
When sending a uri that is a url for an image from our cdn, in iOS it is not displaying this image but in android it is.
Hoping someone can help me in understanding this behaviour and how to have image notifications in iOS from a url

**Comment by Ehesp** [comment]
cc @helenaford is this expected to work or a FR/possible?

**Comment by helenaford** [comment]
It's not expected to work at the moment, iOS only supports local images but it's on the roadmap.

**Comment by ANIBIT14** [comment]
@helenaford thanks for the clarification

**Comment by helenaford** [comment]
Remote image support is now released in v0.13.0. Please see [release notes](https://notifee.app/react-native/docs/release-notes#0130) or [docs](https://notifee.app/react-native/docs/ios/appearance) for more info.
