### ISSUE TITLE
iOS: onForegroundEvent not triggered on notification delivery

### ISSUE THREAD

**Issue by mars-lan** [notifee/react-native-notifee#125]
Thanks for adding the trigger support for iOS in 0.12. However, it seems to behave differently from Android. On Android, when a scheduled notification is delivered, `onForegroundEvent` is triggered with `EventType.DELIVERED`, whereas on iOS, the notification is shown directly to the user without invoking `onForegroundEvent` despite having the app running in foreground.

**Comment by helenaford** [comment]
release 0.12.2 is up with the bug fix :)
