### ISSUE TITLE
IOS: Critical flag and custom sound not working

### ISSUE THREAD

**Issue by supermar1010** [notifee/react-native-notifee#129]
Hello,
I'm sending a local push notification via notifee. The notification shows up. But it always plays the default sound in the normal sound volume.

My code looks like this:

```ts
  const authSettings = await notifee.requestPermission({
    alert: true,
    criticalAlert: true,
    announcement: true,
    badge: true,
    carPlay: true,
    provisional: false,
    sound: true,
  });

// ...

  await notifee.displayNotification({
    title: i18next.t('NOTIFICATION_TITLE'),
    body: 'some string',
    ios: {critical: true, sound: 'sirene', criticalVolume: 1},
  });
```

The output from authSettings is:

```log
 Permission settings: {"alert": 1, "announcement": -1, "authorizationStatus": 1, "badge": 1, "carPlay": -1, "criticalAlert": -1, "inAppNotificationSettings": 0, "lockScreen": 1, "notificationCenter": 1, "showPreviews": 1, "sound": 1}
```

So it seems as if the app doesn't have the right permission for critical alerts, but why? I did request it, and tapped allow in the UI

There's a file siren.caf under right in the project root. I also completely reinstalled the app, but no sound will play. Any suggestion where to put the file, and how to make the critical alert work.

I tried it on an iPhone 6 Plus with iOS 12.4.8 and an iPhone X with iOs 13.6.1

**Comment by helenaford** [comment]
Hi, for local sounds you need to pass in the file extension so `siren.caf` and hopefully you should be able to hear your custom sound.

**Comment by supermar1010** [comment]
Ah ok, thanks 

For the criticalAlert I just found this so I guess this only works after apples approval.

**Comment by helenaford** [comment]
Awesome, glad it worked :) 

Out of curiosity did you see this example [here](https://notifee.app/react-native/docs/ios/behaviour)
` // iOS resource (.wav, aiff, .caf)
    sound: 'local.wav',
`
We can add an extra note to this section to highlight that the extension needs to be included, if that would help?

And, yes, thanks for the link! Looks like a requirement for apps in release which will be good to have in the docs too.

**Comment by supermar1010** [comment]
Well I guess I'm blind then :D 
I read the android documentation first, and then I guessI didn't read cautiously enough. Maybe you could add a warning, this is different to andorid, or just hope the other people are able to properly read something
