### ISSUE TITLE
[Question] Playing custom song from remote sound file

### ISSUE THREAD

**Issue by VivienTournie** [notifee/react-native-notifee#132]
Hello,

I have a question for notification sound (trigger notification). The Notifee documentation says the following :

> Customs sounds must be local .mp3 files. Unfortunately, it is not possible to use remote sound files at this time.

My goal is to play a streaming song from (for example) Napster API. Those are .mp3 remote files (30sec).
How did you planned to implement this feature in Notifee ? 

Will it allow us to just put an url of a .mp3 remote file in the notification parameters, or would we need to create our own player like https://github.com/react-native-kit/react-native-track-player and play the sound manually ?

Thanks a lot for the answer.

P.S : I saw on https://notifee.app/react-native/docs/triggers that links on TimestampTrigger and IntervalTrigger are going 404 Error page.

**Comment by helenaford** [comment]
Hi, with the Notifee API, you can use `iOS Attachments` ([docs](https://notifee.app/react-native/docs/ios/appearance#attachments)) which will play a sound file. 

All the supported file types are listed on the [official Apple docs](https://developer.apple.com/documentation/usernotifications/unnotificationattachment).   

For remote file support when implemented, the plan is that you would be able to pass in a url that points to an audio file and the API will be able to attach it to the notification. 

No external player is needed, Apple takes care of any playable media files. 

Also, thanks for letting us know about the 404s, they've been updated.

**Comment by VivienTournie** [comment]
Thanks for the quick answer !
> For remote file support when implemented, the plan is that you would be able to pass in a url that points to an audio file and the API will be able to attach it to the notification.
> 
> No external player is needed, Apple takes care of any playable media files.

I'm assuming it will be the same for Android ? Do you have an ETA for this great feature ?

**Comment by helenaford** [comment]
No problem, it's good to get feedback and see what features are wanted the most.

For Android, you would use something called 'Media Style' notifications (https://notifee.app/react-native/docs/android/styles#media) which is coming soon. 

For iOS Attachments, all I can say atm is that remote urls is high up on the Roadmap.

**Comment by helenaford** [comment]
iOS Attachments now supports remote media files in release v0.13.0 (please see [release notes](https://notifee.app/react-native/docs/release-notes#0130)) for more info.

**Comment by helenaford** [comment]
Closing this in favour of #9 for Android media attachments.
