### ISSUE TITLE
I have added to 2 action I want to just clear notification but not want to app to be launched in 1 button action?

### ISSUE THREAD

**Issue by HarshitPadalia** [notifee/react-native-notifee#133]
Hello, I have 2 button actions in notification called accept and reject on accept button press app Launched and also on click of reject app launched but is there any way to just clear notification on reject click and won't launch app?

**Comment by Ehesp** [comment]
Can you post some code? How are you creating the actions?

**Comment by HarshitPadalia** [comment]
@Ehesp   I have used this code and facing issue in android and iOS not tested
  const channelId = await notifee.createChannel({
    id: 'default',
    name: 'Call channel',
    importance: AndroidImportance.HIGH,
    sound: 'default',
    bypassDnd: true
  });
  // Display a notification
  await notifee.displayNotification({
    title: JSON.parse(message.data.notifee).title,
    body: JSON.parse(message.data.notifee).body,
    android: {
      channelId,
      category: AndroidCategory.CALL,
      colorized: true,
      pressAction: {
        id: "default"
      },
      actions: [{
        title: "Accept",
        pressAction: {
          id: "accept",
          launchActivity: 'default',
        }
      }, {
        title: "Reject",
        pressAction: {
          id: "reject",
        }
      }],
    },
  });
}
-> after receiving notification if I press on notification body then app should open but notification just clears out but app not launching

**Comment by helenaford** [comment]
Hi, it's an issue that we're looking into. Please see #121. If you add launchActivity: 'default' in pressAction it should open the app. For Example:

pressAction: { id: 'default', launchActivity: 'default' }
