### ISSUE TITLE
On notification tap notification. just clears but application won't open

### ISSUE THREAD

**Issue by HarshitPadalia** [notifee/react-native-notifee#134]
On notification tap notification. just clears but application won't open

**Comment by Ehesp** [comment]
Please provide some more details. What platform? Code etc.

**Comment by HarshitPadalia** [comment]
I have used this code
  const channelId = await notifee.createChannel({
    id: 'default',
    name: 'Call channel',
    importance: AndroidImportance.HIGH,
    sound: 'default',
    bypassDnd: true
  });
  // Display a notification
  await notifee.displayNotification({
    title: JSON.parse(message.data.notifee).title,
    body: JSON.parse(message.data.notifee).body,
    android: {
      channelId,
      category: AndroidCategory.CALL,
      colorized: true,
      pressAction: {
        id: "default"
      },
      actions: [{
        title: "Accept",
        pressAction: {
          id: "accept",
          launchActivity: 'default',
        }
      }, {
        title: "Reject",
        pressAction: {
          id: "reject",
        }
      }],
    },
  });
}
