### ISSUE TITLE
Android app does not open on notification click

### ISSUE THREAD

**Issue by supermar1010** [notifee/react-native-notifee#135]
Hello,
I have had success so far with this library, one thing I could not get to work yet, is to open the app on notification tap.

This is how I send the notification
``` ts
await notifee.displayNotification({
    title: 'Something',
    body: 'Something',
    android: {
      channelId,
      importance: AndroidImportance.HIGH,
      pressAction: {
        id: 'default',
      },
      style: {
        type: AndroidStyle.BIGTEXT,
        text: 'Something',
      },
    },
    data: {type: 'alarm', missionId: missionId},
    ios: {critical: true, sound: 'someSound.caf', criticalVolume: 1},
  });
```

**Comment by helenaford** [comment]
Hi, it's a known bug that we're currently fixing. Please see #121. If you add `launchActivity: 'default'` in `pressAction` it should open the app. For Example:

`pressAction: {
        id: 'default',
launchActivity: 'default'
      }`

**Comment by supermar1010** [comment]
Thanks for the prompt reply! :)

I did not see the other issue/thought it was related
