### ISSUE TITLE
can I use notification payload without notifee key?

### ISSUE THREAD

**Issue by HarshitPadalia** [notifee/react-native-notifee#136]
can I use notification payload without notifee key? as currently I am able to receive notification only when I pass notifee key inside data of my payload
For details check this payload 

```
{ 
"to":"device token",
"priority": "high",
 "show_in_foreground": true,
 "data":{
	 "notifee": {
	  "title": "Incoming Call",
      "body": "Harshit is calling you..."
     },
      "uuid":"",
     "name":"RNVoip",
     "type":"call",
     "obj" : {"test" : "apple"}
}
}
```
-> this payload works but if I remove notifee key then it won't work
Payload without notifee key
```
{ 
"to":"device token",
"priority": "high",
 "show_in_foreground": true,
  "title": "Incoming Call",
      "body": "Harshit is calling you...",
 "data":{
	  "title": "Incoming Call",
      "body": "Harshit is calling you...",
      "uuid":"",
     "name":"RNVoip",
     "type":"call",
     "obj" : {"test" : "apple"}
}
}

```

**Comment by helenaford** [comment]
Hi, can you show how you're displaying the notification. A couple of questions come to mind:

- What are you passing to `displayNotification`? 

- Are you using RNFB? If so, you probably have something like this:
```
function onMessageReceived(message) {
  notifee.displayNotification(JSON.parse(message.data.notifee)); <-- HERE
}

messaging().onMessage(onMessageReceived);
messaging().setBackgroundMessageHandler(onMessageReceived);
```
Can you confirm `onMessage` listener is being called? If so, in the example code, you can change what's being parsed to `JSON.parse(message.data)`

**Comment by HarshitPadalia** [comment]
onMessage is called every Time but if I have not passed then I am not able to receive notification I have created notification via this code in this code if I replace message.data.notifee with message.data and send push without notified key in this case I am not able to see notification banner
```
async function onMessageReceived(message) {
  const channelId = await notifee.createChannel({
    id: 'default',
    name: 'Call channel',
    importance: AndroidImportance.HIGH,
    visibility: AndroidVisibility.PUBLIC,
    sound: 'default',
    bypassDnd: true
  });
  // Display a notification
  await notifee.displayNotification({
    title: JSON.parse(message.data.notifee).title,
    body: JSON.parse(message.data.notifee).body,
    data: message.data,
    android: {
      channelId,
      category: AndroidCategory.CALL,
      visibility: AndroidVisibility.PUBLIC,
      importance: AndroidImportance.HIGH,
      color: "#72CDCF",
      colorized: true,
      pressAction: {
        launchActivity: "default",
        id: "default",
      },
      actions: [{
        title: "Accept",
        pressAction: {
          id: "accept",
          launchActivity: 'default',
        }
      }, {
        title: "Reject",
        pressAction: {
          id: "reject",
        }
      }],
    },
  });
}

messaging().onMessage(onMessageReceived);
messaging().setBackgroundMessageHandler(onMessageReceived);
```

**Comment by helenaford** [comment]
OK, thanks for the example code. It could be that you're not parsing message.data to a JSON object, or title and body fail to resolve to strings. 

It's best to wrap displayNotification in a `try/catch` or append a `.catch` to see if any validation errors are thrown.

**Comment by HarshitPadalia** [comment]
onMessageReceived This method not called if notifee key not passed in payload

**Comment by HarshitPadalia** [comment]
it working once I have removed Json.parse from this code JSON.parse(message.data).title and replaced with this   message.data.title and message.data.body now it's working
