### ISSUE TITLE
[Question] IOS Appearence

### ISSUE THREAD

**Issue by Quantum-35** [notifee/react-native-notifee#137]
Is it possible now or in future to customise notification appearance and style in IOS just like it is in Android?

**Comment by helenaford** [comment]
Hi, thanks for the question. Anything in particular you are looking for on iOS? Hard to give a general answer because there'll be somethings you can do on Android that you can't do on iOS and vice versa.

**Comment by Quantum-35** [comment]
@helenaford Is it possible to style notification title and body text in IOS just like it is in Android. I am asking this so that the notification appearance can be similar in both platforms and use our brand's styles.

**Comment by helenaford** [comment]
As far as I know, it's not possible to do the same thing with iOS, in terms of using html to style text, but it should be possible to add emojis.
