### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by evrimfeyyaz** [notifee/react-native-notifee#15]
I'm not sure if this is the right place to ask about the pricing, if it's not, feel free to remove this issue.

As a software developer, I completely understand how much effort it requires to develop a library like this, and I fully support you charging for it.

That being said, I feel that the price is too expensive for indie developers and too cheap for enterprises. What are your thoughts on this?

Are you considering maybe a lite version, or a separate pricing for indie developers? I would really love to use Notifee if the price comes down to somewhere below $50.

Again, please don't take this as a criticism or an effort to undervalue all the work that went into this library, I am only asking out of curiosity.

**Comment by Ehesp** [comment]
Hey - your thoughts are also similar to ours and we've had many chats about how to work the pricing model. The price we settled at was "somewhere in the middle" for what we thought was fair for the time/effort/long term goals we have.

We have thought about setting up a "enterprise vs indi/solo" pricing model, but in reality we weren't sure how we could actually manage that. We're a small team and want to focus on the product rather than managing/checking licenses. 

Happy to hear thoughts though, we've tried to open it up to be free to those wanting to use it on a non-commercial basis.

**Comment by juddey** [comment]
While we're at pricing,is pricing $240, is that in your home currency or UK Pounds or Martian zaloots?
(Martian Zaloots are totally the next bitcoin, btw)

**Comment by Ehesp** [comment]
That's 240 USD. We kept it that as it seems to be the "norm", but we're GBP ourselves :D

**Comment by zek** [comment]
I wonder if this 240$ per app? May I use this library in my another applications.

**Comment by evrimfeyyaz** [comment]
> We have thought about setting up a "enterprise vs indi/solo" pricing model, but in reality we weren't sure how we could actually manage that. We're a small team and want to focus on the product rather than managing/checking licenses.

@Ehesp I completely get your point.

What do you think about having a lite version that maybe only includes the bare minimum (scheduling/showing/cancelling local and remote notifications) and none of the platform-specific bells and whistles?

**Comment by zwenza** [comment]
I would also love to pay for a proper notification library but 240$ is really a lot for an indie dev. 

Maybe you can think of offering something in the range of 50-100$ for us? Would be fine with having some limits in that version.

**Comment by WeslleyNasRocha** [comment]
![image](https://user-images.githubusercontent.com/19312651/78464009-88d6e200-76ba-11ea-97c7-b665c01571ca.png)
I'm sorry, but this is more then most people earn a month here in brazil

**Comment by zek** [comment]
it's almost minimum wage.

5 Nis 2020 Paz, saat 03:24 tarihinde Weslley Nascimento Rocha <
notifications@github.com> şunu yazdı:

**Comment by WeslleyNasRocha** [comment]
ok

**Comment by mikehardy** [comment]
Everyone focuses on "cost-based pricing" -> this will cost me XYZ amount.
The proper way to view it is "value-based pricing" -> if I had to develop this or integrate with another product, *that* would cost me XYZ amount.

When people buy tools for work, that is productive tools that will earn a return on investment, you have to consider the value they will provide in comparison to other things. In that way a reasonable price is achieved.

I live in a developing country (Ecuador) and our minimum wage is $392/month. But developer here - especially those that could create or integrate a notifications library are around $1500-2500/month. So this library represents about 3-4 days worth of wages in what anyone could admit is a low wage situation.

You can answer for yourself whether that has enough value, but for me at least I believe obtaining real support and not rolling my own solution will save that 3-4 days of work effort

**Comment by erebus01** [comment]
> I wonder if this 240$ per app? May I use this library in my another applications.

Could you confirm if I'll need to buy a separate license for each of my apps? I have two at the moment that I want to use it for.

**Comment by mikehardy** [comment]
@Salakar or @Ehesp please correct me if I'm wrong - but @erebus01 https://notifee.app/react-native/docs/license-keys indicates you need a primary key for each production app. Non-production apps may use secondary keys so you may have e.g. test/stage/dev environments without buying keys for them, but separate production apps should mean separate key unless I'm misunderstanding the docs

**Comment by Ehesp** [comment]
A single license works on one Android app, and one iOS app.

**Comment by Eralyne** [comment]
Hey, I couldn't find this info anywhere but is this a one-time purchase for one license for each of the OS's or will we have to pay an annual fee afterwards to keep the license?

**Comment by mikehardy** [comment]
Invertase is UK time so I think they may be offline, take me as unofficial but I'm 99.9% sure it is a one-time fee, no recurring fee, including access to updates for lifetime. And @Salakar or @Ehesp  will correct me if I'm wrong I am certain ;-)

**Comment by glaydsoncosta** [comment]
I would love to pay something for you guys, but when I convert 240 USD for my currency (Brazilian Real) I get the shocking value of 1.282 BRL which is (believe me) too much for our reality.

In my case I just need simply to use firebase.notifications.displayNotification() and nothing more, but you guys ripped off this feature and now who (like me) need to simply show a notification needs to pay 240 USD to use an alpha product?

That’s really sad.

**Comment by glaydsoncosta** [comment]
> ![image](https://user-images.githubusercontent.com/19312651/78464009-88d6e200-76ba-11ea-97c7-b665c01571ca.png)
> I'm sorry, but this is more then most people earn a month here in brazil

That’s very vey expensive when you convert price to BRL and you must to add 6,38% of IOF (Financial Operations Fee). That’s really disappointing.

**Comment by 8BallBomBom** [comment]
@glaydsoncosta You make good points and it is unfortunate that the currency conversion isn't too good for you but bare in mind this is created by the same people who created and maintain the React Native Firebase module.
The money goes towards helping both modules in the long run.
Good work is being done here, worth every penny.

**Comment by mikehardy** [comment]
Also please note that for simple cases react-native-push-notification and other packages work great! No problem using those.

**Comment by glaydsoncosta** [comment]
> @glaydsoncosta You make good points and it is unfortunate that the currency conversion isn't too good for you but bare in mind this is created by the same people who created and maintain the React Native Firebase module.
> The money goes towards helping both modules in the long run.
> Good work is being done here, worth every penny.

I see, currency conversion is a BIG problem here in Brazil. And that's not doubt React Native Firebase is a great work!

**Comment by patrickreiner** [comment]
Honestly, I think for the functionality you are offering, $240 for a license is not bad at all, and completely worth it

**Comment by glaydsoncosta** [comment]
Just an updated on my comment: Following @mikehardy tips I've solved the problem without using Notifee. But anyway, when I have enought revenues with my app, I would pay RNFirebase guys with pleasure. Thank you!

**Comment by rafaelsilvestre** [comment]
I did some tests using the foreground service, but the license fee ... converting to BRL Brazilian currency ... it doesn't make sense to just use the foreground services part.

**Comment by mikehardy** [comment]
I've locked conversation on this issue as it is not advancing the conversation.
We understand the price cannot be supported by everyone everywhere. There are other options, and competition among packages is great. We think Notifee is worth it of course but obviously adults will disagree on this and that's okay. We sincerely wish everyone success with their projects

Cheers
