### ISSUE TITLE
onBackground event/getInitialNotification not triggered if clicking notification straight from firebase

### ISSUE THREAD

**Issue by supermar1010** [notifee/react-native-notifee#152]
Hello,
Clicking notifications send by notifee works like a charm. But when I send a notification with a text content directly from firebase and click on the notification the app opens, but neither `onBackgroundEvent` nor `getInitialNotification` fires/returns anything.

Is this to be expected for notifications not send by notifee, can I additionally call the corresponding methods from rnfirebaseio? Or does that conflict?

With best regards
Mario

**Comment by mikehardy** [comment]
I believe that is to be expected as notifee will have no knowledge of the notifications that it did not post?
I send data-only messages and post notifee notifications in my handler for this reason

I could see how in this scenario you might want interoperation between a firebase cloud message with notification payload and notifee handlers, but in my app the handlers are in fact unified (seems a sensible approach?) so it is not something I feel is missing? Have you tried unifying what is called by the notification handler hooks `@react-native-firebase/messaging` gives you with the handlers installed by `@notifee/react-native` ?

**Comment by supermar1010** [comment]
Ok :) I yesterday tried to register both handler that works flawless so far, so I'm gonna go that route. Why I even need that, it is crucial that the notification arrives and under iOS if the user force closed the app a silent notification will not always arrive, so thats why I have both :)

**Comment by mikehardy** [comment]
@supermar1010 I have the exact same case, I understand. I almost always use data-only cloud message and call notifee items with my firebase.messaging().onMessage handler, but exactly as you say they are not 100% reliable (well, nothing is but you understand me) so for certain things I send notification payloads. Both my notification tap hooks map into one handler though and so far (for me) it has been effective

I hope it is also successful for you
