### ISSUE TITLE
isBatteryOptimizationEnabled is returning an object instead of boolean 

### ISSUE THREAD

**Issue by mars-lan** [notifee/react-native-notifee#156]
```
const optimized = await notifee.isBatteryOptimizationEnabled();
console.log(JSON.stringify(optimized));
```

prints

```
{"isBatteryOptimizationEnabled":false}
```

but both the [type](https://github.com/notifee/react-native-notifee/blob/5e1764456f5f3dd00fef9d99c6ab686ac33c4717/src/NotifeeApiModule.ts#L487) & [doc](https://notifee.app/react-native/docs/android/behaviour#background-restrictions) suggest that it should return a boolean directly.

**Comment by helenaford** [comment]
oooh good catch!! Will get that fixed.
