### ISSUE TITLE
[Question] Is there an option to have more than one licence key within notifee.config.json regading e.g. bundle ID

### ISSUE THREAD

**Issue by lorenc-tomasz** [notifee/react-native-notifee#157]
Hi,
just wondering if there is better option to manage licences within the `notifee.config.json` file.

Current scheme looks like:

```javascript
{
  "android": {
    "license": "XXXX.YYYY.ZZZZ"
  },
  "ios": {
    "license": "XXXX.YYYY.ZZZZ"
  }
}
``` 

In my case we have e.g. test, uat, dev builds with different bundle id and package names. So now I need to inject / replace licence keys each time based on the build type. 

Maybe there is an option to put there all licence keys at once, e.g.:

```javascript
{
  "android": {
    "licenses":
         {
             "id": "com.example.app",
              "license": "XXXX.YYYY.ZZZZ.1", 
         },
         {
             "id": "com.example.app.test",
              "license": "XXXX.YYYY.ZZZZ.2", 
         },
         {
             "id": "com.example.test-app",
              "license": "XXXX.YYYY.ZZZZ.3", 
         },
  },
  "ios": {
    "licenses":
         {
             "id": "com.example.app",
              "license": "XXXX.YYYY.ZZZZ.1", 
         },
         {
             "id": "com.example.app.test",
              "license": "XXXX.YYYY.ZZZZ.2", 
         },
         {
             "id": "com.example.test-app",
              "license": "XXXX.YYYY.ZZZZ.3", 
         },
  },
}
``` 

?

**Comment by mikehardy** [comment]
Yes! https://github.com/notifee/react-native-notifee/pull/67#issuecomment-640136025

**Comment by lorenc-tomasz** [comment]
@mikehardy Thank you :)

**Comment by mikehardy** [comment]
Note: Needs corresponding documentation update, linking someone to a comment with the answer is nifty, but not really a great strategy ;-)

**Comment by helenaford** [comment]
[Docs](https://notifee.app/react-native/docs/license-keys#supporting-multiple-environments) have now been updated.
