### ISSUE TITLE
Request notifications and not just notificationIds

### ISSUE THREAD

**Issue by Sixzero** [notifee/react-native-notifee#159]
Hey All!

My problem is that, I would like to reschedule a previously scheduled reminder in our application, and I don't really know how I would be able to do this without keeping a map in cache about ids and currently scheduled reminders, since I can only use: `getTriggerNotificationIds`

**Comment by mikehardy** [comment]
Mmm - I believe doing exactly that - maintaining the capacity to regenerate any notification based on the id - is the expected solution. That's how I have always handled it at any rate

**Comment by Sixzero** [comment]
Ok. If you think that is a good option, then I close this issue. :+1:
