### ISSUE TITLE
getInitialNotification doesn't work 

### ISSUE THREAD

**Issue by KaterinaParashchyevina** [notifee/react-native-notifee#16]
Hi guys! Now I'm testing your package in debug mode. For my product is very critical how 'App open events' feature  works. Before buying the package I have to be sure that this feature is fully workable.  But in some case I can't test it. I call this part on 'componentDidMount'
``` javascript
 const initialNotification = await notifee.getInitialNotification();
        if (initialNotification) {
            console.log('Notification caused application to open', initialNotification.notification);
            console.log('Press action used to open the app', initialNotification.pressAction);
        }
```
I always get null in Android. Then I dig into native code and found following:
``` java
    @KeepForSdk
    public void getInitialNotification(MethodCallResult<Bundle> var1) {
        if (nz_f.nz_t()) {
            nz_f.nz_t("getInitialNotification");
            var1.onComplete((Exception)null, (Object)null);
        } else {
            nZ_ne var2;
            if ((var2 = (nZ_ne)nz_t.nZ_o.nz_n.removeStickyEvent(nZ_ne.class)) == null) {
                var1.onComplete((Exception)null, (Object)null);
            } else {
                MethodCallResult var10000 = var1;
                Bundle var3;
                Bundle var10001 = var3 = new Bundle;
                var3.<init>();
                var3.putAll(var2.nZ_o);
                var10001.putBundle("notification", var2.nz_n.toBundle());
                var10000.onComplete((Exception)null, var3);
            }
        }

    }
```
I moved to nz_t method and get this :
``` java
 public static boolean nz_t() {
        if ((n.o.t.i.f.e.e.nZ_o.nz_n.getApplicationInfo().flags & 2) != 0) {
            return false;
        } else {
            int var0 = nz_nn.nZ_o.nz_n("lvs", 1);
            int var1;
            return (var1 = nz_nn.nZ_o.nz_n("rvs", 1)) != 1 && var1 != 0 || var0 != 1 && var0 != 0;
        }
    }
```
It looks like method always return null if app is run in debug mode. 
Of cause I can be wrong so please tell how can I test "app open event feature" in debug mode.

**Comment by ja-bravo** [comment]
Same here, can't get getInitialNotification to return anything other than null in dev mode.
Everything else seems to work just fine, including background and foreground notifications but this here is a blocker for my company right now.

```js
 useEffect(() => {
    messaging()
      .registerForRemoteNotifications()
      .then(r => {
        const granted = messaging().requestPermission();
        messaging().subscribeToTopic('developers');
        if (granted) {
          notifee
            .getInitialNotification()
            .then(initial => {
              if (initial) {
                console.log('Initial');
                console.log(initial);
              } else {
                console.log('no initial notification');
              }
            })
            .catch(e => console.log(e));
        } 
      });
  }, []);
```

**Comment by kperreau** [comment]
Same problem for me, i can't buying the package if this feature is not working.
Trying to get the initial notification from remote (firebase Messaging) and always return null if i open app from notification when app is killed.
Worste, if app is in background (not killed), i can't reach the event getInitialNotification().

- React-Native 61.5 (full hook, stateless)
- Hermes
- Tested with a real device connected (samsung s8+) in debug mode

**Comment by mikehardy** [comment]
There was a problem with intent handling and splash screens etc in the react-native-firebase repo, resolved with some specific steps in AndroidManifest to make the intent go to the right place https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454 - no idea at all if this applies here but if someone could confirm that they definitely don't have splash screens eating the launch intent, that might help.

**Comment by Ehesp** [comment]
Hey all

Thanks for the feedback - @mikehardy  we actually implemented the initial notifications totally different to RNFB :D

Can you guys please show what notification options you're using to display the notification? When a `pressAction` is provided to the body/actions, and that press action causes an open of the app, that's when we save the notification into it's initial state, hence knowing the options would help massively :)

We'll be sorting this as priority so don't worry!

**Comment by Ehesp** [comment]
Also it's worth mentioning (does mention in the docs but maybe not obvious enough?), that once a call to `getInitialNotification` is called it is then cleared, so if there's a "double" mount/call that could be a problem.

Also @ja-bravo based on your code snippet, there is a couple of general issues:

1. `getInitialNotification` has no impact on whether they're registered for notification or have them granted.
2. You have nested promises, and some calls which do not wait for promises so your code may not be even working as expected. A better example would be:

```js
function App() {
  async function bootstrap() {
    const initialNotification = await notifee.getInitialNotification();

    if (initialNotification) {
      // Do something
    }

    await messaging().registerForRemoteNotifications();
    const granted = await messaging().requestPermission();
    await messaging().subscribeToTopic("developers");
    // etc
  }

  useEffect(() => {
    bootstrap().catch(e => console.error(e));
  }, []);
}
```

In your example, `granted` will always be `true` because you're not waiting for the result, so `granted` = `Promise`, which is a truthy value :)

**Comment by kperreau** [comment]
> 
> 
> Hey all
> 
> Thanks for the feedback - @mikehardy we actually implemented the initial notifications totally different to RNFB :D
> 
> Can you guys please show what notification options you're using to display the notification? When a `pressAction` is provided to the body/actions, and that press action causes an open of the app, that's when we save the notification into it's initial state, hence knowing the options would help massively :)
> 
> We'll be sorting this as priority so don't worry!

I'ts not a local notification but a remote.
I have no `pressAction` option, just clicking on the notification.

If it can help, yes i'm using `react-native-splash-screen`.

**Json notification exemple:** 
`{
  "message": {
    "token": "XXXXX",
    "data": {
      "type": "newComment",
    	"photoID": "XXXXX",
	    "fromUserID": "XXXXX"
    },
    "notification": {
      "title": "Jhon commented your BeReal",
      "body": "test"
    },
    "apns": {
      "headers": {
        "apns-priority": "5"
      },
      "payload": {
        "aps": {
          "thread-id": "XXXXX"
        }
      }
    },
    "android": {
      "priority": "normal",
      "notification": {
        "channel_id": "default",
        "icon": "ic_notification"
      }
    },
    "fcm_options": {
      "analytics_label": "newComment"
    }
  }
}`

**Comment by Ehesp** [comment]
Conscious there could be different situations going on here...

@kperreau Notifee only manages it's own notifications, not those which have been created via the `notification` payload, which the system creates automatically. If you check out the [FCM](https://notifee.app/react-native/docs/integrations/fcm) guide it suggests to send the data over via the FCM payload and construct the notification manually (allowing for Notifee functionality to exist).

That being said, in theory we could also hook into "external" notifications and also manage them (e.g. checking for actions, providing default "press" behaviour).

**Comment by ja-bravo** [comment]
Thanks for the answer @Ehesp. I copy-pasted that from the RNFB messaging documentation without double-checking, my bad.

We still can't get it to work on our app. We're not using react-native-splash-screen.

```js
const AppContent = () => {
  async function bootstrap() {
    const initialNotification = await notifee.getInitialNotification();
    if (initialNotification) {
      console.log('initial notification'); // Never reaches here
      console.log(initialNotification);
    }

    await messaging().registerForRemoteNotifications();
    const granted = await messaging().requestPermission();
    console.log(`granted: ${granted}`); // Logs granted: true
    if (granted) {
      await messaging().subscribeToTopic('developers');
      console.log('sub to developers');
      messaging().onMessage(onMessageReceived); // Works perfectly, we can display the notification using notifee
    }
  }

  useEffect(() => {
    console.log('Run bootstrap');
    bootstrap().catch(e => console.log(e)); // No error gets logged
  }, []);
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName={SCREENS.Loading} headerMode="none">
        <Stack.Screen name={SCREENS.Loading} component={LoadingScreen} />
        <Stack.Screen name={SCREENS.Landing} component={LandingScreen} />

        <Stack.Screen name="AppStack" component={AppStack} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

const App = () => {
  return (
      <ApolloProvider client={apolloClient}>
        <AppProvider>
          <AppContent />
        </AppProvider>
      </ApolloProvider>
  );
};
```

I've tried sending the notification with both the data and notification fields
```js
 const message = {
      topic: 'developers',
      notification: {
        title,
        body,
      },
    };

 const message = {
      topic: 'developers',
      data: {
        title,
        body,
      },
    };
```

The one with the notification field gets received with the app killed/in the background but getInitialNotification returns null.

The one with the data field gets received with the app killed/in the background if I use ```messaging().setBackgroundMessageHandler()``` and ```notifee.onBackgroundEvent()``` and I can display a local notification but it won't open the app once it's tapped.

**Comment by Ehesp** [comment]
> and I can display a local notification but it won't open the app once it's tapped.

By default, it doesn't as it's fully in your control. Have you read [these docs](https://notifee.app/react-native/docs/android/interaction#press-action)?

> Notifee does not provide any default interaction behaviour when a user presses a notification. The Android guidelines suggest a notification should always open the application when pressed. In React Native, we have multiple options to exactly how the application opens.

You need to specify a press action, and if that press action causes the app to open, the initial notification will be set ready to be consumed.

**Comment by Ehesp** [comment]
Closing this one  - please let me know if you have issues after going through the above points.

**Comment by rajnishcoder** [comment]
> There was a problem with intent handling and splash screens etc in the react-native-firebase repo, resolved with some specific steps in AndroidManifest to make the intent go to the right place [crazycodeboy/react-native-splash-screen#289 (comment)](https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454) - no idea at all if this applies here but if someone could confirm that they definitely don't have splash screens eating the launch intent, that might help.

Dosn't have `react-native-splash-screen` still getInitialNotification doesn't work.

**Comment by mikehardy** [comment]
@rajnishcoder you quoted my question but did not answer. My question was a general question "splash screens" not just that module. Do you have *any* activity in AndroidManifest.xml set as LAUNCHER other than your MainActivity? That's the important part.
