### ISSUE TITLE
NullPointerException at launch

### ISSUE THREAD

**Issue by mars-lan** [notifee/react-native-notifee#160]
Start seeing NullPointerException in production on quite a few Android devices after upgrading notifee to 0.13.0

Here's the log from Firebase Crashlytics
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
n.o.t.i.f.e.e.nz_f.nz_n (SourceFile:423)
n.o.t.i.f.e.e.-$$Lambda$E60Y5ndDEZUYHTvKcR_YxKM7hHw.onComplete (Unknown Source:6)
com.google.android.gms.tasks.zzj.run (com.google.android.gms:play-services-tasks@@17.1.0:4)
```

Seeing this on, a wide range of devices and Android versions (6-11), e.g.
- Samsung Galaxy S8-S10
- Google Pixel 2-4

**Comment by mikehardy** [comment]
@mars-lan thanks for this report (and also I want to mention I still have another crash investigation queued for you - I apologize for the velocity but want to emphasize I really value the reports and your collaboration, sincerely)

@helenaford this is sort of a build toolchain question - and it's more android-related which is where I may be able to add more value vs Obj-C but perhaps you already know - is there a way for us to distribute NDK symbolocation tables for customer crashes? In the AAR perhaps? or should we do a fresh build locally and with local tables available attempt to symbolocate? I could see this becoming a regular triage effort to hunt down the correct source line so I'm trying to think of something reproducible on our end that can accelerate our customer response

@mars-lan normally I'd recommend updating to current stable which is 0.13.1 at this point vs the 0.13.0 report but a quick code check confirms there were no android updates between the versions so I think we can be confident this report is vs the tip of main branch, no worries.

Is there any more information you can give about reproduction scenarios? I'm guessing not and we should be able to locate it anyway, but am compelled to ask

Cheers

**Comment by mars-lan** [comment]
I have a Galaxy S9 but was unable to reproduce this locally. FWIW, I'm using APK locally but [AAB](https://developer.android.com/platform/technology/app-bundle) on the Play Store. Not sure if that makes a difference.

**Comment by mikehardy** [comment]
w.r.t. symbolocation I don't believe that will matter at the moment, as I think we're obfuscating/stripping prior to putting them in the AAR in our build/release process. But that could be relevant to any proposed solution - thanks for mentioning it.

**Comment by helenaford** [comment]
Ah I think I can see what this is, it happen if you had triggers set before v0.13.0. I've just pushed up a fix. Can get a patch out quickly, but will do some more tests locally. There should be a warning printing in the console, "The trigger notification was created using an older version, please consider recreating the notification." but it will still display the notification.

**Comment by helenaford** [comment]
Patch is up (v0.13.2) should fix it.

**Comment by mars-lan** [comment]
Thanks for the quick fix, @helenaford. Will roll this out to production and report back in a day or two.

**Comment by helenaford** [comment]
No worries, sorry for the bug in the first place 😅  we appreciate the reports/feedback and helping us weed these things out 😎

**Comment by mars-lan** [comment]
Ramped up the fix to 100% in production and no longer sees the NPE. Closing the issue.

**Comment by mikehardy** [comment]
Fantastic to hear! Thanks for the feedback @mars-lan
