### ISSUE TITLE
Release note for 0.13.1?

### ISSUE THREAD

**Issue by mars-lan** [notifee/react-native-notifee#161]
https://github.com/notifee/react-native-notifee/releases/tag/v0.13.1 points to https://notifee.app/react-native/docs/release-notes which doesn't have any release note for 0.13.1.

**Comment by mikehardy** [comment]
Hmm - that's an oversight @helenaford :pray: - but I can say via code inspection on the release it was limited to a compile fix for iOS w.r.t. URL parsing in the remote image download feature. It did not touch Android functionality at all and thus won't have bearing on #160 if my guess you were checking for the common "an upgrade may fix it..." resolution related to #160

**Comment by helenaford** [comment]
Yep, I'm online today, so will add those. It was just a change with iOS, making sure the new features were updated as listed in 0.13.0.
