### ISSUE TITLE
Question : is the license lifetime? And on how many apps can it be used? 

### ISSUE THREAD

**Issue by Stevemoretz** [notifee/react-native-notifee#164]
First of all thank you for this, though this is a bit weird that it's a payed product because it's a total offline library but again pretty cool, so please explain more about the limitations I asked above.

**Comment by mikehardy** [comment]
Lifetime? yes
How many products? It is licensed by Android package name or iOS bundle id. So it is tied to those. It is possible to have "secondary" keys to cover sub-ids (think: `.staging`, `.dev` etc) but the FAQ discusses their limitations

Validation is performed via a JWT over the network, so it works completely offline yes but if validation fails for long enough, the package may stop working.

https://notifee.app/frequently-asked-questions/

**Comment by Stevemoretz** [comment]
Hi thanks for the answer this problem is completely solved by your explanation.

I'm gonna ask something off topic now it would be really nice you answered me.

I'm a developer too I'm planning to make some of my php and react native works with a license, but if I make my own license system with a few stupid if statements it's easily hackable, how would you do your license management systems would you please, give me some general idea or something, whatever I'm thinking of create sounds too vulnerable.

**Comment by mikehardy** [comment]
It's all vulnerable. Once bits are distributed they may be tampered with. Most humans have a strong sense of fairness though. I believe this library emits JWTs as license validators and pings a REST API to validate them.

From a security perspective I believe the correct tradeoff is whether hacking the the license costs more than the cost of the license, stated differently, a thing is adequately secured when the cost of defeating the security is higher than the cost of going along with it. For libraries, the cost of going along with it is the combination of actual license cost plus potential cost if you need support and can't get it.

Every product or thing you are security will have a different answer to how to secure it and how to price it

**Comment by Stevemoretz** [comment]
Thank you so much what you said totally makes sense.

You talked about hacking it would be more expensive than buying it,a jwt token that you're using for example and I thought about this before also, you send a request to the server get a response and check the response if programmer puts a log of your server or even simpler puts a or true for the next if statement the whole thing is hacked that easy.

As an example how do you make your system hard and expensive to hack?

**Comment by mikehardy** [comment]
The core library is packaged as a precompiled obfuscated aar, you would have to adept at java bytecode manipulations to hack it, and you'd have to redo them every single time we release and update.

I have work today so I won't answer further - apologies, there are plenty of discussions on this topic on the internet, and it's out of scope for support here

**Comment by Stevemoretz** [comment]
Yeah alright great explanation, but I was looking for Javascript based answers I'll look up the internet thanks anyways really useful information.
