### ISSUE TITLE
App crashes after pressing notification

### ISSUE THREAD

**Issue by photoroulette** [notifee/react-native-notifee#166]
Our app sometimes crashes after pressing a local notification while the app is running in the background. The app terminates due to uncaught exception 'NSInternalInconsistencyException', reason: **'Call must be made on main thread'.** This only happens on devices running iOS 14.

The stack trace points towards Notifee's **didReceiveNotificationResponse** handler. Does that handler submit something to a background queue?

![Screenshot 2020-10-08 at 09 03 19](https://user-images.githubusercontent.com/37245382/95428019-bc841480-0948-11eb-8e85-5bc51b6fe738.png)

**Library versions**
react-native: 0.63.3
@notifee/react-native: 0.13.2
@react-native-firebase/messaging: 7.9.0

**Comment by mikehardy** [comment]
Thanks for reporting this @photoroulette ! It is under review this very moment

**Comment by helenaford** [comment]
@photoroulette thanks for the information. I see you mentioned it happens sometimes. Does it happen for a particular notification with certain properties like actions or attachments? Trying to reproduce locally but can't recreate the error. Could this be related, https://github.com/invertase/react-native-firebase/issues/3944?

**Comment by photoroulette** [comment]
Unfortunately, I haven't figured out a way to reproduce this consistently.

The issue you linked to is certainly relevant, as some users in the discussion are reporting similar errors. We have tried making sure that the completion handler is executed on the main queue (as suggested), but that didn't help. That left us to think that Notifee's handler submits something to a queue that is (at least sometimes) run on a background thread. Did you find any calls to dispatch_after?

Thanks for looking into it!

**Comment by Salakar** [comment]
Looks like this error is actually happening inside RNFB, Notifee is just delegating to RNFB's delegate implementation, here's the code in Notifiee executed by the first line in the highlighted red box in your screenshot:

```obj-c
if (_originalDelegate != nil &&
             originalUNCDelegateRespondsTo.didReceiveNotificationResponse) {
    [_originalDelegate userNotificationCenter:center
               didReceiveNotificationResponse:response
                        withCompletionHandler:completionHandler];
}
```

`_originalDelegate` being RNFB in this case.

**Comment by photoroulette** [comment]
In our case, I think it's the other way around: The event is first handled by RNFB, then delegated to Notifee before it crashes. Correct me if I'm wrong. I will regardless investigate whether it helps to reverse the order of which the notification center delegates are registered.

Is that everything Notifee's handler is doing? I was at least expecting some logic to emit relevant events (onForegroundEvent etc.)?

**Comment by photoroulette** [comment]
@helenaford Steps to reproduce:
1. Open the app
2. Display a local notification
3. Press the local notification
4. Send the app to the background
5. Wait 30 seconds
6. Open the app again
7. App crashes

Tested this with a clean project (react-native init) and the example code from https://notifee.app/react-native/docs/displaying-a-notification, running on an iPhone 6S and iPhone XS.

**Comment by helenaford** [comment]
Thanks, I think I've fixed this, ensuring the `completionHandler` will run on the main queue. Will be doing some final checks and aiming for a release today.

**Comment by helenaford** [comment]
Release v0.14.0 has the bug fix. Thanks for your help, helping us debug this.

**Comment by julespaget** [comment]
Hi @helenaford , i'm facing the same issue but i don't use react-native-notifee, i just use react-native-firebase (v5).

So what do you do for fix the bug ?

Thank you.

**Comment by helenaford** [comment]
Hi, it was pretty much what I said above, making sure the `completionHandler` is run on the main queue. 

From looking at this [file](https://github.com/invertase/react-native-firebase/blob/v5.x.x/ios/RNFirebase/notifications/RNFirebaseNotifications.m), I can't see anything that would cause the same bug. But, you could try changing how the `completionHandler` is called in `didReceiveNotificationResponse`:

```
// from
 completionHandler();
        // to
         dispatch_async(dispatch_get_main_queue(), ^{
          completionHandler();
         });
```

But, I highly recommend to update, I've been there myself it may seem like a lot of work but it's worth it, especially with Apple updating their rules for the App Store constantly.

You can either upgrade to use RNFB with Notifee or use one of the other Open Source alternatives listed [here](https://notifee.app/react-native/docs/overview).

**Comment by julespaget** [comment]
I try to change this :

**Comment by julespaget** [comment]
In the file : AppDelegate.m 

```
-(void) userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {        
  [[RNFirebaseMessaging instance] didReceiveRemoteNotification:response.notification.request.content.userInfo];
  dispatch_async(dispatch_get_main_queue(), ^{
    completionHandler();
  });
}
```
But i always the same error.

**Comment by julespaget** [comment]
I replace dispatch_async with dispatch_sync and works fine !

**Comment by ElChawich** [comment]
can you please help me, i'm facing same issue, and i applied the solutions that you mentioned yet i'm still getting same error "Call must be made on main thread, was thrown while invoking complete on target  RNFirebaseNotifications"

this is my AppDelegate.m
```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>
#import <RnAlarmNotification.h>
#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>

@implementation AppDelegate

// Required to register for notifications
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
 [RNCPushNotificationIOS didRegisterUserNotificationSettings:notificationSettings];
}
// Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
 [RNCPushNotificationIOS didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}
// Required for the notification event. You must call the completion handler after handling the remote notification.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
// Required for the registrationError event.
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
 [RNCPushNotificationIOS didFailToRegisterForRemoteNotificationsWithError:error];
}
// IOS 10+ Required for localNotification event
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  [RNCPushNotificationIOS didReceiveNotificationResponse:response];
  [RnAlarmNotification didReceiveNotificationResponse:response];
  dispatch_sync(dispatch_get_main_queue(), ^{
      completionHandler();
    });
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification withCompletionHandler: (void (^)(UNNotificationPresentationOptions options))completionHandler {
  [RnAlarmNotification didReceiveNotification:notification];
  completionHandler(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge);
}
// IOS 4-10 Required for the localNotification event.
//- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
//{
// [RNCPushNotificationIOS didReceiveLocalNotification:notification];
//}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"CCMM"
                                            initialProperties:nil];
  
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
    center.delegate = self;
  
  return YES;
}

//-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
//{
//  completionHandler(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge);
//}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```
