### ISSUE TITLE
[Question] Cancelling triggered notification and completing action in Android

### ISSUE THREAD

**Issue by ocsby** [notifee/react-native-notifee#169]
Hi,

I am working on a timestamp triggered notification with daily frequency.
The notification has interaction buttons where user can click Yes or No.
User can change notification schedule, so to achieve this, my thought was to cancel notification and create a new one whenever schedule changes.
In documentation, cancelling a triggered notification can be done by:

> There may be situations whereby you may want to cancel the trigger notification and stop any future notifications from displaying.
To cancel a trigger notification, the cancelNotification method can be called with the unique notification ID.

However, in the Android documentation's `Interaction` section:

> Once an action has been completed, the notification should be cancelled or updated.

With example code:
`await notifee.cancelNotification(detail.notification.id);`

In my test, I see that notification is not removed when I click on Yes or No button if cancel notification is not called (unlike ios which dismisses without canceling).

The question is wouldn't calling `cancelNotification` as mentioned in Android documentation "stop any future notifications from displaying"?  If so, do I have to reschedule the notification?

Any clarity would be very appreciated.
Thank you!

**Comment by helenaford** [comment]
Hi, thanks for your question. It sounds like you want the Android notification to update and then clear from the tray. There may be a gap in the API for this. Currently, like you mention, `cancelNotification` will remove it from the tray and cancel the trigger. Proposed API could be:
`cancelDisplayedNotification(id)`
`cancelTriggerNotification(id)`
Then in this instance, you would call `cancelDisplayedNotification(id)`.
Would that work? 

In the meantime, yes, you would need to call `cancel`, then call `createTriggerNotificaiton`.  For `createTriggerNotificaiton`, you can still use the same id as before.

**Comment by ocsby** [comment]
@helenaford 
Yes. The proposed API is what I was thinking as well.
Without that API, I think triggers with frequency/interval is not useful on Android interactive notification since you have to recreate it after every notification.

I will use the solution you mentioned, but would it be possible to know if the API can be included in future?

Thanks for your help.

**Comment by helenaford** [comment]
No problem, glad to help. Will mark this as an enhancement.

**Comment by helenaford** [comment]
Added new endpoints, `cancelDisplayedNotification` and `cancelTriggerNotification`, in release [v0.15.0](https://notifee.app/react-native/docs/release-notes#0150)
