### ISSUE TITLE
Add information how to support notifee when more than one push provider is used

### ISSUE THREAD

**Issue by lorenc-tomasz** [notifee/react-native-notifee#17]
Android doesn't allow an app to have more than one handler for com.google.firebase.MESSAGING_EVENT intent filter action. Only the first registered service will handle a firebase message. If you need to use multiple push providers, you have to make custom handler / register your custom FirebaseMessagingService service, eg. 

```
public class PushProvidersHandler extends FirebaseMessagingService {
    @Override
    public void onNewToken(String token) {
        super.onNewToken(token);
        // Do something with providers here
        ....
    }

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);
        // Do something with providers here
        ....
    }
}
```

**Comment by Ehesp** [comment]
Hey @lorenc-tomasz sorry for the delay in replying.

Right now, Notifee is a local service and doesn't subscribe to the intent, that is done by other libraries handling remote notifications (such as React Native Firebase). It may be best to create an issue over there?
