### ISSUE TITLE
Is their a way to notifications that destruct on an basis of interval on iOS

### ISSUE THREAD

**Issue by ANIBIT14** [notifee/react-native-notifee#171]
We want to trigger local notification for user with some data, in such a way that notification is active for 60 seconds and after that it destroys automatically or when user clears it, whichever happens first, we have done it on android, but is it possible do it on iOS

**Comment by mikehardy** [comment]
Hi there! Curious how you accomplished this in android? The only way I can think is to set an alarm for a minute and "update" the alert to dismiss it?

**Comment by ANIBIT14** [comment]
@mikehardy on android it was achieved by writing native code, not using notifee, if you want more detail I will ask my colleague to describe it here, as he was the person who implemented it.

**Comment by mikehardy** [comment]
Interesting - that's okay, no need to bug your colleague :-), I think creating a time trigger where you cancel the notification (if it still exists) is possible via the APIs here on android as well but I haven't tested it myself, I'm not 100% sure if a 60 second time based trigger is too small a value to work or not without actually testing

**Comment by helenaford** [comment]
Closing this as I don't think it's possible using local notifications. It would require a server to send a silent notification to let the app know when to delete it.
