### ISSUE TITLE
Is data notification required for background event to be captured?

### ISSUE THREAD

**Issue by Aayushi1301** [notifee/react-native-notifee#172]

**Comment by helenaford** [comment]
Hi, could you give more information? 
If it's to capture when a notification is received and you're are using React Native Firebase, you'll need to use [`setBackgroundMessageHandler`] (https://rnfirebase.io/messaging/usage#background--quit-state-messages) which does not require a data property.

**Comment by mikehardy** [comment]
I think this is between the two libraries.

If the app is not running and needs to wake up, then a cloud messages is one of the only ways to do it, but if it has a notification payload then the firebase SDKs handle it - your code doesn't get called.

If you send a data only Firebase Cloud Message with the correct contents to wake your app (for example, on iOS content-available is in there...), then your setBackgroundMessageHandler code will run and now you have control.

Within that handler you can then use Notifee APIs to post notifications and you will see background notifee events (notification delivered, notification pressed if the user taps it etc)

**Comment by helenaford** [comment]
This was a great question. Closing the issue as I think it's been answered but please don't hesitate to reopen if you want to discuss it further.
