### ISSUE TITLE
How to add large images on android local notifications ?

### ISSUE THREAD

**Issue by Aayushi1301** [notifee/react-native-notifee#173]
Similar to attachments https://notifee.app/react-native/docs/ios/appearance#attachments
 on ios, is there an option on android to show image below title and message(rich notifications). 
largeIcon on android still shows image on side of the text. I want it to be below it.

**Comment by helenaford** [comment]
Hi, I believe what you're looking for is [Big Picture Style](https://notifee.app/react-native/docs/android/styles#big-picture), displays an image below the text.
