### ISSUE TITLE
Package requires Xcode 12 as of version 0.13.1 but requirement is not noted anywhere

### ISSUE THREAD

**Issue by bjjeong** [notifee/react-native-notifee#174]
### Environment
```json
"@notifee/react-native": "0.13.1",
"react-native": "0.63.3",

Xcode: 11.6
```

### Issue
When I try to build my app in release mode, I get the following error:
```
error: exportArchive: ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk -o /var/folders/rx/90bsbdvx4vlfvzgxdcg_3mn80000gn/T/ipatool20201012-9880-7sdfqn/thinned-out/arm64/Payload/Bilt.app/Frameworks/NotifeeCore.framework/NotifeeCore --generate-dsym /var/folders/rx/90bsbdvx4vlfvzgxdcg_3mn80000gn/T/ipatool20201012-9880-7sdfqn/thinned-out/arm64/Payload/Bilt.app/Frameworks/NotifeeCore.framework/NotifeeCore.dSYM --strip-swift-symbols /var/folders/rx/90bsbdvx4vlfvzgxdcg_3mn80000gn/T/ipatool20201012-9880-7sdfqn/thinned-in/arm64/Payload/Bilt.app/Frameworks/NotifeeCore.framework/NotifeeCore
Status: pid 10831 exit 1

Failed to compile bundle: /var/folders/rx/90bsbdvx4vlfvzgxdcg_3mn80000gn/T/NotifeeCorevcigcdl6/NotifeeCore.arm64.xar
```
This occurs in notifee versions `0.13.1` to `0.14.0`. All versions before `0.13.1` work fine. Might be somewhat related to https://github.com/notifee/react-native-notifee/issues/162.

Any suggestions?

**Comment by bjjeong** [comment]
@mikehardy got it, thank you! 👍 it would be helpful to have this listed somewhere, as this was what I suspected but didn't find any documentation of that requirement on the repo or the documentation site.

**Comment by mikehardy** [comment]
If you can confirm success after updating Xcode to 12 - to make sure - I'll add it to the docs release notes and install

**Comment by bjjeong** [comment]
@mikehardy No issues after updating Xcode to 12.

**Comment by mikehardy** [comment]
Whew - okay, thanks for the report, I'll re-open this but re-focus it entirely for documentation update. Good luck on your project
