### ISSUE TITLE
isBatteryOptimizationEnabled initially always true on emulator

### ISSUE THREAD

**Issue by raphaelrupprecht** [notifee/react-native-notifee#175]
I observed that isBatteryOptimizationEnabled initially always true on emulator.
On my devices this matches with the vendors defaults, so the question is: has someone a Pixel phone on which isBatteryOptimizationEnabled initially returns false?

**Comment by helenaford** [comment]
I have a Pixel 2a that I can test with but I'm not sure if I understand the scenario. Does it return true, even though it's actually false on the device?

**Comment by raphaelrupprecht** [comment]
On the emulator the optimization default is false, but I get optimzed = true.
On my devices the default is true (chinese vendors) and I get optimized true (which is ok).
So I am asking myself if emulator is not good for testing, or if the method always returns true, even on Pixel device.

**Comment by helenaford** [comment]
Ah OK, will investigate and let you know.

**Comment by helenaford** [comment]
I had a look. I got the same results on the emulator as I did on the Pixel 2a, both returned true. 

`On the emulator the optimization default is false, but I get optimzed = true.`
Which emulator are you using?

I think for the `isBatteryOptimizationEnabled` method, you can rely on the emulator, and probably find that it's difficult to get a device (above API Level 23+) that doesn't have default as true.
