### ISSUE TITLE
Foreground notification in android event is not triggering when click on it

### ISSUE THREAD

**Issue by saurabh874** [notifee/react-native-notifee#176]
Hi,
I am using Notifee with react-native-firebase v6.
there is one issue when new notification is come up in foreground its perfectly showing but when i click on it its routing my screen. even i used pressAction in android.

```
notifee.displayNotification({
                        title: remoteNotification.notification.title,
                        body: remoteNotification.notification.body,
                        data: remoteNotification.data,
                        android: {
                            channelId,
                            pressAction: {
                                id: 'default',
                            },
                            smallIcon: 'ic_notification',
                            asForegroundService: true,
                            colorized: true,
                            // importance: AndroidImportance.HIGH,
                            sound: remoteNotification.notification.sound ? remoteNotification.notification.sound : 'newmessage.wav',
                        },
                    });

 // Subscribe to events
    useEffect(() => {
        const unsubscribe = notifee.onForegroundEvent(({ type, detail }) => {
            console.log('onForegroundEvent', type);
            const { data } = detail.notification;
            const campaignID = _.get(data, 'campaign_id', '');
            switch (type) {
                case EventType.DISMISSED:
                    console.log('User dismissed notification', detail.notification);
                    break;
                case EventType.PRESS:
                    if (campaignID && campaignID !== '' && campaignID !== 'null') {
                        handleCampaign(data);
                    } else {
                        handleContactDetail(data);
                    }
                    break;
                default:
                    break;
            }
        });
        return unsubscribe();
    }, []);
```

**Comment by Ehesp** [comment]
Have you tried removing the 

```
 pressAction: {
   id: 'default',
 },
```

item?

**Comment by saurabh874** [comment]
Yes @Ehesp 
const unsubscribe = messaging().onMessage(async (remoteNotification) => {
            console.log('remoteNotification', remoteNotification);
            if (!getCurrentConversationState(remoteNotification)) {
                if (androidPlatform) {
                    notifee.displayNotification({
                        title: remoteNotification.notification.title,
                        body: remoteNotification.notification.body,
                        data: remoteNotification.data,
                        android: {
                            channelId,
                            smallIcon: 'ic_notification',
                            asForegroundService: true,
                            colorized: true,
                            // importance: AndroidImportance.HIGH,
                            sound: remoteNotification.notification.sound ? remoteNotification.notification.sound : 'newmessage.wav',
                        },
                    });
                } else {
                    notifee.displayNotification({
                        title: remoteNotification.notification.title,
                        body: remoteNotification.notification.body,
                        data: remoteNotification.data,
                        ios: {
                            sound: remoteNotification.notification.sound ? remoteNotification.notification.sound : 'newmessage.wav',
                        },
                    });
                }
            }
        });

but again not working.

**Comment by helenaford** [comment]
Hi, just did a quick test and can see the `onPress` event coming through when I click a notification with a foreground service. Nothing screams out that could be causing the issue apart from one one thing, `remoteNotification.notification.title`. Can you confirm that Notifee is displaying the notification, and it's not being displayed by Firebase itself.
