### ISSUE TITLE
iOS: Ability to only cancel future (not currently displayed) trigger-notifications.

### ISSUE THREAD

**Issue by tdekoning** [notifee/react-native-notifee#177]
Not sure, but i think https://notifee.app/react-native/reference/canceltriggernotifications only cancels trigger notifications that have not been triggered yet (are in the future). 

It would be nice to see this feature available on iOS too.

**Comment by helenaford** [comment]
ah this is a bug in the docs. I'm currently working on them now, so will remove the `Android-only` label. The api works on iOS too.

**Comment by tdekoning** [comment]
Awesome!
