### ISSUE TITLE
largeIcon not working + small icon?

### ISSUE THREAD

**Issue by tomskopek** [notifee/react-native-notifee#18]
Hello,

I can't get the largeIcon to work with my image.
~I'm also wondering if functionality has been built yet to change the icon from a square to a custom one? Is this the smallIcon for which documentation is in progress?~ Edit: figured this out

Please see my setup and a screenshot below.

Here is my code:
I've set up a hook that gets called in the main App.js, to set up the push notifications.
(*note the strange conditional import, this is so that I can keep building our ios app - if there is a better way please let me know!)
I'm sending push notifications from the server using firebase-admin (nodejs).

`react_native/src/hooks/usePushNotifications.js`:
```javascript
import { useState, useEffect } from 'react';
import messaging from '@react-native-firebase/messaging';
let notifee;
if (Platform.OS === 'android') { // 👈 * never done this before, if there's a better way, please share!
  notifee = require('@notifee/react-native').default;
}

export default function usePushNotifications() {
  const [pushNotificationsReady, setPushNotificationsReady] = useState(false);

  useEffect(() => {
    if (Platform.OS === 'android') {
      setupPushNotificationHandlers().then(() => setPushNotificationsReady(true));
    } else {
      setPushNotificationsReady(true);
    }
  }, []);

  async function setupPushNotificationHandlers() {
    messaging().onMessage(onMessageReceived);
    messaging().setBackgroundMessageHandler(onMessageReceived);
  }

  async function onMessageReceived(message) {
    const channelId = await notifee.createChannel({
      id: 'default',
      name: 'Default Channel',
    });
    console.log('---@channelId --- usePushNotifications.js: onMessageReceived, L30');
    console.log(channelId);
    const notification = JSON.parse(message.data.notifee);
    // notification.android.largeIcon = require('../assets/images/img_name_196px.jpg'); // 👈 this throws an error: 'notification.android.largeIcon' expected a string value.
    // notification.android.largeIcon = 'https://i.pinimg.com/originals/42/81/53/428153d3084285c6292dd84e441ae97d.png' // 👈  this works
    notification.android.largeIcon = 'ic_launcher_custom'; // 👈 this only works sometimes, more info below**
    console.log('---@notification --- usePushNotifications.js: onMessageReceived, L36');
    console.log(notification);
    notifee.displayNotification(notification);
  }

  return {
    pushNotificationsReady,
  };
}
```

And this is my notifications object that is being logged right before
```javascript
notifee.displayNotification(notification)
```
```json
---@notification --- usePushNotifications.js: onMessageReceived, L36
{
  title: "Test",
  body: "You did it!",
  android: {
    color: "#c40018",
    channelId: "default",
    largeIcon: "ic_launcher_custom"
  },
  subtitle: "&#129395;"
}
```

![image](https://user-images.githubusercontent.com/4926143/76173742-61066400-6178-11ea-936f-491d47ab6446.png)

** I've tried a few mipmaps and it seems like they only work if the mipmap does _not_ have a .xml in the folder. If there is an .xml file in the folder of the mipmap I want to use, it will not work.

Thanks!

**Comment by tomskopek** [comment]
I figured out the smallIcon.

I needed to add one of these guys:

![image](https://user-images.githubusercontent.com/4926143/76177954-10006b00-618c-11ea-91d6-64c89b3a5e11.png)

![image](https://user-images.githubusercontent.com/4926143/76177918-f4956000-618b-11ea-9405-68c48c3952ec.png)

and then adding:
```javascript
notification.android.smallIcon = 'ic_notification';
```
did the trick.

By the way, what does `ic_` stand for?

Thanks!

**Comment by Ehesp** [comment]
Have you tired to add an image (for the large icon) the same way as the small icon? 

The large icon can be a local resource, local path or http URL. 

> By the way, what does ic_ stand for?

Just shorthand for "icon"

**Comment by Salakar** [comment]
@Ehesp can we add docs for adding in a small icon asset maybe?

**Comment by tskopek** [comment]
This thread slipped through the cracks for me.

> Have you tired to add an image (for the large icon) the same way as the small icon?
I didn't get around to this. I'll have a go this weekend

> can we add docs for adding in a small icon asset maybe?
I think this would be extremely useful!

**Comment by Ehesp** [comment]
> I think this would be extremely useful!

I'll get it sorted :)

**Comment by Salakar** [comment]
Please try the latest release for large icon, image requires should now be working correctly

**Comment by Salakar** [comment]
Small icon docs are now up also (thanks @helenaford): https://notifee.app/react-native/docs/android/appearance#small-icons

Going to go ahead and close this issue now, thanks.

**Comment by mars-lan** [comment]
> ** I've tried a few mipmaps and it seems like they only work if the mipmap does not have a .xml in the folder. If there is an .xml file in the folder of the mipmap I want to use, it will not work.

Also encountered this issue today. @Salakar could you please update [the doc](https://notifee.app/react-native/docs/android/appearance#large-icons) noting the XML limitation?

**Comment by mikehardy** [comment]
@mars-lan sure - https://github.com/notifee/documentation/pull/14
