### ISSUE TITLE
[Help Wanted]Question about the fee of the standard license 

### ISSUE THREAD

**Issue by hollyoops** [notifee/react-native-notifee#180]
Hello team, 

We are plan to buy the standard license of notifee. And we have a question about this license. The [document](https://notifee.app/) said "Lifetime Updates Included",  Does this mean the license only needs to be paid by once rather than pay by yearly.

(We sent emails and tweets to the team. but unfortunately, there is no response. so we raise an issue here)

**Comment by m-jachym** [comment]
Same issue.
we sent messages but no reply

**Comment by Ehesp** [comment]
> Does this mean the license only needs to be paid by once rather than pay by yearly.

Yes, you pay for a license once.

**Comment by mikehardy** [comment]
In addition, you get some sub-licenses (for example, for bundle ids / android packages that are .test, .dev etc) included so testing environment separation is possible

**Comment by hollyoops** [comment]
Thanks a bunch!
