### ISSUE TITLE
Android: Project with path ':notifee_react-native' could not be found in project ':app'.

### ISSUE THREAD

**Issue by DevArenaCN** [notifee/react-native-notifee#181]
Versions: 
React-Native: 0.63.3
Notifee: 0.14.0

Reproduce: I've tried cleaning out the node_module folder, run `npx react-native-clean-project` and reinstall afterwards, iOS doesn't seem to have this issue, but Android keep throwing me this error:
```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/u/demoapp/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 108

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':notifee_react-native' could not be found in project ':app'.

```

Anything else I should try? I also tried `react-native link @notifee/react-native` as well, same issue

**Comment by mikehardy** [comment]
I maintain a from-scratch demo that works https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh

The only case we've seen where it doesn't work is if you follow the OneSignal docs, so we have a special thing for them: https://github.com/notifee/documentation/commit/7249b1d497b7dac9765677642aae970c09cb93b7

If you can show how to reproduce an integration failure following the docs, we can troubleshoot

**Comment by DevArenaCN** [comment]
OK, not sure what went wrong, but create a RN project from scratch seems to solve it.

**Comment by mikehardy** [comment]
@DevArenaCN going to chalk this up to the standard "being a react-native developer is a lot harder than it seems..." category of issues then, that is, it's just hard to get right :-). Happy you're moving forward, good luck with your project
