### ISSUE TITLE
On Android: Notification Channel Creation on Release Builds is Broken

### ISSUE THREAD

**Issue by WaterCityFlame** [notifee/react-native-notifee#184]
### On Android: Notification Channel Creation on Release Builds is Broken

**Version**: Notifee 14.0
**Android Version:** 10.0
**Code Snippet:**
```javascript
  notifee.createChannel({
    id: "testChannelId",
    name: "This is a Test Channel :D",
    lights: false,
    vibration: true,
    importance: AndroidImportance.DEFAULT,
  })
```

**Expected Behaviour:**
If I go to the Android Settings App -> App Info -> my app -> Notifications, I should see "This is a Test Channel :D" beside a toggle. Notifications sent to the test channel should show up. 

**Actual Behaviour:**
This all works if I build the app in Debug mode. 

It does not work if I build the app in Release mode. 

I have been experiencing an issue in a different app where Timestamp Trigger notifications are not showing up on Android and I believe that is related to this issue. At the moment my reproduction doesn't actually test that though. EDIT: I added a "Send A Notification" button that schedules a notification for 15 seconds from Date.now(). On release, no notification. On debug, notification shows up. 

**Minimal Reproduction:**
https://github.com/WaterCityFlame/NotifeeChannelCreation

**Comment by mikehardy** [comment]
Fascinating - no idea how that could be a difference between debug and release, you aren't even minifying for release so it's not a D8/R8 issue https://github.com/WaterCityFlame/NotifeeChannelCreation/blob/ac1c70b294e5fcd89add3c1773bb552520893270/android/app/build.gradle#L99

:thinking:

**Comment by helenaford** [comment]
Hey, is there anything in your logs, if you search `createChannel`? The only difference I can think could be happening, is if the library can't find a valid license, and you might see something `Attempted to call method createChannel but your license is invalid.`.

**Comment by WaterCityFlame** [comment]
Ok, so this one is user error :D 

@mikehardy yea, this is minimally modified from the `npx react-native init` output, so it should be super simple. 

@helenaford That's a good idea, and about half right. On this app, I saw that warning, but thought to double-check on my work app where we have a license. There, I saw a different error about how Notifee expected the ID to be a string. I have no idea why it would worry about this in release but not in debug mode, but it does give me enough of a pointer in the right direction that I can probably fix it. 

You can probably close this but I'll leave that to you guys to decide

**Comment by helenaford** [comment]
Thanks,  will close this but if you still see an issue, feel free to re-open :)

**Comment by Hamidrezana** [comment]
@WaterCityFlame 
I have same issue, How did you resolve it?
