### ISSUE TITLE
iOS: RunPath not finding framework causing crash on launch

### ISSUE THREAD

**Issue by KevinDoom** [notifee/react-native-notifee#185]
Hello.

I recently installed Notifee. Seems to work fine on Android, but when attempting run on iOS, the app crashes on launch with this:

```
dyld: Library not loaded: @rpath/NotifeeCore.framework/NotifeeCore
  Referenced from: /private/var/containers/Bundle/Application/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/MyApp.app/MyApp
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

Seems as though the framework isn't being copied over the appropriate location. Perhaps an auto-linking issue? I tried running `react-native link @notifee/react-native` manually just in case—no dice.

I noticed if I add `$(SRCROOT)/../node_modules/@notifee/react-native/ios` to `RunPath Search Paths` in the target's Build Settings I can get it to run on an iOS Simulator. This makes me think the framework isn't making its way to `@executable_path/Frameworks` for some reason. ¯\_(ツ)_/¯ 

Any help would be appreciated! 

### Versions
notifee:  0.14.0
react-native: 0.62.2

**Comment by mikehardy** [comment]
Hi there! I have a script here I use to triage build issues, and I've run it recently it all seems to work: https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh

Can you reproduce it with a clean project like that?

**Comment by KevinDoom** [comment]
Thanks, @mikehardy. Trying a fresh install and will get progressively closer to out configuration until I see where it breaks. I'll report back!

**Comment by KevinDoom** [comment]
While I haven't tracked down the specific issue, it seems particular to our app configuration. I can't reproduce on a fresh project with the same react and react-native versions. I'll close. Thanks!

**Comment by mikehardy** [comment]
Sorry you're still having issues but at least we know it's *possible* it can work. Good luck picking out the offending chunk and moving forward
