### ISSUE TITLE
[Android]: Notifee not working on release mode android

### ISSUE THREAD

**Issue by meosieudang** [notifee/react-native-notifee#186]
Version: Notifee 15.0
Android Version: 10.0

Expected Behaviour: 
 - Show notifee on release mode

Actual Behaviour:
This all works if I build the app in Debug mode.

It does not work if I build the app in Release mode.

For the iOS, it working all Debug and Release mode

**Comment by meosieudang** [comment]
> Hi there @meosieudang !
> 
> 1. Do you have a license correctly configured? The output of `adb logcat` while running your app and doing a test notification in release mode would be instructive.
> 2. I have not updated my work project to 0.15 yet but on the version immediately prior (0.14.1 I believe) I just tested it and it is working for me. Is this something that used to work and has changed, or has it never worked for you?

hi @mikehardy, i dont have license. this lib need purchase to get license. It terrible for me, and now i'm use lib react-native-push-notification. it working for me and FREE

**Comment by Rishabh-spec** [comment]
I am using notifee and i have license for it but push notification not working in release mode

**Comment by mikehardy** [comment]
@Rishabh-spec there are no known issues with notifee working in release mode. I suggest you separate the concerns of "push notification" (i.e., some cloud message with JSON payload received by your app) and "notifee notification" (which is you calling a notifee API to display a visible notification on the device).

Notifee notifications work just fine in release mode if the license is configured correctly. Here is a quick way to construct a sample application, and you can change the package names and put your license in to test if you like https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh

**Comment by Rishabh-spec** [comment]
I have already done licence setup according to notifee documentation. Still
not receive push notification in release.

**Comment by mikehardy** [comment]
@Rishabh-spec it does not sound like you actually followed my suggestion and performed the test I suggested. I can't add anything to it, all of what I said in my previous comment is still valid.
