### ISSUE TITLE
Print positive license identification message on app startup

### ISSUE THREAD

**Issue by mikehardy** [notifee/react-native-notifee#187]
Is there a good way of validating that the right license has been bundled with the right app? 

It would be useful to have a debug mode or something that prints out the license key (or some kind of identifiable substring of it) that it has found for the current build.

I'm using the following configuration, in the hope that if all else fails it will default back to the production license - as those are the notifications that we definitely want to go through:

```
{
  "android": {
    "development": {
      "license": "[dev android license]"
    },
    "staging": {
      "license": "[staging android license]"
    },
    "license": "[production android license]"
  },
  "ios": {
    "development": {
      "license": "[dev ios license]",
    },
    "staging": {
      "license": "[staging ios license]",
    },
    "license": "[production ios license]"
  }
}
```

Where on iOS my scheme names are `staging`, `production`, `storybook`, and `development`, and on Android my productFlavors are named the same respectively.

_Originally posted by @cjpete in https://github.com/notifee/react-native-notifee/pull/67#issuecomment-717291200_

**Comment by helenaford** [comment]
Latest release (v0.15.2) logs a positive message with the last 10 characters of the license key, e.g.:

`Local verification succeeded for your application with package name com.app.dev and license key ending in SEnXjJQbY1`

Docs coming soon with more in-depth guide on how to use the logs and how to debug any validation issues.

**Comment by MystL** [comment]
@helenaford is there any logs for failed license validation? asking because I couldn't seem to see the logs for Positive Validation even-though i might have the correct config setup.

**Comment by mikehardy** [comment]
failed validation was always printed I think, positive log messages were added just so that all license cases (they worked, they didn't work...) were visible meaning ideally developers could scan the log at any time and know how things went either way so they could focus work on other things instead of wondering

That was the goal, sorry it's not working exactly right. `adb logcat` should be showing everything though? Or is this iOS?

**Comment by MystL** [comment]
@mikehardy ah sorry I should be more specific, i mean logs for iOS. I'm able to get the logs in Android, just not in iOS.

**Comment by mikehardy** [comment]
Ah, the positive logging for license validation was added for Android not for iOS. iOS will log failures I believe but that's it.

So for iOS you should focus on functionality. If you do a release build and you are able to display a local notification of any type, things are working 100%.

I have release streams (that's what I call them, on Android they are "flavors" and for iOS they are "targets", in my firebase backend they are separate "projects"), and in my non-production release streams I allow a little control panel screen to be available. In that control panel / development info screen I have a number of testing buttons and one of them just does a local notification popup to make sure things are working. On iOS it always works.

I go into some detail because I also have a button there that calls a firebase function to send an FCM back to the same user, which exercises the firebase message handler and triggers a notifee notification - a much more complex integration type test which is important to check and goes far beyond license validation and is important to check prior to promoting code to the production stream

**Comment by MystL** [comment]
I see, but by just directly making a build via xcode in local machine is not sufficient to justify the license works i guess?

**Comment by mikehardy** [comment]
If it works in debug it will work in release as well, I mean, test it but debug builds will also be sufficient to check. You should be able to deploy on iOS with confidence

**Comment by MystL** [comment]
so, just to confirm that for managing different licenses key in iOS i should define them using `"scheme" right? whereas Android is by "flavour" (sorry if this is not the correct thread to ask), something like this?
```
{
 "ios": {
    "dev_scheme":{
       "license": "value"
    },
   "prod_scheme": {
       "license": "value"
   }
  }
}
```

**Comment by mikehardy** [comment]
That should work, and though positive validation messages will not be printed in iOS I believe you'll find the functionality works fine

**Comment by MystL** [comment]
thanks, i'll give it a go
