### ISSUE TITLE
Custom Component help

### ISSUE THREAD

**Issue by raphaelrupprecht** [notifee/react-native-notifee#189]
I am trying the custom component feature to configure a mainComponent for pressActions [like described here](https://notifee.app/react-native/docs/android/interaction#advanced-custom-component).

In the index.js I register two components:
````
AppRegistry.registerComponent('tek_prevent', () => App123);
AppRegistry.registerComponent('notification-screen', () => NotificationScreen);
````

My MainActivity.java looks like:
````
package de.tek_prevent;

import com.facebook.react.ReactActivity;

// Import the NotifeeApiModule
import io.invertase.notifee.NotifeeApiModule;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return NotifeeApiModule.getMainComponent("tek_prevent");
  }
}
````
The notification is triggered by:
````
await notifee.createTriggerNotification(
      {
        id: this.lastId+'',
        title: title,
        body: msg,
        android: {
          channelId: this.channelId,
          style: { type: AndroidStyle.BIGTEXT, text: msg },
          smallIcon: 'ic_launcher',
          largeIcon: 'ic_launcher',
          pressAction: {    
            id: 'default',
            launchActivity: 'default',                                    
            mainComponent: 'notification-screen',
          }
        }
      },
      trigger,
    );
````
Triggering a notification now opens the "tek_prevent" / App123 component. I would have expected it to open the "notification-screen" / NotificationScreen component. Any idea?

**Comment by mikehardy** [comment]
The only thing I can think of is the launchActivity is not present in the docs, but I vaguely recall from another issue that it may be necessary-but-not-documented-as-necessary so I give that low-probability of having an effect.

It appears everything is correct otherwise per docs, so I'm not sure. Can this be reproduced in a single App.js dropped in to the result of a skeleton app creation like https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh ?

**Comment by raphaelrupprecht** [comment]
Thanks for the reply @mikehardy ! 
I got the launchActivity: "default" already set but I added `launchActivityFlags: [AndroidLaunchActivityFlag.SINGLE_TOP]` and changed the `android:launchMode="singleTop"` in the AndroidManifest.xml.
This doesn't help.

With your demo app it doesnt work either. But pressing the notification leads to a warning: "No task registered for the key app.notifee.notification-event". 

To specify what my goal is: when my app starts the user lands on a Dashboard component. Users can then navigate to a NotificationScreen component and activate notifications. When a notification appears and the user presses it, the NotificationScreen should open, not the Dashboard component. In my tests always the last opened component is displayed again.

**Comment by mikehardy** [comment]
Thank you for trying to reproduce based on the demo, I would love to see the App.js you dropped in the demo to check it, just to make sure we have the same basis for reproduction and (in the future) confirmation of a fix that we share.

I feel like I was understanding your goal + problem before, I think you described it well with the code snippets (and the component names), I'm sorry it's not working for you as expected!

**Comment by raphaelrupprecht** [comment]
The only thing I changed in the NotifeeApp.js was the launchActivityFlags and mainComponent.
````
// Display a notification
    await notifee.displayNotification({
      title: 'Notification Title',
      body: 'Main body content of the notification',
      android: {
        channelId,
        pressAction: {
          id: 'default',
          launchActivity: 'default',
          launchActivityFlags: [AndroidLaunchActivityFlag.SINGLE_TOP],
          mainComponent: 'app2',
        },
      },
    });
````
I am starting to wonder if it is possible to call AppRegistry.registerComponent() twice, as I do in the index.js:
````
AppRegistry.registerComponent('notifeedemo', () => App);
AppRegistry.registerComponent('app2', () => App2);
````
If I change the calling order it leads to an error that 'notifeedemo' has not been registered.

**Comment by helenaford** [comment]
Hi, I had a look. Did you override `getMainComponentName() `  inside `/android/app/src/main/java/.../MainActivity.java`. It should work after doing that. Maybe we could adjust the docs to make it clearer.

**Comment by raphaelrupprecht** [comment]
Hi Helena. My App2 component is just the normal App.js that comes with the react-native init script. 
So for you it worked? You trigger a notification, then close the app and tap on the notification and the "app2" component opens?

**Comment by helenaford** [comment]
OK, I tried with both displayNotification and createTriggerNotification, both worked. But think I found what it could be, can you try it again but comment out  `launchActivityFlags: [AndroidLaunchActivityFlag.SINGLE_TOP]`

**Comment by helenaford** [comment]
Code snippets from my app:
`Notification`:

   ```
 const triggerNotificationWithCustomComponent = async () => {
        console.log('trigger');
        const date = new Date(Date.now());
        date.setSeconds(date.getSeconds() + 3);

        await notifee.createTriggerNotification({
            title: 'New trigger notification',
            android: {
                channelId: 'default',
                pressAction: {
                    id: 'default',
                    launchActivity: 'default',
                    // launchActivityFlags: [AndroidLaunchActivityFlag.SINGLE_TOP],
                    mainComponent: 'custom-component',
                },
            },
        }, { type: 0, timestamp: date.getTime() });
    }
```

`index.js`
```
/**
 * @format
 */
import React from "react";
import { AppRegistry } from "react-native";
import { StyleSheet, View, Text } from "react-native";
import App from "./App";
import { name as appName } from "./app.json";

import messaging from "@react-native-firebase/messaging";
import notifee from "@notifee/react-native";

messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});

AppRegistry.registerComponent(appName, () => App);

function CustomComponent() {
  return (
    <View>
      <Text>A custom trigger component</Text>
    </View>
  );
}

AppRegistry.registerComponent('custom-component', () => CustomComponent);
```
`MainActivity.java`
```
import io.invertase.notifee.NotifeeApiModule;
public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
   //   return "MyApp";
    return NotifeeApiModule.getMainComponent("MyApp"); 
  }
}
```

**Comment by raphaelrupprecht** [comment]
Thanks for your your messages Helena. Even with almost the exact code I cannot make this work. I left out the messaging().setBackgroundMessageHandler stuff, because I am not using firebase push.

**Comment by helenaford** [comment]
mmm interesting, as I can't reproduce this locally, I'm not sure what to suggest. Could it be another library interfering like a navigation library? Is it possible to produce a bare bones app with this issue? 

For your wanted outcome, have you considered listening to the notification [press](https://notifee.app/react-native/reference/eventtype#press) event, and navigating the user that way?

**Comment by mikehardy** [comment]
Just on the off chance it's useful, I use this to produce bare-bones setups for reproduction as needed, you might be able to use it as the start of a bare-bones reproduction and post it https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh
