### ISSUE TITLE
notification badge support 

### ISSUE THREAD

**Issue by monaye** [notifee/react-native-notifee#19]
Hello, I just purchased the package then realized the package doesn't support notification badge. 
So far I know there few but it seems like none of them are up to date and wondering any plan to add such functionality. 
Even without the badge func. this is a great package and really loves it and also huge fun of the idea of charging the package. Hope the team the best.

**Comment by Ehesp** [comment]
Hey - would you be able to explain what you mean? We're open to implementing features but not sure exactly which here :)

**Comment by mikehardy** [comment]
I'd bet a $1 @monaye means ShortcutBadger-like functionality

**Comment by Ehesp** [comment]
Ahh, if that's the case we removed it because the amount of devices which support custom badges is fairly low now. Android has it's own badge system in place, which we support options for.

**Comment by monaye** [comment]
@mikehardy you got it!! 
@Ehesp thank you for the explanation. It makes sense. I didn't know about the Android's badge limitation.

**Comment by Ehesp** [comment]
For reference https://notifee.app/react-native/docs/android/appearance#badges

**Comment by umang-simform** [comment]
Hello, Is there any method to get current badge counts?

**Comment by Salakar** [comment]
#32 was just merged - adds support for iOS - we'll have a release out within the next day.

Still not sure if this is viable for Android as it's a non-standard API and requires a third party library like ShortcutBadger - do people actually need/use this for Android?

**Comment by metervara** [comment]
> Still not sure if this is viable for Android as it's a non-standard API and requires a third party library like ShortcutBadger - do people actually need/use this for Android?

Android 8.0 added notifications badges including setting the number (count): https://developer.android.com/training/notify-user/badges#set_custom_notification_count

It is not displayed on the badge it seems, but rather in the long press menu, but I think it would be relevant to map that functionality in notifee

**Comment by Ehesp** [comment]
@metervara you can do that already: https://notifee.app/react-native/reference/notificationandroid#badgecount

**Comment by mikehardy** [comment]
Very interesting - and one would expect (?) that all the custom launchers in the world that were semi-supported with ShortcutBadger might actually adopt that. Even in my skewed-older-on-API-distribution app, Android 8+ is predominant now, so I have renewed hope for convergence in "notification counts / badging" in the Android world. On iOS it's a big deal :)

**Comment by metervara** [comment]
@Ehesp thanks, I totally missed that. I searched for setBadgeCount and the results led me to this: https://notifee.app/react-native/reference/setbadgecount#notifee. Saw the **ios only** badge so I assumed it was unavailable on Android. Sorry about that
