### ISSUE TITLE
Notifee on IoS does not have a good hook for showing user notifications.

### ISSUE THREAD

**Issue by mahpat16** [notifee/react-native-notifee#192]
Working with notifee to build notifications on Android and IOS. Things work very well with Android. Looks like data only messages are supported as a first class entity on Android, which is awesome. On the other hand things on IOS are not working as expected. Here are my findings.

1. Based on Apples documentation about background update notifications i.e. 
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW8

It is fairly clear that background updated notifications are not meant as a replacement for 'Notifications' that are meant to involve user interactions. There is also a limit on the number of background messages that you can send per hour which is documented in the above link.  

My testing has also shown that, on IOS, an 'alert' i.e. one with the following headers is 100% reliable, I have never seen a FCM message sent with these apns headers being lost.

apns{
   headers: {
          'apns-push-type': 'alert',
          'apns-priority': '10',
          'apns-topic': 'blah-placeholder',
}
}

The problem with the above is that, there is no way for notifee to hook into this path, the above results in the system(ios) showing an alert to the user without giving notifee (i.e. me the developer in this case)  a hook to show local notification.

On the other hand if we send a FCM message with the following headers as required (per my understanding) by notifee. Then the delivery of this message is at best a crapshoot. I simply dont get these messages delivered with any level of consistency. 
apns{
   headers: {
          'apns-push-type': 'background',
          'apns-priority': '5',
          'apns-topic': 'blah-placeholder',
}
}

For me as a developer the unreliability of these types of messages whether it is because of Apple's algorithm or some other reason means I simply cant use this way as a way to hook up FCM messages to notifee on IoS. Plus the restrictions on the number of these that you can send per hour means that they suffer from certain builtin restrictions which dont apply to apns based alerts.

I dont claim to be an expert in IoS notifications or notifee. My reason for filing this issue is.
1. Is there something fundamentally wrong with my understanding. If so, please explain.
2. If not, what is the right way to solve this problem. The problem being, 'How can I reliably use notifee to show notifications to users on IOS'.  

Again to summarize, clearly background messages are simply too unreliable plus has restrictions on the number that I could send per hour. making them practically useless for showing notifications to users. apns based alerts is reliable and does not suffer from the rate limiting restrictions. In this scenario how can anyone use notifee on IOS?

**Comment by helenaford** [comment]
Hi, thanks for the question. I believe we have a solution in the roadmap for this which allows you to use remote notifications via FCM and utilise notifee features. 

It would require a custom key to be added in the apns payload, that would be an object, which would be picked up via your app's Notification Service Extension. We'd provide a helper class to parse it, adjusting the notification content before it's displayed.

**Comment by mahpat16** [comment]
Thanks for the info. Do you have a rough ETA for the roadmap item?

**Comment by helenaford** [comment]
A rough ETA will be in the next few releases. Hard to give exact dates, but what I can say is half of the work item has been done. Will keep you posted! We're working hard behind the scenes to get a few big features out. :-)

**Comment by helenaford** [comment]
@mahpat16 It's now possible to use remote notifications with notifee (https://notifee.app/react-native/docs/release-notes#120). Please see the docs for more info (https://notifee.app/react-native/docs/ios/remote-notification-support).
