### ISSUE TITLE
iOS notification not being displayed when app is quit, 

### ISSUE THREAD

**Issue by ANIBIT14** [notifee/react-native-notifee#193]
Hi, in iOS app when app is quit the notification is not being displayed but its data is getting inside onMessage function, for displaying we are using notiffe displayNotification. It works fine on android, hope someone can explain what issue is causing this.

**Comment by mikehardy** [comment]
@ANIBIT14 Hi there! Can you tell me the exact steps, starting with your app being in the foreground, that result in your app being in "quit" state? Every action you take with the phone until the point you send the message.

Can you tell you also provide your package.json and an App.js that we could drop in to a clean reproduction app to try to reproduce this?

My app does similar things (receive cloud messages using react-native-firebase, display visible notifications with Notifee), and it works fine for me, so it should work and I imagine this is a project-specific problem, but we won't know until we can work off the same reproduction and versions

**Comment by ANIBIT14** [comment]
@mikehardy with quit state I mean app is closed, the message are bing generated from backend on specific event's like when user do a transaction, from his credit card, we are fintech company and app is only way of communication for users.

**Comment by mikehardy** [comment]
@ANIBIT14 I was very specific in my request, and I don't feel I have the information I need. Please re-read my request and provide the details exactly, thank you
