### ISSUE TITLE
iOS critical alert permission not asked

### ISSUE THREAD

**Issue by varungupta85** [notifee/react-native-notifee#198]
Is it required to have the critical alert entitlement accepted by Apple before asking for the `criticalAlert` permission during development also?

I am using the following code to ask for `criticalAlert` permission:

```
notifee
          .requestPermission({
            alert: true,
            criticalAlert: true,
            badge: true,
            sound: true
          })
          .then(reqPermisssions => {
            console.tron.log('requestPermissions', reqPermisssions)
          })
```

Below is the response:

```
'requestPermissions', { inAppNotificationSettings: 0,
  badge: 1,
  lockScreen: 1,
  announcement: -1,
  showPreviews: 1,
  criticalAlert: -1,
  sound: 1,
  alert: 1,
  authorizationStatus: 1,
  notificationCenter: 1,
  carPlay: -1 }
```

I don't see the extra dialog either that asks the user that this app will show them critical alerts and user allows or rejects.

 I have added the following entitlement to the entitlements file based on searching on Google

```
	<key>com.apple.developer.usernotifications.critical-alerts</key>
	<string>1</string>
```

**Comment by mikehardy** [comment]
My understanding of this is that you only get access to this type of notification if Apple grants it, with no possibility for inclusion without acceptance https://developer.apple.com/forums/thread/106042?answerId=337153022#337153022 - the comments from other developers on that issue are interesting as they show actual developer experience

**Comment by varungupta85** [comment]
Okay, thanks Mike. The link you shared from Apple Developer Forum was helpful.
