### ISSUE TITLE
Android: customise largeIcon style (border radius)

### ISSUE THREAD

**Issue by rgommezz** [notifee/react-native-notifee#199]
For a chat application like, it'd be great if we could customise the border radius for the sender remote image, since they render square. Is it possible to provide a border radius in the configuration so that we can make the thumbnail rounded?

![image](https://user-images.githubusercontent.com/4982414/99391548-3b6a5680-28d2-11eb-9af9-477e102979d9.png)

Btw great works guys, I am happy user of the package! 🚀

**Comment by kperreau** [comment]
Yes, I would really like to have this option too !

**Comment by 8BallBomBom** [comment]
Useful stuff over [here](https://stackoverflow.com/questions/28280615/make-notification-large-icon-round).
Would be nice to have that kinda functionality integrated though.

**Comment by helenaford** [comment]
Mmm interesting. This could be a cool enhancement, something we can see is feasible.

**Comment by hibinoA** [comment]
This is exactly what I want! It is enough great to be able to clip into circle for me.

**Comment by helenaford** [comment]
I've pushed up a draft p/r for this enhancement (#232), let me know what you think of the API 😄 It's a new boolean property on `NotificaitonAndroid` named 'circularLargeIcon'.

**Comment by helenaford** [comment]
Release v1.1.0 includes the feature enhancement 👍  If you set `circularLargeIcon` to `true` it will display any shape image as a circular image:
```
  await notifee.displayNotification({
      title: "Notification Title",
      body: "Main body content of the notification",
      android: {
        channelId: 'default',
        largeIcon: 'https://cdn.stacktiger.co/testing/test-image-square.jpg',
        circularLargeIcon: true,
      },
    });
```

<img width="385" alt="Screenshot 2021-02-01 at 01 21 18" src="https://user-images.githubusercontent.com/14185925/106481881-cbb54200-64a4-11eb-8d14-9df541eccabb.png">

Let us know what you think 😄
