### ISSUE TITLE
Push Notification sent through firebase do not trigger foreground or background events.

### ISSUE THREAD

**Issue by ShyamPanchal** [notifee/react-native-notifee#20]
Using @react-native-firebase/app (6.3.4) and @react-native-firebase/messaging (6.3.4) for data messages yet notification and data messages both trigger the messaging onMessage function and notifee background or foreground events do not get triggered.

<details>
  <summary>init Background code</summary>
<pre><code>
const initBackground = async () => {
	notifee.onBackgroundEvent(async ({type, detail}) => {
		const {notification, pressAction} = detail;

		switch (type) {
			case EventType.PRESS:
				console.log("Notification Pressed when app in background", notification);
				await notifee.cancelNotification(notification.id);
				break;

			case EventType.ACTION_PRESS:
				console.log("User Pressed Action on Notification", detail);
				break;

			case EventType.DELIVERED:
				console.log("Notification Delivered", notification);
				break;

			case EventType.DISMISSED:
				console.log("User Dismissed the Notification", notification);
				break;

			default:
				console.log("Not sure what to do with this info", {type, detail});
				break;
		}
	})
};
</code></pre>
</details>

<details>
  <summary>init Foreground code</summary>
<pre><code>
function initForeground() {
	useEffect(() => {
		return notifee.onForegroundEvent(({type, detail}) => {
			switch (type) {
				case EventType.DISMISSED:
					console.log('User dismissed notification', detail.notification);
					break;
				case EventType.PRESS:
					console.log('User pressed notification', detail.notification);
					break;
				case EventType.DELIVERED:
					console.log("User Notification Delivered: ", detail);
					break;
			}
		});
	}, []);
}
</code></pre>
</details>

These do get called if a notification was created and displayed using notifee but not for Push Notification.

**Comment by Ehesp** [comment]
Hey @ShyamPanchal - currently Notifee doesn't handle any form of remote notifications, all events are handled from Notifee actions.

This is something we're thinking of handling.

**Comment by ShyamPanchal** [comment]
@Ehesp , thank you, will look out for that feature

**Comment by Ehesp** [comment]
Hey @ShyamPanchal 

After digging into this, the any messages sent from FCM with a notification payload are automatically displayed on the device with the `messaging` module. 

We've added support for Android (6.4.0-rc0) (iOS coming) which enables handling notifications via FCM. Notifee will be standalone for local notifications still.

**Comment by Salakar** [comment]
Given the recent RNFB Messaging release I'm going to go ahead and close this issue - the latest release of RNFB messaging & Notifee are designed so that that play well together, you just need to keep in mind Notifee = Local, RNFB Messaging = Remote.
