### ISSUE TITLE
Android local notification is not working

### ISSUE THREAD

**Issue by freedomzzzii** [notifee/react-native-notifee#201]
I use react-native-firebase to trigger event (onMessage) and use react-notifee to show local notification but that's not working on android release(apk)(ios local and testfight is work, android on local is work). Anyone can help me?

my code
`
import messaging from '@react-native-firebase/messaging';
import notifee, { AndroidImportance } from '@notifee/react-native';

messaging().onMessage(remoteMessage => {
    this.handleNotifee(remoteMessage);
});

handleNotifee = async remoteMessage => {
    try {
      if (!remoteMessage || !remoteMessage.notification) {
        return null;
      }

      const channelId = await notifee.createChannel({
        'id': 'important',
        'name': 'Important Notifications',
        'importance': AndroidImportance.HIGH,
        'asForegroundService': true,
      });

      await notifee.displayNotification({
        'title': remoteMessage.notification.title ? remoteMessage.notification.title : '',
        'body': remoteMessage.notification.body ? remoteMessage.notification.body : '',
        'android': {
          channelId,
        },
      });

      return null;
    } catch (error) {
      return null;
    }
  }
`

**Comment by helenaford** [comment]
Hi, I can't see anything really wrong here. Apart from you have `asForegroundService: true` for the channel but not for the notification. Not sure if that would stop it. But, there should be an error message. Was there anything in the `catch (error) {}`?

**Comment by mikehardy** [comment]
Following `adb logcat` while the device is plugged in is sometimes instructive as well

**Comment by freedomzzzii** [comment]
> Hi, I can't see anything really wrong here. Apart from you have `asForegroundService: true` for the channel but not for the notification. Not sure if that would stop it. But, there should be an error message. Was there anything in the `catch (error) {}`?
> 
> It could be a license issue if it's only broken in release but the error message should show that.

It does not show any error on catch but event onMessage is trigger.

**Comment by freedomzzzii** [comment]
I try sample trigger notifee on this code, It's work on local(react-native run-android), on release (build apk) is not work. I don't know what's wrong.

more detail:
"@notifee/react-native": "^0.15.1",
"@react-native-firebase/app": "^9.0.0",
"@react-native-firebase/messaging": "^8.0.1",
"react": "16.13.1",
"react-native": "0.63.3",

`
<Button title="Display Notification" onPress={async () => {
              const channelId = await notifee.createChannel({
                id: 'default',
                name: 'Default Channel',
                importance: AndroidImportance.HIGH,
              });

              await notifee.displayNotification({
                title: '08:00am Alarm',
                body: 'The alarm you set for 08:00am requires attention!',
                'android': {
                  channelId,
                },
              });
            }} />
`

**Comment by mikehardy** [comment]
Anything from this?

> Following adb logcat while the device is plugged in is sometimes instructive as well

**Comment by SNWStaff** [comment]
Hello !

I have the actual same problem for testing in release mode, displayNotification seems to not be called. After some tries to debug this, thinking about a config error, I found this thread. There is the exact same problem, and nothing in my code seems to be wrong like posted here.
I followed your advice Mike, and displayed adb logs. There is the trick :
12-05 11:07:52.162 19810 20070 W NOTIFEE : (License): Attempted to call method displayNotification but your license is invalid.

I don't know if it's normal or not, but there is the reason why notification are not displayed in release mode.
I hope it helps !!

Sincerely
SNW Staff

**Comment by mikehardy** [comment]
That was my guess but we haven't heard back from the original poster. We can reopen if we do and it's not a license issue

**Comment by baronhsiao** [comment]
same issue

**Comment by mikehardy** [comment]
Please open a new issue with version details (package.json is best) and results from watching adb logcat for the app. Its usually license issue or power management, things that leaves logcat messages
