### ISSUE TITLE
[Android] Build on Github Actions it's Failing

### ISSUE THREAD

**Issue by sperezm97** [notifee/react-native-notifee#202]
When i try to get a new build with CI/CD on Github Actions on Android, it gave me this error: 

>Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous  versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :notifee_react-native project caused this error<root>/node_modules/@notifee/react-native/android/libs/notifee_core_release.aar

Would you know it's for your side or my side?

**Comment by mikehardy** [comment]
I think it may be this? https://github.com/notifee/react-native-notifee/issues/151#issuecomment-696910951

**Comment by sperezm97** [comment]
yes, it is. i would check, thanks.

**Comment by sperezm97** [comment]
It works, thanks!

**Comment by mikehardy** [comment]
Happy to hear it! Good luck with your project
