### ISSUE TITLE
notifee.getInitialNotification not firing

### ISSUE THREAD

**Issue by kjr-lh** [notifee/react-native-notifee#204]
I've got notifee set up in my project, I can schedule notifications and when I click on them the app opens and handles the event correctly (through `notifee.onForegroundEvent`)

I'm trying to test this using detox [mocking notifications](https://github.com/wix/Detox/blob/master/docs/APIRef.MockingUserNotifications.md) but I can't get notifee to see the mocked notification at all. 

I've had a quick test with `react-native-notifications` to test whether detox is setting up the event correctly, and it's `getInitialNotification` method handles the test notification correctly.

I know that `react-native-notifications` and `detox` are written by the same people, so you'd expect them to work together, but I'm not sure why notifee isn't handling the test notifications correctly

**Comment by mikehardy** [comment]
Hey there! Just a question, it is not 100% clear to me if getInitialNotification works for you on real devices, and this is limited to a detox mocking problem, or if this is a full getInitialNotification does-not-work-anywhere problem

Thinking to the next step, if it is detox-only it would help us a lot to have a test rig with a simple App.js to reproduce it. I usually reproduce things with this script: https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh - if there were any modifications you could make to it that then reproduced it that would help (maybe easy to just fork/clone that one and show me a branch?)
