### ISSUE TITLE
Firebase cloud messaging console doesn't pick up iOS users

### ISSUE THREAD

**Issue by cjpete** [notifee/react-native-notifee#207]
I'm not sure if this is a bug with Notifee, but I think you guys are best-placed to advise what may be going on here. It might be useful to extend the documentation in order to work around this, if indeed it is something that can be resolved. I don't see anything obvious in either the Notifee or the React-Native-Firebase docs.

### Issue

Targeting iOS app only picks up 1 user (real number closer to 2000):

![image](https://user-images.githubusercontent.com/13134961/101166342-0bd87f80-3630-11eb-8614-3b30efbd7f6f.png)

Targeting Android app the number looks accurate compared to our internal analytics:

![image](https://user-images.githubusercontent.com/13134961/101166421-2ca0d500-3630-11eb-9e52-d8b22d6dc560.png)

When sending a push to iOS, it did indeed go to many devices, not just 1.

### Versions

```
    "@notifee/react-native": "0.14.0",
    "@react-native-firebase/app": "10.0.0",
    "@react-native-firebase/dynamic-links": "10.0.0",
    "@react-native-firebase/messaging": "10.0.0",
    "@react-native-firebase/perf": "10.0.0",
    "react-native": "0.63.3",
```

### Implementation

We register the device for notifications at runtime:

```
  if (!messaging().isDeviceRegisteredForRemoteMessages) {
    await messaging().registerDeviceForRemoteMessages()
  }
```

And retrieve the device's FCM token on app foreground:

```
export const registerTokenListener = (listener: (token: string) => void): () => void => {
  messaging()
    .getToken()
    .then(async (token) => {
      if (token) {
        listener(token)
      }
    })

  const unsubscribe = messaging().onTokenRefresh(async (token) => {
    if (token) {
      listener(token)
    }
  })

  return unsubscribe
}
```

`AppDelegate` also has a call to register the device for remote notifications, in order to support Intercom push notification integration:

```
// I'm not sure why this is required - intercom doesn't work without this
// even though the firebase code does call `registerForRemoteNotifications`
- (void)applicationDidBecomeActive:(UIApplication *)application {
  [application registerForRemoteNotifications];
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [Intercom setDeviceToken:deviceToken];
  NSLog(@"***** INTERCOM TOKEN SET : %@", deviceToken);
}
```

**Comment by mikehardy** [comment]
Maybe not a useful response, I'll think more on it and add anything else I can think of - but I have also had disappointing results from the dashboard prediction of iOS targeting. My best advice is to check the official youtube channel for firebase, specifically around device membership in groups and how that works. From what I understand when you create target groups the devices pick those criteria up as *very* async changes (like, maybe not even once a day, sort of like remote config) and the device decides whether it meets the criteria, then adds itself to the group async (slow again).

I tend to maintain info about the things that interest me for pushes in firestore then, along with device tokens, and create my own token set to target manually, which is not ideal and arguably a mis-use vs target groups and UI driven campaigns, so I can't recommend it, but it's my experience.
