### ISSUE TITLE
Allow more granular control over repetition period of local timestamp notifications

### ISSUE THREAD

**Issue by eqlion** [notifee/react-native-notifee#211]
Let me describe my usecase: 30 minutes prior to the start of some event I need to send a push, for which I use timestamp notification. After that I need to send notification at the moment when the event starts and every 30 minutes until it's end. For the second notification I use interval notification with repetition period of 30 minutes. However currently it's not possible to schedule an interval notification, thus, I launch it the moment the timestamp notification registers. However, it launches the interval notification immediately, and even though i try to cancel it on arrival, it still sometimes manages to slip through. 
The only two solutions I see right now (and I know that it's impossible, as the functions don't exist yet) are either to allow us to set the repetition interval for the timestamp notification freely (i.e. not to restrict to the hourly, daily, weekly and monthly notifications only and allow the developers to set the period themselves), or to let us schedule the first appearance of the interval notification (i.e. when it should fire first). 
Anyway, I'd really appreciate any help in achieving my goal with the present functions and their limitations, as perhaps I miss some obvious solution. Thank you in advance!

**Comment by helenaford** [comment]
This is a duplication of #190.
