### ISSUE TITLE
Can't override sound settings for critical alerts on Android

### ISSUE THREAD

**Issue by michorvath** [notifee/react-native-notifee#212]
I have successfully enable critical alerts on iOS which make sound regardless of a users sound settings using Notifee and Firebase, however, I cannot seem to find anything in the docs for Firebase or Notifee to do the same for Android. Once you set your phone to vibrate only, silent, or dnd, I can't seem to make notifications vibrate and make sound. I know this is possible on Android but have only found a brief mention of it within Google's Android docs.

Am I missing something obvious? Any help would be greatly appreciated!

**Comment by helenaford** [comment]
I think this is what you are looking for [bypassDnd](https://notifee.app/react-native/reference/androidchannel#bypassdnd), setting the channel to be able to by pass do not disturb mode.

**Comment by helenaford** [comment]
There's an open git issue around setting `bypassDnd` (#206). Let me know if this answers your question, and I'll close this issue in favour of the other one.

**Comment by michorvath** [comment]
The bypassDnd flag just seems to toggle the dnd override setting on Android, if it is working properly. I was more looking for a way to make sound and vibrate even if the phone is on silent.

I already implemented a work around with the AudioManager's alarm channel with ReactNative's vibration and just removed Notifee's vibrate and sound properties. Thank you though for the help!

**Comment by helenaford** [comment]
No problem. There maybe something we could do but Android really doesn't make it as easy as iOS. Glad you were able to find a solution that works.

**Comment by daviddean99** [comment]
Hi @helenaford and @mikehardy,

I see the OP managed to work around this issue by using the AudioManager's alarm channel and disabling Notifee's support.

I have a similar requirement to the OP (i.e. to trigger sound and vibration even when device is in "Do Not Disturb" mode), having obtained the appropriate user permission first.

Do you have any plans to implement this "alarm channel" functionality within Notifee so avoid me having to implement a side solution like the OP did?

Thanks.
