### ISSUE TITLE
[Question] Is it possible to use iOS Attachments inside TriggerNotification ?

### ISSUE THREAD

**Issue by VivienTournie** [notifee/react-native-notifee#213]
Hello,

Is it possible to use iOS Attachments inside a trigger notification ? (to play an mp3 file for example)

From what I understand from the documentation it seems usable only for a "simple notification", am I right ?

Thanks

**Comment by helenaford** [comment]
Hi, you should be able to do attachments with trigger notifications. [Here's](https://notifee.app/react-native/reference/createtriggernotification) the reference docs for `createTrigger` method, it accepts a `Notification` so can handle any property that has. Hope that helps. Please let us know if there's anything we can change in the docs to make it better.
