### ISSUE TITLE
Data object is not initialized inside Event type

### ISSUE THREAD

**Issue by momirkostic** [notifee/react-native-notifee#219]
Hi,

I am currently using **notifee.onForegroundEvent** and **notifee.onBackgroundEvent** handlers which receive Event type parameter.  Event  type contains **notification** object and inside that object there is **data** object. Even though I send that object across FCM, it is not initialized inside Event object, so I get something like this: 

```json
detail: {
   "pressAction":{
      "id":"default"
   },
   "notification":{
      "body":"Body",
      "id":"gr5DAQFkX2TSHReseDFf",
      "data":{},
      "title":"Title",
      "ios":{
         "foregroundPresentationOptions":{
            "sound":true,
            "badge":true,
            "alert":true
         },
         "categoryId":"notification"
      },
      "subtitle":""
   }
}
```

Only the body and title are set.. Do you have any clue why this is like that?

**Comment by mikehardy** [comment]
Hi there, FCM and Notifee may be connected but are fundamentally separate.
For the purposes of reproduction, can create a minimal App.js that we can drop in an application created by this script https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh so we can see exactly what you're seeing?

When I use this actual functioning code from my work project for instance, it works just fine:

```typescript
      case 'ConnectionRequest':
        try {
          await notifee.displayNotification({
            title: 'Test ConnectionRequest notification',
            body: `sender kullkiId was ${message.data.sender}`,
            android: {
              channelId: BackgroundTaskService.CONNECTION_REQUEST_NOTIFICATION_CHANNEL_ID,
              smallIcon: 'drawable/minilogo_bw',
              pressAction: {
                id: 'default',
                launchActivity: 'default',
                launchActivityFlags: [AndroidLaunchActivityFlag.SINGLE_TOP],
              },
            },
            data: {
              fcmType: 'ConnectionRequest',
              senderId: message.data.sender,
            },
          });
        } catch (e) {
          console.log('cloudMessageHandler could not post notification?', e);
        }

```

**Comment by momirkostic** [comment]
Hi Mike, thanks for your reply.

I have something like this in my App.js file: 

```
React.useEffect(() => {
    return notifee.onForegroundEvent(({ type, detail }) => {
      if(type === EventType.DELIVERED) {
        // TO DO
      }
      else if (type === EventType.PRESS) {
        console.log("detail: " + JSON.stringify(detail));

      } else if (type === EventType.ACTION_PRESS) {
        // TO DO
      }
    });
  }, []);
```

I created simple node app which sends notifications.Here is the code: 

```
const admin = require("firebase-admin");

admin.initializeApp({
  credential: admin.credential.cert(require("./path/to/json/file.json")),
});

admin.messaging().send({
  token: "firebase_token",
  data: {
    hello: "world",
  },
  notification: {
    body: "Body",
    title: "Title",
  },
  // Set Android priority to "high"
  android: {
    priority: "high",
  },
  // Add APNS (Apple) config
  apns: {
    payload: {
      aps: {
        contentAvailable: true,
      },
    },
    headers: {
      "apns-push-type": "background",
      "apns-priority": "5", // Must be `5` when `contentAvailable` is set to true.
      "apns-topic": "", // bundle identifier
    },
  },
});
```

So when I press on the notification while the app is in foreground, I console.log detail object of event object which has Event type and it looks like this: 

```
detail: {
   "pressAction":{
      "id":"default"
   },
   "notification":{
      "body":"Body",
      "id":"gr5DAQFkX2TSHReseDFf",
      "data":{},
      "title":"Title",
      "ios":{
         "foregroundPresentationOptions":{
            "sound":true,
            "badge":true,
            "alert":true
         },
         "categoryId":"notification"
      },
      "subtitle":""
   }
}
```
You can see that body and title inside notification object are initialized with values that I sent through the node app. So the question is why is the data object empty even though I send it through the node app as well?

**Comment by mikehardy** [comment]
With respect I need to emphasize as it is important:

> Hi there, FCM and Notifee may be connected but are fundamentally separate.

Object shapes may differ. Notifee has APIs that take specific object shapes, and debugging node apps and FCM etc is out of scope here

> For the purposes of reproduction, can you create a minimal App.js that we can drop in an application created by this script https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh so we can see exactly what you're seeing?

**Comment by momirkostic** [comment]
Yes, I agree with you that object shapes may differ, but can you tell me then how to send a notification (which structure need to be) in order to get initialized data object.

BTW. I'll send you App.js file a little later.

**Comment by mikehardy** [comment]
In my app I have adapter code so that I guarantee Notifee gets the shape it expects. Once you have an App.js that uses nothing but Notifee APIs and does what you like, you may work backwards from there to non-Notifee things if needed. If you can show with the App.js file using nothing but Notifee APIs that things aren't working then we can examine in more detail as it would be an error in the module

**Comment by momirkostic** [comment]
Hi Mike, just to let you know that I fixed a problem. I added adapter, so now Notifee gets the shape it expects. Thanks

**Comment by mikehardy** [comment]
Excellent! I'm glad that worked, sorry the shapes aren't exactly the same but we're dealing with reserved words (notification / data) and external systems (FCM etc). Good luck with your project!
