### ISSUE TITLE
Came from react-native-firebase/v5, question about setBadge() on Android

### ISSUE THREAD

**Issue by tarouboy** [notifee/react-native-notifee#222]
First of all, great package! Going to purchase the license soon (Y)

When I was using react-native-firebase/v5, I used setBadge to manage the badge count. ( on Android with [ShortcutBadger](https://v5.rnfirebase.io/docs/v5.x.x/messaging/android) )
After reading the Notifee documentation, understand that setBadgeCount is iOS only. 
and I have some questions:

1. Does Notifee supports ShortcutBadger?
2. If an Android user came from the previous version (with RNFirebase/v5) with a badge count set, then updated to the new version (with Notifee). Is there anyway to clear the badge count with Notifee? or what will happen with his badge count?
3. I found "[Badges](https://notifee.app/react-native/docs/android/appearance#badges)" under Android > Appearance but I have no idea how to make use of it. Is it done automatically? Like just grouping the current notifications?

Thank you.

**Comment by Ehesp** [comment]
Hey

> Does Notifee supports ShortcutBadger?

We decided not to. The library is 3rd party and not well maintained. Also Google considers setting badge counts an anti-pattern so we left it out.

> If an Android user came from the previous version (with RNFirebase/v5) with a badge count set, then updated to the new version (with Notifee). Is there anyway to clear the badge count with Notifee? or what will happen with his badge count?


I believe it would reset automatically, since it's a new version of the app.

> I found "Badges" under Android > Appearance but I have no idea how to make use of it. Is it done automatically? Like just grouping the current notifications?

These are what are shown in the gif below, kinda like previews of a notification. You can disable them which is what the "Badges" mean on Android.

**Comment by tarouboy** [comment]
Thank you @Ehesp much appreciated.
In this case I will think of some other ways to migrate the badge count on Android then.
