### ISSUE TITLE
Do background restrictions affect only on "data" messages?

### ISSUE THREAD

**Issue by pavelpashkovsky** [notifee/react-native-notifee#228]
Hey guys, my question relates to [Notifee background restrictions](https://notifee.app/react-native/docs/android/background-restrictions#battery-optimization). Do they affect only "data" messages? But what if I have "notification" prop in push-notification object, should I optimize app in accordance with this part of the documentation?

**Comment by mikehardy** [comment]
Hi there! That's a reasonable question. I am not sure I or anyone can give you a complete answer as it is device and android-version specific.

In my experience (this was on a OnePlus 5 back in the Android 8 time) I had apps killed in the background *while they were running a foreground service specifically to stay alive*. Specifically, things like music equalizers would just be killed. So anything is possible.

https://dontkillmyapp.com has more vendor-specific details, but if possible I would direct the users just in case, if notifications are a core part of your app's experience (vs just informative). I would plan for the case where for some reason messages aren't delivered anyway (detect it and communicate it if possible). And I would test on the worst devices (Xioami, Huawei, OPPO I believe)

**Comment by helenaford** [comment]
Hi, thanks for the question. Background restrictions mainly affect your app if you are using trigger notifications not so much remote notifications. 

If you are remote notifications and are experiencing issues, there's things you can try such as changing the importance of the channel.  

Hope that helps.
