### ISSUE TITLE
[Android] - cannot create channel

### ISSUE THREAD

**Issue by jpudysz** [notifee/react-native-notifee#23]
I'm not able to create a notification channel with the v. 0.3.0 nor current master.

Steps to reproduce:

```
import notifee, { Importance } from '@notifee/react-native'

 notifee.createChannel({
   id: 'default',
   name: 'Default channel',
   importance: Importance.DEFAULT
})
```

Error:
`notifee.createChannel(*) Cannot read property DEFAULT of undefined. Changing importance to number eg. 4 causes same error.`

EDIT:
Changing import from '..' to '../types/Notification' fixes the issue.
https://github.com/notifee/react-native-notifee/blob/master/src/validators/validateAndroidChannel.ts#L11

Not sure why TS can't resolve it I have typescript in version `3.8.3`

**Comment by Salakar** [comment]
Taking a look at this now, thanks for the report

**Comment by Salakar** [comment]
Hey, I've published version 0.4.0 which includes a fix for this, please try it out - thanks

**Comment by jpudysz** [comment]
Version 0.4.0 causes error on app lunch.

![IMG_38E7BBE8C359-1](https://user-images.githubusercontent.com/9088288/78244009-14971580-74e5-11ea-8635-30a9942cb0ac.jpeg)

**Comment by jpudysz** [comment]
I was able to pass this error with 
```
rm -rf node_modules
rm -rf Pods
rm Podfile.lock
yarn install
cd ios
pod install
> clean build folder (XCode)
Rebuild
```
and for Android
```
cd android
./gradlew clean
> clean Project (Android Studio)
Rebuild
```
