### ISSUE TITLE
[iOS] Support for multiple Environments in notifee.config.json

### ISSUE THREAD

**Issue by lucaslenz** [notifee/react-native-notifee#234]
Hello,

I'm trying to configute notifee for iOS. It is working if i have a config file like that:

```json{
  "android": {...},
  "ios": {
      "license": "..."
    }
}
````

As I have more than one scheme (one for each environment) it would be nice if i could define all of them in the config `notifee.config.json`. I tried to set it up the same as on android where each tag in the "ios" section corresponds to one scheme. Apparently this does not work.

The documentation only states the Android configuration which is working very well. I am missing guidance on the iOS configuration. If that is not possible at the moment it would be good to at least say that in the documentation. Not having any information about that seems like someone forgot to put that information into the documentation.

**Comment by helenaford** [comment]
Hey thanks for bringing this to our attention. Think there's two things here 1. Docs need updating to add that there's no support for multiple envs. 2. This is a potential feature enhancement.

**Comment by lucaslenz** [comment]
I'm sorry but I'm confused now. So @mikehardy your configuration is working? So there is support for multiple envs on iOS? @helenaford you said, `that there's no support for multiple envs` ?!
@mikehardy Are "dev", "test", "staging", "release" XCode Schemes, Targets or just Build Configurations?

**Comment by mikehardy** [comment]
Those are targets, with firebase plist files and icons per-target and set into the targets by target / file association. There may not be official support yet but I chose my words carefully, you can verify in your project:

> ...and all functionality is 100 - are you seeing a functionality issue?

All my notifee API calls function correctly in iOS

**Comment by lucaslenz** [comment]
Okay, thank you for your answers. I will try that out!

**Comment by metervara** [comment]
I have a small follow-up question. @mikehardy your project uses targets, will this work for a project that is setup with multiple configurations too?

Thanks.

**Comment by mikehardy** [comment]
@metervara have you tested it? It should work 100% that way on iOS

**Comment by metervara** [comment]
Great, thanks.

I haven't tested it yet, I was uncertain about how to do that. I can see [here](https://github.com/notifee/react-native-notifee/issues/240) that if there are no error messages it is working, and in my case I have no errors.

**Comment by helenaford** [comment]
Docs now updated to reflect that iOS licensing is not required at this time. Please see https://notifee.app/react-native/docs/license-keys.
