### ISSUE TITLE
CancelNotification(id) not working on device's background/closed-status, cancelAllNotifications() works.

### ISSUE THREAD

**Issue by jonisorjonen** [notifee/react-native-notifee#235]
Hey,

our Firebase's
```
messaging().setBackgroundMessageHandler((message) => {
      return handleMessage(message);
    });
```

is fired on background, and code runs on called handleMessage(). When app on foreground, notifee.cancelNotification(id) works perfectly in handleMessage after sending overriding cancel notification from backend through FCM. Message-object includes both data + notification.

**Problem seems to be that cancelNotification(id) couldn't find cancellable notification with correct id when app is on background/closed**. The notifee.cancelAllNotifications() works instead. This occurs both on android and iOS. Have tried for example updating Notifee's version 0.14.0 --> 0.15.0, moving messaging().setBackgroundMessageHandler() / notifee.onBackgroundEvent() to index.js, checked channelID working on android with global channelID etc. 

EDIT: Our use case with this is to send notification with specified id and data to client, and when someone picks up this notification and approves the offered deal, we send cancelling notification to other clients so they don't have outdated notifications waiting on notification center's stray and so on.

Used React Native is 0.63.2 and @react-native-firebase/messaging": "^7.9.0". Notifee is paid version.

Big thanks if You have time to enlighten with this one.

ADDED MORE CODE:

```
import {useCallback, useEffect} from 'react';
import messaging, {
  FirebaseMessagingTypes,
} from '@react-native-firebase/messaging';
import notifee, { IOSAuthorizationStatus } from '@notifee/react-native';

export type NotificationType = 'PUBLISH' | 'CANCEL';

interface Message {
  data: {
    body: string;
    title: string;
    id: string;
    type: NotificationType;
  };
}

export const useSubscribeToNotifications = () => {

  useEffect(() => {
    messaging().registerDeviceForRemoteMessages();
  }, []);

  useEffect(()=> {
    requestUserPermission();
  }, []);

  const onMessageReceived = useCallback(
    (message: FirebaseMessagingTypes.RemoteMessage) => {
      handleMessage(message);
    },
    [],
  );

  useEffect(() => {
    notifee.onBackgroundEvent(async ({detail}) => {
      console.log('BACKGROUND EVENT: ', detail);
    });

    const unsubscribeOnMessage = messaging().onMessage(onMessageReceived);
    messaging().setBackgroundMessageHandler((message) => {
      return handleMessage(message);
    });

    return () => {
      unsubscribeOnMessage();
    };
  }, [onMessageReceived]);
};

const requestUserPermission = async () => {
  const settings = await notifee.requestPermission();

  if (settings.authorizationStatus >= IOSAuthorizationStatus.AUTHORIZED) {
    console.log('Permission settings:', settings);
  } else {
    console.log('User declined permissions');
  }
}

const handleMessage = async (
  message: FirebaseMessagingTypes.RemoteMessage,
) => {
  console.log('message', message);
  const channelId = await notifee.createChannel({
    id: 'test-1',
    name: 'for test',
  });

  const {
    body,
    title,
    id,
    type,
  } = ((message as unknown) as Message).data;

  try {
    if (type === 'PUBLISH') {
      await notifee.displayNotification({
        id,
        title: title,
        body: body,
        android: {
          channelId,
          smallIcon: 'ic_launcher',
          pressAction: {
            id: 'default',
          },
        },
      });
    } else {
      await notifee.cancelNotification(id);
      // notifee.cancelAllNotifications();
    }
  } catch (e) {
    console.log('failed to show/cancel notification');
    console.log(e);
  }
};
```

Might be also that those multiple background-listeners/ function calls are causing duplicate notifications with same id's, so not everyone of them aren't erased with cancelNotification(id) and are still on stray.

**Comment by mikehardy** [comment]
Hmm I can have a look but it might take a day or so, I have another item in the queue first. Mostly replying quickly to say that you should update your react-native-firebase, we're on v10.5 there now! (the updates should be easy but they're important, they bring in lots and lots of fixes (via new version) of the underlying firebase SDKs

**Comment by jonisorjonen** [comment]
Much appreciated if you have some time at some point. Will try those firebase-lib updates, thanks!

**Comment by helenaford** [comment]
Hi, how did you get on with the firebase updates?  Are you still experiencing this issue?

**Comment by helenaford** [comment]
Stale. closing this. Please re-open if you're still experiencing the issue
