### ISSUE TITLE
[Android] Notifications didn't played in silent

### ISSUE THREAD

**Issue by MitinDmytro** [notifee/react-native-notifee#236]
I need to create channel without sound
In docs I saw this: 

> To use the users default sound, set the value as default. For no sound, set the value to null. 
link: [https://notifee.app/react-native/docs/ios/behaviour#sound](url)

Steps to reproduce:

**index.js**
```
// Create a channel 
      await notifee.createChannel({
        id: 'default',
        name: 'default',
        sound: "null",
        vibration: true
      });

// Display a notification
  await notifee.displayNotification({
        id: notification.messageId,
        title:  "Title",
        body: "Body",
        subtitle: "subtitle",
        data: data,
        android: {
          channelId: "default",
          smallIcon: smallIcon,
          color: color,
          sound: "null",
          groupId: groupId
        }
      });
```

**Comment by VivienTournie** [comment]
It seems like you need to remove quotes around "null" for this to work as expected.

**Comment by MitinDmytro** [comment]
After removing quotes, I get the error:
`[Error: notifee.createChannel(*) 'channel.sound' expected a string value.]`

**Comment by VivienTournie** [comment]
Ah, so maybe there is a bug there, I'll let the maintainers answer .. :)

**Comment by MitinDmytro** [comment]
Also after deleting the "sound" parameter from createChannel/displayNotification methods, I hear a sound

**Comment by helenaford** [comment]
@MitinDmytro the sound property will accept either `undefined` or a `string` as a value (https://notifee.app/react-native/reference/androidchannel#sound). If it's still playing a sound... this could be a bug that we've missed; either with docs or with the code.

**Comment by helenaford** [comment]
I can confirm this works. When you are changing the sound on the channel, are you changing the channel id?  If you call `console.log("getChannel", await notifee.getChannel('default'));` you can see what properties are set for the channel. See https://notifee.app/react-native/docs/android/channels#creating--updating-channels, in particular,`Remember! Once the channel has been created only metadata values such as the name can be updated.`. 

So if you want to update the channel with id 'default', delete the channel first. `await notifee.deleteChannel('default');`

For no sound, create a channel with no `sound` property or set `sound: undefined`.

Hope this helps. Please re-open if you still see an issue.
