### ISSUE TITLE
[Android] Duplicated time only on Samsung phones

### ISSUE THREAD

**Issue by MitinDmytro** [notifee/react-native-notifee#238]
I need to delete duplicate time from a subtitle
**index.js**
```
// Display a notification
  await notifee.displayNotification({
        id: notification.messageId,
        title:  "Title",
        body: "Body",
        subtitle: Moment().format("DD/MM/YY HH:mm")
        data: data,
        android: {
          channelId: "default",
          smallIcon: smallIcon,
          color: color
        }
      });
```
![Untitled](https://user-images.githubusercontent.com/59180806/106164058-4246fc80-6192-11eb-801a-0339b14cf9a1.png)

**Comment by mikehardy** [comment]
That looks like a moment or Javascript issue perhaps platform specific, but if you console log just the result of that moment call it should have the problem yes? If so, it doesn't seem the place of notifee to do anything but post the passed string, error and all. Maybe clean it as a separate step if needed?

**Comment by MitinDmytro** [comment]
I see this issue only on Samsung phones and only if there are few notifications in group. Could it be that this is smth related to grouping?

**Comment by MitinDmytro** [comment]
I hardcoded subtitle, but real-time was added at the end of subtitle. You can see it in attached screenshot.

index.js
```
// Display a notification
  await notifee.displayNotification({
        id: notification.messageId,
        title:  "Title",
        body: "Body",
        subtitle: "28/01/21 19:19",
        data: data,
        android: {
          channelId: "default",
          smallIcon: smallIcon,
          color: color
        }
      }
```);
![image_2021_01_29T08_27_30_447Z](https://user-images.githubusercontent.com/59180806/106252251-b9c26d80-621e-11eb-92d4-dc929974c675.png)

**Comment by helenaford** [comment]
There's a way to detect if it's an Samsung device by using Notifee's getPowerManagerInfo() API (https://notifee.app/react-native/reference/powermanagerinfo#manufacturer) and not setting the subtitle for those devices.

But you could try using the showTimestamp property (https://notifee.app/react-native/docs/android/grouping-and-sorting#sorting-by-timestamp) and using the timestamp instead of using the subTitle?
