### ISSUE TITLE
[IOS] - How to verify that a license key is properly verified on iOS?

### ISSUE THREAD

**Issue by kekami** [notifee/react-native-notifee#240]
Hello,

I was trying to get the notifee library working last night, mostly trying to get `notifee.getInitialNotification()` to work, but it keeps returning undefined when launching the app from a push notification.

Reading the docs I noticed this line:
```
If an invalid license key is provided, your application will still continue to work as normal. However, all features provided by notifee will not work.
```

So maybe that is the culprit?

Is there a way to verify that the secondary key I created was properly validated on iOS? Docs seems to only have instructions for Android.

Versions being used:
notifee 1.1.0
react native 0.63.3

**Comment by mikehardy** [comment]
In debug mode, there are zero restrictions. On iOS I can basically guarantee that if your code is not working, it will not work in debug mode, where license key restrictions are not applied at all. So it is not licensing. Unfortunately the license positive-confirmation output added to Android was not added to iOS so you cannot positively confirm, however if there is a licensing issue there *will* be failure messages printed

**Comment by kekami** [comment]
I believe I tried it with a nonsense key without seeing any error messages in XCode in debug mode, e.g.
```
{
  "ios": {
    "license": "fake"
  }
}
```

What other reasons could there be for `notifee.getInitialNotification()` returning undefined when the app is launched via a push notification?

**Comment by mikehardy** [comment]
No validation whatsoever is performed in debug mode. If the code is correct, everything will work with no validation at all.

**Comment by mikehardy** [comment]
I'm not sure...If we saw the actual JSON you post to the FCM REST API (minus API keys, device tokens etc), and an App.js that reproduced it in isolation, we could say, otherwise I'm not sure :thinking:

**Comment by ryanbrink** [comment]
I had basically the same question. I don't see any way to validate that the license is working as expected on iOS. The Notifee docs show this for Android, but nothing for iOS.

Ryan

**Comment by mikehardy** [comment]
Everyone reading this: Stop worrying about validating the license on iOS. We'll update the docs to reflect this, but unless you see some very very very clear messages in your console saying validation *failed*, then it's working. Your code may not be working but it is not a license issue.

**Comment by helenaford** [comment]
@mikehardy think there's overlap with another issue (https://github.com/notifee/react-native-notifee/issues/234), where there's a doc change due to say licensing is not currently required on iOS.

**Comment by helenaford** [comment]
Docs now updated. Please see https://notifee.app/react-native/docs/license-keys. 

Also, quick note about the docs, they're open-sourced, so if you see anything that you think can be clearer or is missing, please feel free to open a p/r (https://github.com/notifee/documentation).
