### ISSUE TITLE
iOS recurring trigger notifications fire before timestamp value

### ISSUE THREAD

**Issue by ryanbrink** [notifee/react-native-notifee#241]
Hello, 

I'm attempting to schedule daily recurring notifications, so I'm using the Notifee trigger API. One of these daily notifications is suppose to start the next day but it's firing on the current day on iOS deployments.

Example: it's January 1 at 10 AM and I schedule a _daily_ recurring notification for January 2 at 11 AM. On Android, this notification will work as expected, but on iOS I will get a local notification on January 1 at 11 AM and every day thereafter.

I wonder if this is because Notifee is using the [UNCalendarNotificationTrigger](https://developer.apple.com/documentation/usernotifications/uncalendarnotificationtrigger), and specifying hours/seconds for a repeating trigger but not setting any restrictions on the day it starts?

**Comment by ryanbrink** [comment]
@helenaford, any advice on how to pursue a resolution for this?

**Comment by helenaford** [comment]
Hi, do you have an example of how you're creating the Trigger Notification? Are you using the TimestampTrigger?

Guessing you have something like this:

```
/* Create the date for the next day at 11am */
const date = new Date(Date.now());
date.setHours(11);
date.setMinutes(0);
date.setDate(date.getDate() + 1);
   
const trigger: TimestampTrigger = {
  type: TriggerType.TIMESTAMP,
  timestamp: date.getTime(),
  repeatFrequency: RepeatFrequency.DAILY, // repeat once a day
};
```

If this isn't working, sounds like it could be a potential bug... It should trigger from the initial date you set via the `timestamp` property 🤔

**Comment by ryanbrink** [comment]
That's almost exactly what I have, yes.

**Comment by helenaford** [comment]
I can reproduce this locally. Not sure what the solution is. It could be something we note in the docs as a limitation on iOS. Or, do you suggest an alternative? There's only a select number of triggers we can implement  (https://developer.apple.com/documentation/usernotifications/unnotificationtrigger?language=objc):
- TimeIntervalNotificationTrigger `Supported`
- UNCalendarNotificationTrigger `Supported`
- UNLocationNotificationTrigger `Not Supported`
- UNPushNotificationTrigger `Not Supported`

And, the UNCalendarNotificationTrigger is quite restrictive. 

A possible workaround could be setting a notification that repeats weekly for every day from `tomorrow`, for example:

```
// Current day is Monday 11am.
// Set a timestramp trigger for Tuesday, Wednesday, Thursday, Friday... 
const trigger: TimestampTrigger = {
  type: TriggerType.TIMESTAMP,
  timestamp: date.getTime(), //  Tuesday 11 AM
  repeatFrequency: RepeatFrequency.WEEKLY, // repeat weekly for Tuesday
};
```

**Comment by ryanbrink** [comment]
Hmm, okay thanks for looking into this, and glad you can reproduce it. I think that workaround could work for us, but it does mean frustratingly platform-dependent code. Thanks!

**Comment by helenaford** [comment]
Yes, sadly that is true, we do try to avoid platform-dependent code as much a possible. Maybe, as a feature enhancement we can do something with the api, where we can behind the scenes create multiple but you only have to call it once.  But, might have other side-effects and is more of a long-term enhancement, one to add to notifee's roadmap.
