### ISSUE TITLE
Notifee small Icon in Android

### ISSUE THREAD

**Issue by puneetkansal04** [notifee/react-native-notifee#243]
I am using it and found that small icon is not working hit a notification in android. I tried with ic_launcher, image from local location, image from internet, But nothing is worked and showing default android icon. As this icon even not showing launcher icon. It is showing a white icon. I even don't know where from it is getting this icon.

**Comment by mikehardy** [comment]
Icons on android may be problematic. If you have not processed the icon correctly (like, you attempted to use transparency or similar) this can happen, search engines will return lots of hits about that.

Additionally, the android resource shrinker has an interesting reaction with how people package icons sometimes, where the icons you want are removed during packaging: https://twitter.com/fastsquatch/status/1196475279688028160

**Comment by helenaford** [comment]
@puneetkansal04 we have a guide in the docs to help create a custom small icon [here](https://notifee.app/react-native/docs/android/appearance#small-icons), also with a note about a solid square if the app has found your icon, but it's not formatted correctly ( `The small icon must have a transparent background, otherwise Android will display a solid square.`. ). Hope that helps.

**Comment by puneetkansal04** [comment]
@helenaford @mikehardy as i tried everything. okay can you tell me in which folder the android res will work. As i have ic_launcher png, Transparency everything is maintained. Still i am not getting app icon on notifications. Can you please tell me where android is picking a white small icon. What can be possible case where android notification is picking a white icon. What is the location of this default icon. As it doesn't exist in my app. I hope this will help us to get more close to the error.

**Comment by helenaford** [comment]
Can you show a screenshot, is the white icon, a solid white square?

**Comment by princefishthrower** [comment]
Having the same issue. We already have an image asset called ic_launcher, but we only see the square. Do I need the full path? For example in our `AndroidManifest.xml` we have `android:icon="@mipmap/ic_launcher"`

though neither `ic_launcher` or `@mipmap/ic_launcher` are working, we still get the square (color property is working at least)

Looking for any additional tips here.

**Comment by mikehardy** [comment]
Not sure exactly but there is an example app - https://github.com/notifee/react-native-notifee/tree/master/example - have you tried it? I believe it has the icon correct (though maybe I'm wrong and it needs an update so it shows how to do this better...)

**Comment by princefishthrower** [comment]
@mikehardy - thanks for the quick reply. I finally got it working, I didn't realize that when generating the assets you need to specify the asset type of `Notification Icons` - which was what I was missing.
