### ISSUE TITLE
When click on Background notification or quit app notification redirection is not working.

### ISSUE THREAD

**Issue by harmit001** [notifee/react-native-notifee#244]

**Comment by mikehardy** [comment]
Hi there!
Can you provide any useful information to troubleshoot this?
- versions in use (package.json is usually useful)
- an App.js that minimally reproduces the issue when dropped in a clean project (e.g. from https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh)

Without details to help, we'll have to close this. Thanks!

**Comment by harmit001** [comment]
@mikehardy 
In Package JSON
"@react-native-firebase/messaging": "^10.6.4",
 "@notifee/react-native": "^1.1.0", 
 "react-native": "0.61.4",

Written below code in My Home screen 
componentDidMount(){
  messaging().onMessage(this.onMessageReceived);
    messaging().setBackgroundMessageHandler(this.onMessageReceived);
}

  onMessageReceived = async message => {
    const channelId = await notifee.createChannel({
      id: 'default',
      name: 'Default Channel',
    });

    await notifee.displayNotification({
      title: message.notification.title,
      body: message.notification.body,
      data: message.data,
      android: {
        channelId,
        smallIcon: 'ic_notification', // optional, defaults to 'ic_launcher'.
      },
    });
    notifee.onBackgroundEvent(async ({type, detail}) => {
      const {notification, pressAction} = detail;
      console.log('notification.data', notification.data);
      console.log('type', type, pressAction);
      console.log(type === EventType.PRESS);
      if (type === EventType.PRESS) {
        this.showAlertNotification(notification.data);
      }
      this.cancelNotification(notification.id);
      // if (type === EventType.ACTION_PRESS) {
      //   this.showAlertNotification(detail.notification.data);
      //   this.cancelNotification(notification.id);
      // }
    });

    notifee.onForegroundEvent(({type, detail}) => {
      switch (type) {
        case EventType.DISMISSED:
          this.cancelNotification(detail.notification.id);
          break;
        case EventType.PRESS:
          this.showAlertNotification(detail.notification.data);
          this.cancelNotification(detail.notification.id);
          break;
      }
    });
  };


In this.showAlertNotification() function Redirect Screen navigation

But When Application is in Foreground and Background At that Time click on Notification Only Open the Application not Redirect in Another Screen

**Comment by mikehardy** [comment]
I believe the react-native-firebase docs indicate to set the handlers prior to AppRegistry

I would follow the same structure to register notifee click handlers, setting a click handler inside each message handling doesn't seem correct to me

To be specific, I'm thinking:

`index.js`:

```javascript
import {AppRegistry} from 'react-native';
import App from './App';

// Generic message handler. This could be defined somewhere else but here should work
const onMessageReceived = async message => {
  const channelId = await notifee.createChannel({
    id: 'default',
    name: 'Default Channel',
  });

  await notifee.displayNotification({
    title: message.notification.title,
    body: message.notification.body,
    data: message.data,
    android: {
      channelId,
      smallIcon: 'ic_notification', // optional, defaults to 'ic_launcher'.
    },
  });
});

// register generic FCM handling logic as react-native-firebase handler, before AppRegistry per RNFB docs
messaging().onMessage(onMessageReceived);
messaging().setBackgroundMessageHandler(onMessageReceived);


// set notifee handlers here - *outside* context of handleEvent
notifee.onBackgroundEvent(async ({type, detail}) => {
  const {notification, pressAction} = detail;
  console.log(JSON.stringify(detail, null, 2);
  if (type === EventType.PRESS) {
    this.showAlertNotification(notification.data);
  }
  this.cancelNotification(notification.id);
});

notifee.onForegroundEvent(({type, detail}) => {
  switch (type) {
    case EventType.DISMISSED:
      this.cancelNotification(detail.notification.id);
      break;
    case EventType.PRESS:
      this.showAlertNotification(detail.notification.data);
      this.cancelNotification(detail.notification.id);
      break;
  }
});

// Now load your app

AppRegistry.registerComponent('MyApp', () => App);

```

`App.js`

```javascript

// your root view here, nothing related to click handlers

```

I would wrap everything in try/catches with appropriate error handling as well though, this is just the structural change I'd try first thing.

**Comment by harmit001** [comment]
@mikehardy 
I have implemented the above code But still Not get any On click Action When notification received Background and Foreground.

I have put this code in index.js file in the root.

import {AppRegistry} from 'react-native';
import App from './App';
import SplashScreen from 'react-native-splash-screen';
import {name as appName} from './app.json';
import Config from 'react-native-config';
import AsyncStorage from '@react-native-community/async-storage';
import messaging from '@react-native-firebase/messaging';
import notifee, {EventType, AndroidImportance} from '@notifee/react-native';
async function onMessageReceived(message) {
const channelId = await notifee.createChannel({
id: 'default',
name: 'Default Channel',
});

await notifee.displayNotification({
title: message.notification.title,
body: message.notification.body,
data: message.data,
android: {
channelId,
smallIcon: 'ic_notification', // optional, defaults to 'ic_launcher'.
},
});
}
messaging().onMessage(onMessageReceived);
messaging().setBackgroundMessageHandler(onMessageReceived);
notifee.onBackgroundEvent(async ({type, detail}) => {
const {notification, pressAction} = detail;
console.log(JSON.stringify(detail, null, 2));
if (type === EventType.PRESS) {
console.log('BACKGROUND CLICK EVENT', detail);
}
// this.cancelNotification(notification.id);
});

notifee.onForegroundEvent(({type, detail}) => {
switch (type) {
case EventType.DISMISSED:
break;
case EventType.PRESS:
console.log('FOREGROUND CLICK EVENT', detail);
break;
}
});
AppRegistry.registerComponent(appName, () => App);

**Comment by mikehardy** [comment]
Do not under any circumstances use react-native-splash-screen any more, I suspect that may be part of the problem.  It is an unmaintained buggy repository. react-native-boot-splash is the thing to use now - there have been lots of bugs reported concerning that module

You also have all this config, asyncstorage - all this other stuff.

Create a *minimal* (nothing else! not a single other thing than notifee) index.js and App.js to reproduce this.
