### ISSUE TITLE
[IOS] - Notification isn't displayed

### ISSUE THREAD

**Issue by MitinDmytro** [notifee/react-native-notifee#246]
Hello everyone! Please, help me :)

My method `"displayNotification"` doesn't show any messages on IOS real device` (IPhone 5, firmware: 10.3.4)` in **debug** mode. But in Android, it works perfectly.

Steps to reproduce:

**index.js**
```
// Create a channel 
      await notifee.createChannel({
        id: 'default',
        name: 'default',
        sound: "null",
        vibration: true
      });

// Display a notification
  await notifee.displayNotification({
        id: notification.messageId,
        title:  "Title",
        body: "Body",
        subtitle: "subtitle",
        data: data,
        android: {
          channelId: "default",
          smallIcon: smallIcon,
          color: color,
          sound: "null",
          groupId: groupId
        },
        ios: {
          foregroundPresentationOptions: {
            alert: true,
            badge: true,
            sound: true
          }
       }
      });
```

**Comment by mikehardy** [comment]
Can you please verify that you have granted permission for notifications for the app? For displaying simple notifications using the simulator is fine, real devices are really only for firebase messages testing. Does it work on a simulator on any ios version? Debug or release?

**Comment by helenaford** [comment]
With iOS, permissions are my go-to  as well if the notifications aren't showing (https://notifee.app/react-native/docs/ios/permissions) . 

Here's some example code on how to do that: 

```
import notifee, { IOSAuthorizationStatus } from '@notifee/react-native';

async function requestUserPermission() {
  const settings = await notifee.requestPermission();

  if (settings.authorizationStatus >= IOSAuthorizationStatus.AUTHORIZED) {
    console.log('Permission settings:', settings);
  } else {
    console.log('User declined permissions');
  }
}
```
