### ISSUE TITLE
[IOS] - How to group notification

### ISSUE THREAD

**Issue by MitinDmytro** [notifee/react-native-notifee#247]
Hello everyone!
Please, help me. 
How to group notification on IOS platform? I can't find it in the documentation.

**Comment by helenaford** [comment]
Hey, on iOS grouping is done automatically. There's an option to  customize the summary text via categories. https://notifee.app/react-native/docs/ios/categories

**Comment by helenaford** [comment]
Also, you can use threadId (https://notifee.app/react-native/reference/notificationios#threadid) which looks like is missing from the docs 🤔

**Comment by MitinDmytro** [comment]
Thank you, @helenaford!

**Comment by helenaford** [comment]
Docs updated with a note about threadId (https://notifee.app/react-native/docs/ios/categories).
