### ISSUE TITLE
[IOS] How to set icon for notification

### ISSUE THREAD

**Issue by MitinDmytro** [notifee/react-native-notifee#248]
Hi, everyone!
How to set a custom icon for my notification in `displayNotification()` method for IOS devices?
I can do it using a `smallIcon` property in android.

**Comment by helenaford** [comment]
Hey, the icon for iOS is the app icon, it's not possible to change it.

**Comment by MitinDmytro** [comment]
Don't you know any workaround? It's critical behavior for my application.

**Comment by helenaford** [comment]
It's possible to hide the default, in replace of a custom interface but you would have to do that integration natively using Apple's APIs directly, and not via Notifee. https://developer.apple.com/documentation/usernotificationsui/customizing_the_appearance_of_notifications
