### ISSUE TITLE
Build Failed During Archive my app Xcode 12.4

### ISSUE THREAD

**Issue by ahtisham09** [notifee/react-native-notifee#249]
Hello Everyone i hope you guys are going well i just upgrade xcode from 11 to 12.4 i got this error when i trying to archive my app for TestFlight i search a lot of things but nothing is work

<img width="905" alt="Screenshot 2021-02-17 at 5 11 12 PM" src="https://user-images.githubusercontent.com/59255791/108202801-7aaf7a00-7143-11eb-8228-0f50db207e14.png">

**Comment by helenaford** [comment]
Hi, it's been tested with 12.4 and everything should be working. Maybe try clearing your derived data folder and your pods, and trying again. 

I'm a bit confused from the log output you've shown how this is related to notifee. What does your Pods-Connect360-frameworks.sh script do ? Could you tell us what version of Notifee are you using? 

Thanks.

**Comment by ahtisham09** [comment]
hey @helenaford the issue is resolved by updating library My Notifee Previous version is   "@notifee/react-native": "^0.15.1", and i just upgrade the Notifee Library  "@notifee/react-native": "^1.1.0", 
Thanks for reply

**Comment by helenaford** [comment]
OK great, glad you found a fix :) thanks for letting us know.

**Comment by ahtisham09** [comment]
@helenaford No problem
