### ISSUE TITLE
[iOS] - IOSNotificationSettings is missing provisional permission

### ISSUE THREAD

**Issue by jpudysz** [notifee/react-native-notifee#25]
As a developer, I can't detect that user selected `provisional` permission.
This permission is requestable with `requestPermission` method, but `IOSNotificationSettings` returned with promise misses `provisional` flag.

**Use case:**
On app launch, I would like to request provisional permission silently and ask the user for full permissions after some time. With the current implementation, I'm not able to say if the user has provisional permission or not. I was trying to overcome it with `alert` or `authorizationStatus` flags but they won't work if I manually block permissions and grant it later.

**Comment by Salakar** [comment]
Hey @jpudysz - please see the `IOSNotificationSettings` > `authorizationStatus` value: https://notifee.app/react-native/reference/iosauthorizationstatus

E.g:

```js
import notifee, { IOSAuthorizationStatus } from '@notifee/react-native';

async function requestUserPermission() {
  const settings = await notifee.requestPermission();

  if (settings && settings.authorizationStatus === IOSAuthorizationStatus.PROVISIONAL) {
    console.log('Provisional Permissions', settings);
  }
}
```

---

cc @Ehesp is this covered on the docs anywhere?

**Comment by Ehesp** [comment]
I'll double check the docs.

Worth mentioning though once you request provisional permission, you can't force the popup again to re-request permission. The user has to select an option from the notification itself

**Comment by jpudysz** [comment]
Thanks @Salakar it worked!
It should be covered in the docs :)
