### ISSUE TITLE
[iOS] Not compiling for iPhone Xr - "Building for iOS, but linking in object file built for iOS Simulator. Architecture arm64"

### ISSUE THREAD

**Issue by MEsteves22** [notifee/react-native-notifee#250]
Hello,

We just bought a notifee key for our App but we are currently not able to compile it for a real iPhone Xr device. At the moment, we do not seem to have problems with iOS simulators and other real devices besides iPhone Xr.

The error we encountered while compiling our App is the following:

`in /Users/name/Library/Developer/Xcode/DerivedData/App-fctfklmpsliakgcgkfuoxlwebceo/Build/Products/Debug-iphoneos/NotifeeCore.framework/NotifeeCore(NotifeeCoreDownloadDelegate.o), building for iOS, but linking in object file built for iOS Simulator, file ‘/Users/name/Library/Developer/Xcode/DerivedData/App-fctfklmpsliakgcgkfuoxlwebceo/Build/Products/Debug-iphoneos/NotifeeCore.framework/NotifeeCore’ for architecture arm64`

The environment we are using is the following:

- macOS Big Sur 11.2.1 (20D75)
- Xcode 12.4 (12D4e)
- @notifee/react-native 1.1.0
- iPhone Xr iOS 14.4

Thank you for your help and answers!

**Comment by helenaford** [comment]
Hi, sorry you're experiencing that. I personally have an iPhone XR with iOS 14.4 and it works fine with Notifee 1.1.0. What other devices have you tried?

Was this a new install of Notifee, or an upgrade from an older version? 

In the logs, it looks like it's trying to to build for an iOS Simulator and not a real device, e.g. `but linking in object file built for iOS Simulator` and `Debug-iphoneos`. 

Could this be an issue with XCode where sometimes it is assuming you are building for the simulator and not the phone.

**Comment by MEsteves22** [comment]
Hello, thank you for your response! This is a new install of Notifee, not an upgrade from an older version.

We have also tried compiling the app on an iPad Air 2 (iOS 14.4) real device for debugging and everything worked fine. However, the iPhone XR is the one having problems when we try to do the same thing.

We've tried deleting the pods, the derived data folder, Xcode cache, and build data. Nothing seems to work at the moment.

**Comment by MEsteves22** [comment]
Hello, thank you for your response! 

I will try the solutions and recommendations you gave me and get back to you.

**Comment by MEsteves22** [comment]
Hello, since updating to @notifee/react-native 1.1.1 I am now able to compile my App on my iPhone XR for debugging.

Thanks for your time and help!

**Comment by mikehardy** [comment]
Great news! Good luck with your project
