### ISSUE TITLE
Firebase integration with Notifee

### ISSUE THREAD

**Issue by square1grp** [notifee/react-native-notifee#253]
I am trying to integrate FCM and notifee.

The notification data from the server contains `notification` and FCM SDK shows a notification automatically.

And also notifee is attached as a FCM backgroundMessagesHandler, notifee shows a notification too.

So there're 2 notifications for 1 event.

How can I fix it?

**Comment by mikehardy** [comment]
Hi there!

You must be careful in design, and choose what layer you want to show the on-device notification.

If you include a notification payload, the firebase SDKs will show notifications, as you see.

If you pop a Notifee notification from a background message handler for an FCM that *also* has a notification payload, of course you will get 2 notificaitons, as you see.

Either don't send FCM with notification payload, or don't show notifee notifications when there is a notification payload. But don't do both.

Each method has drawbacks - if you do data-only payloads the messages are unreliable: https://github.com/notifee/react-native-notifee/issues?q=is%3Aissue+unreliable+data-only+payload+

If you do notification-payload the messages are reliable but your code (including notifee) do not get control.

These are platform limitations unfortunately.
