### ISSUE TITLE
[Android] App crashing when opening a notification

### ISSUE THREAD

**Issue by Markuson** [notifee/react-native-notifee#256]
Hi all,

I'm starting to work with this library and integrating it to react-native-firebase.

What I found is, when pressing to a custom created notification via notifee.displayNotification(), tha app just crashes. However, if i launch a notification directly from firebase console. I press and it just opens the app. 

What I'm missing?? I've been looking for some information throught the issues and the documentation but i did not find anything.

Thanks.

**Comment by helenaford** [comment]
Hi, it's hard to know what exactly is wrong without knowing more details. A few questions:

- Is this happening in dev?
- Do you have any log output? 
- Is it crashing when the app is in the foreground/background/quit/all?
- What properties does your custom notification have?
- Can you show a snapshot of your code, in particular, displayNotification(...) and if you have any listeners, if you could paste those here too. 

I can see if there's anything obvious going on, or you can try to recreate the scenario using https://github.com/mikehardy/rnfbdemo and send us the link to your fork. All you have to do is edit `NotifeeApp.js`, and run `notifee-demo.sh `.

**Comment by Markuson** [comment]
Hi, 

- This is happening in Dev, yes. I don't have the license yet, cause we want to test the library and confirm it does everything we need before purchasing it.

- The app is crashing allways. When the notification pops out, if i press on it, it just crashes without logs.

see some snapshots of my code below:

`import firebaseMessaging from '@react-native-firebase/messaging';
import { Platform } from 'react-native';
import { customNotification } from './customNotification'
import notifee, {EventType} from '@notifee/react-native';

export const messaging = firebaseMessaging();

class fcmHelper {
  register = (
    onRegister: any,
    onNotification: any,
    onOpenNotification: any,
  ) => {
    this.checkPermission(onRegister);
    this.createNoitificationListeners(
      onRegister,
      onNotification,
      onOpenNotification,
    );
  };

  registerAppWithFCM = async () => {
    if (Platform.OS === 'ios') {
      await messaging.registerDeviceForRemoteMessages();
      await messaging.setAutoInitEnabled(true);
    }
  };

  checkPermission = async (onRegister: any) => {
    const authorizationStatus = await messaging.hasPermission();
    if (authorizationStatus === firebaseMessaging.AuthorizationStatus.AUTHORIZED) {
      //if user has permission
      console.log('fcm checkpermission true');
      this.getToken(onRegister);
    } else {
      //if user don't have permission
      console.log('fcm checkpermission false');
      this.requestPermission(onRegister);
    }
  };

  getToken = async (onRegister: (arg0: string) => void) => {
    const fcmToken = await messaging.getToken();
    if (fcmToken) {
      onRegister(fcmToken);
      console.log('User have a device token: fcm', fcmToken);
      customNotification.createChannel();
    } else {
      console.log('User does not have a device token: fcm');
    }
  };

  requestPermission = async (onRegister: any) => {
    if (messaging.isDeviceRegisteredForRemoteMessages) {
      await messaging.registerDeviceForRemoteMessages();
    }
    const authorizationStatus = await messaging.requestPermission({
      alert: true,
    });
    if (
      authorizationStatus === firebaseMessaging.AuthorizationStatus.AUTHORIZED || firebaseMessaging.AuthorizationStatus.NOT_DETERMINED
    ) {
      // this.getToken(onRegister)
      const token = await messaging.getToken();
      onRegister(token);
      console.log('Token fcm', token);
      customNotification.createChannel();
    } else if (
      authorizationStatus === firebaseMessaging.AuthorizationStatus.PROVISIONAL
    ) {
      console.log('User has provisional notification permissions.');
    } else {
      console.log('User has notification permissions disabled');
    }
  };

  deletedToken = () => {
    messaging.deleteToken().catch(error => {
      console.log('Delected token error fcm', error);
    });
  };

  createNoitificationListeners = (
    onRegister: any,
    onNotification: any,
    onOpenNotification: any,
  ) => {
    // Background
    messaging.onNotificationOpenedApp(remoteMessage => {
      console.log('OPENED FROM BACKGROUND!')
    });

    // Quit state
    notifee.getInitialNotification().then((remoteMessage:any) => {
      console.log('Opened from Quit or Background state', remoteMessage);
 
    })

    // ForeGround
    this.messageListener = messaging.onMessage(async (remoteMessage) => {
      console.log('FCM Foreground notification:', remoteMessage);
      const lastMessage = await customNotification.launch(remoteMessage.data);
      console.log('Fcm: last message launchedddd', lastMessage);
    })

    // Triggered when have  new token
    messaging.onTokenRefresh(token => {
      console.log('token was refreshed: fcm', token);
      onRegister(token);
      customNotification.createChannel();
    });
  };

  unRegister = () => {
    this.messageListener()
  };

  backgroundListener = () => {
    messaging.setBackgroundMessageHandler(async payload => {
      console.log('Fcm: message received in background', payload);
      const lastMessage = await customNotification.launch(payload.data);
      console.log('Fcm: last message launched', lastMessage);
      // return Promise.resolve(true);
    });
  };
}


export const FCMHelper = new fcmHelper();
`

here is how I create the notification with notifee:

`import notifee, { AndroidLaunchActivityFlag, EventType } from '@notifee/react-native';
import { Platform } from 'react-native';

class CustomNotification {

    channel = 'default'

    backgroundEvent = () => {
        notifee.onBackgroundEvent(async ({ type, detail }) => {
            const { notification, pressAction } = detail;
            if (type === EventType.ACTION_PRESS) {
                console.log("ACTION PRESS: ", pressAction)
            }
        })
        return Promise.resolve(true);
    }

    cancel = async (id: string | undefined) => {
        if (id) {
            await notifee.cancelNotification(id);
        }
    }

    createChannel = async (channel: string = this.channel) => {
        if (Platform.OS == 'android') {
            const channelId = await notifee.createChannel({
                id: channel,
                name: channel,
            });

            console.log('FCM Notification Android, channel name: ', channelId)
        }
    }

    launch = async (data: any, channelId: string = this.channel) => {
            const id = String(Date.now())
            const { body, title } = data

            console.log("launch CustonNotification: ", data)
            return await notifee.displayNotification({
                id,
                title,
                body,
                android: {
                    channelId,
                    smallIcon: 'smallicon_example',
                    groupId: channelId,
                    pressAction: {
                        id: 'default',
                        launchActivity: 'default',
                        launchActivityFlags: [AndroidLaunchActivityFlag.SINGLE_TOP],
                    },
                },
            });
        }
    }
}

export const customNotification = new CustomNotification`


`FCMHelper.backgroundListener();` is called on index.js and `FCMHelper.registerAppWithFCM();` is called on App.tsx on componentDidMount().

Also, my app it's managing redux. Don't know if coud be important.

**Comment by Markuson** [comment]
hey,
I just realized Deleting the `pressAction` part on the notification it's not crashing. It don't do nothing when pressing but et least it's not crahing.

So it should be there the problem. I would be missing something...

**Comment by mikehardy** [comment]
Hi there! There are always logs when there is a crash - on android watch unfiltered `adb logcat` while you have the emulator running and trigger the crash, you should see a stack trace?

**Comment by Markuson** [comment]
Ok, Sorry, i didn't know about logcat... I'm newbie with React-native.

On logcat i can see the fllowing:

```
03-01 14:05:04.540 22058 22058 E NOTIFEE : (ReceiverService): Launch Activity for notification does not exist ('default').
03-01 14:05:04.543 22058 22058 E AndroidRuntime: FATAL EXCEPTION: main
03-01 14:05:04.543 22058 22058 E AndroidRuntime: Process: com.myapp, PID: 22058
03-01 14:05:04.543 22058 22058 E AndroidRuntime: java.lang.RuntimeException: Unable to start service app.notifee.core.ReceiverService@309bd3f with Intent { act=app.notifee.core.ReceiverService.PRESS_INTENT cmp=com.myapp/app.notifee.core.ReceiverService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
```

**Comment by mikehardy** [comment]
react-native is a lot to learn all at once, given that problems frequently break the cross-platform abstraction and require iOS/Objective-C or Android/Java skills plus all the infrastructure knowledge like adb logcat. Well, you have a new trick now anyway :-). logcat is very very useful

One thing that might be even more useful is the actual stack frames, not just the Exception message. Could you post the complete stack trace?

So - the error - this looks like a multi-bug to me - Notifee code not being defensive enough about requested Activity, at least in Debug mode it should present much more useful diagnostic information (like via logbox, not logcat) vs crashing, and in production at minimum it should not crash

Something is unexpected about your native project setup - if you run this script from a clone of this repo does it work? https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh (it should work!)

If it does, then the thing to examine is `android/app/src/main/AndroidManifest.xml` to see how the Activities are set up I think

**Comment by Markuson** [comment]
there's many things happening on the logcat... sooo many things... I just get lost on it.

I'll paste here a piece of it. No idea if it will be enough.

```
03-01 14:38:46.165  1337  8997 D CompatibilityInfo: mCompatibilityFlags - 0
03-01 14:38:46.165  1337  8997 D CompatibilityInfo: applicationDensity - 320
03-01 14:38:46.165  1337  8997 D CompatibilityInfo: applicationScale - 1.0
03-01 14:38:46.166   770   797 I vendor.qti.hardware.servicetracker@1.2-service: startService() is called for servicecom.myapp/app.notifee.core.ReceiverService
03-01 14:38:46.172  3609  3609 V ShadeControllerImpl: NotificationShadeWindow: com.android.systemui.statusbar.phone.NotificationShadeWindowView{cce298 V.E...... ........ 0,0-720,1560} canPanelBeCollapsed(): true
03-01 14:38:46.173  4328  4328 I CNSS    : Failed to send nl message
03-01 14:38:46.179  4886  4886 D NotificationMService: onNotificationRemoved
03-01 14:38:46.186   509   509 E SELinux : avc:  denied  { find } for pid=4577 uid=10257 name=tethering scontext=u:r:vendor_systemhelper_app:s0:c512,c768 tcontext=u:object_r:tethering_service:s0 tclass=service_manager permissive=0
03-01 14:38:46.195 29190 29238 V bt_stack: [VERBOSE1:bta_gattc_main.cc(361)] bta_gattc_hdl_event: Event:BTA_GATTC_API_WRITE_EVT
03-01 14:38:46.195 12247 12247 E NOTIFEE : (ReceiverService): Launch Activity for notification does not exist ('default').
03-01 14:38:46.195 29190 29238 V bt_stack: [VERBOSE1:bta_gattc_main.cc(305)] bta_gattc_sm_execute: State 0x02 [GATTC_CONN_ST], Event 0x1f05[BTA_GATTC_API_WRITE_EVT]
03-01 14:38:46.195 29190 29238 V bt_stack: [VERBOSE1:gatt_utils.cc(1191)] gatt_end_operation status=0 op=3 subtype=1
03-01 14:38:46.195 29190 29238 V bt_stack: [VERBOSE1:bta_gattc_act.cc(1481)] bta_gattc_cmpl_cback: conn_id:6 op:3 status:0
03-01 14:38:46.195 29190 29238 V bt_stack: [VERBOSE1:bta_gattc_main.cc(341)] bta_gattc_sm_execute: GATTC State Change: 0x02 -> 0x02 after Event 0x1f05
03-01 14:38:46.196 29190 29238 V bt_stack: [VERBOSE1:bta_gattc_main.cc(361)] bta_gattc_hdl_event: Event:BTA_GATTC_OP_CMPL_EVT
03-01 14:38:46.196 29190 29238 V bt_stack: [VERBOSE1:bta_gattc_main.cc(305)] bta_gattc_sm_execute: State 0x02 [GATTC_CONN_ST], Event 0x1f0f[BTA_GATTC_OP_CMPL_EVT]
03-01 14:38:46.196 29190 29238 V bt_stack: [VERBOSE1:bta_gattc_act.cc(962)] bta_gattc_op_cmpl: op:3
03-01 14:38:46.196 29190 29238 V bt_stack: [VERBOSE1:bta_gattc_main.cc(341)] bta_gattc_sm_execute: GATTC State Change: 0x02 -> 0x02 after Event 0x1f0f
03-01 14:38:46.196   712   712 D vendor.qti.bluetooth@1.0-ibs_handler: SerialClockVote: vote for UART CLK ON
03-01 14:38:46.197 12247 12247 D AndroidRuntime: Shutting down VM
03-01 14:38:46.198   712   712 D vendor.qti.bluetooth@1.0-wake_lock: Acquire wakelock is acquired 
03-01 14:38:46.198   712   712 I vendor.qti.bluetooth@1.0-ibs_handler: DeviceWakeUp: Writing IBS_WAKE_IND
03-01 14:38:46.199  4328  4328 I CNSS    : Failed to send nl message
03-01 14:38:46.200 12247 12247 E AndroidRuntime: FATAL EXCEPTION: main
03-01 14:38:46.200 12247 12247 E AndroidRuntime: Process: com.myapp, PID: 12247
03-01 14:38:46.200 12247 12247 E AndroidRuntime: java.lang.RuntimeException: Unable to start service app.notifee.core.ReceiverService@b216bbe with Intent { act=app.notifee.core.ReceiverService.PRESS_INTENT cmp=com.myapp/app.notifee.core.ReceiverService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4337)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:238)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7698)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at android.content.ComponentName.<init>(ComponentName.java:132)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at android.content.Intent.<init>(Intent.java:6870)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at app.notifee.core.ReceiverService.nz_n(SourceFile:34)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at app.notifee.core.ReceiverService.onStartCommand(SourceFile:44)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4319)
03-01 14:38:46.200 12247 12247 E AndroidRuntime: 	... 8 more
03-01 14:38:46.201   712 29236 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_WAKE_ACK: 0xFC
03-01 14:38:46.206   722  3064 E qdmetadata: paramType 2048 not supported
03-01 14:38:39.586  1337  2105 I Nat464Xlat: Android Xlat is disabled
03-01 14:38:46.209  1337  8997 W ActivityTaskManager:   Force finishing activity com.myapp/.MainActivity
03-01 14:38:46.209  1337  8997 V ActivityTaskManager: Calling mServicetracker.OnActivityStateChange with flag truestateFINISHING
03-01 14:38:46.209  1337 12455 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
03-01 14:38:46.209  1337  8997 V ActivityTaskManager: Calling mServicetracker.OnActivityStateChange with flag falsestateFINISHING
03-01 14:38:46.209   770   797 I vendor.qti.hardware.servicetracker@1.2-service: Activity state is changed to : 7
03-01 14:38:46.210  1337  8997 V ActivityTaskManager: Calling mServicetracker.OnActivityStateChange with flag truestateFINISHING
03-01 14:38:46.211  1337  8997 V ActivityTaskManager: Calling mServicetracker.OnActivityStateChange with flag truestateDESTROYING
03-01 14:38:46.211  1337  8997 V ActivityTaskManager: Calling mServicetracker.OnActivityStateChange with flag falsestateDESTROYING
03-01 14:38:46.210   770   797 I chatty  : uid=1000(system) servicetracker@ identical 1 line
03-01 14:38:46.210   770   797 I vendor.qti.hardware.servicetracker@1.2-service: Activity state is changed to : 7
03-01 14:38:46.212   770   797 I vendor.qti.hardware.servicetracker@1.2-service: Activity state is changed to : 8
03-01 14:38:46.220  1337  1513 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
03-01 14:38:46.220  1337  1513 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
03-01 14:38:46.212   770   797 I vendor.qti.hardware.servicetracker@1.2-service: Activity state is changed to : 8
03-01 14:38:46.223  3609  3609 D fpod    : onWindowFocusChanged updatefpodstate 
03-01 14:38:46.223  3609  3609 I fpod    : isUnlockingWithFingerprintAllowed:true
03-01 14:38:46.223  3609  3609 D fpod    : mQsExpanded : false and mKeyguardOccluded : false  and moveHelperCanShow : true and bouncer : false and mHasWindowFocus : false and ignoreFocusChange : false and isShouldShowGxzwIconInKeyguard : true and isShowFpodInBouncer : true KeyguardVisible: false
03-01 14:38:46.223  3609  3609 I fpod    : (mQsExpanded || mKeyguardOccluded || !moveHelperCanShow) ?
03-01 14:38:46.223  3609  3609 I fpod    : canShow:false
03-01 14:38:46.223  3609  3609 I NotificationPanelViewCt: updateFpodState: mQsExpanded = false, mKeyguardOccluded = , moveHelperCanShow = true, bottomAreaCanShow = , bouncer = false, mHasWindowFocus = false, ignoreFocusChange = false, mLockScreenMagazinePreViewVisible = , isShowFpodInBouncer = true
03-01 14:38:46.223  3609  3609 D FpodManager: dismissFpodIconView  dismiss = true  mShouldShowFpodIconInKeyguard = true mKeyguardShow = false
03-01 14:38:46.227  1337  2072 I SensorService: user found in check list, getPackageName  android.view.OrientationEventListener
03-01 14:38:46.227  1337  2072 I chatty  : uid=1000(system) SensorService identical 3 lines
03-01 14:38:46.227  1337  2072 I SensorService: user found in check list, getPackageName  android.view.OrientationEventListener
03-01 14:38:46.228  2547  2547 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3311 
03-01 14:38:46.228  2547  2547 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1914 
03-01 14:38:46.229 12247 12247 I Process : Sending signal. PID: 12247 SIG: 9
03-01 14:38:46.229  4328  4328 I CNSS    : Failed to send nl message
03-01 14:38:46.233   712 29236 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
03-01 14:38:46.233   712 29236 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Writing IBS_WAKE_ACK
03-01 14:38:46.243  1337  8997 D CompatibilityInfo: mCompatibilityFlags - 0
03-01 14:38:46.243  1337  8997 D CompatibilityInfo: applicationDensity - 320
03-01 14:38:46.243  1337  8997 D CompatibilityInfo: applicationScale - 1.0
03-01 14:38:46.245   770   797 I vendor.qti.hardware.servicetracker@1.2-service: startService() is called for servicecom.google.android.gms/.stats.service.DropBoxEntryAddedService
03-01 14:38:46.249  1337  4529 D CompatibilityInfo: mCompatibilityFlags - 0
03-01 14:38:46.249  1337  4529 D CompatibilityInfo: applicationDensity - 320
03-01 14:38:46.249  1337  4529 D CompatibilityInfo: applicationScale - 1.0
03-01 14:38:46.250   770   797 I vendor.qti.hardware.servicetracker@1.2-service: startService() is called for servicecom.google.android.gms/.chimera.GmsIntentOperationService
03-01 14:38:46.252   722  3064 E qdmetadata: paramType 2048 not supported
03-01 14:38:46.260   770   797 I vendor.qti.hardware.servicetracker@1.2-service: destroyService is called for service : com.google.android.gms/.stats.service.DropBoxEntryAddedService
03-01 14:38:46.263  4328  4328 I CNSS    : Failed to send nl message
03-01 14:38:46.269   722  3064 E qdmetadata: paramType 2048 not supported
03-01 14:38:46.274   712 29236 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE

```

**Comment by mikehardy** [comment]
I edited it down to just the relevant parts of the exception - and it's gold! thank you @helenaford possibly of interest? I won't have time to fix the Notifee library part of the issue for a while so can't volunteer for that one

@Markuson I still believe this should not happen for your app and there is a configuration issue in your app. It should be possible to get this to work, I literally tested it on my app just now and it works. We should not crash of course, but there should be nothing blocking you from examining the AndroidManifest.xml / project generated from notifee-demo.sh compared with yours and finding a difference. There must be a difference and finding+fixing it should get you going

**Comment by Markuson** [comment]
thanks for your help @mikehardy !

I've found react-native-splash-screen could cause some problems. we are using this library, I'll try to do some research on this.

Also, there's many things in our AndroidManifest.xml. many of it out of my control so maybe I should find some help on this through my colleagues.

**Comment by mikehardy** [comment]
Indeed! I am vocal in my assertion that react-native-splash-screen should never be used at this point https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454 (with recommendation on alternative)

That may help in this case, as the way an Android app starts up is directly affected by splash screens and this crash is definitely in the area of the Android app starting up

**Comment by Markuson** [comment]
Finally I found a workaround,

Not sure if it's correct at all, but it's working!

just pointed to the mainActivity on launchActivity. see below:

```javascript
notifee.displayNotification({
                id,
                title,
                body,
                android: {
                    channelId,
                    smallIcon,
                    groupId: channelId,
                    pressAction: {
                        id: 'default',
                        launchActivity: 'com.myapp.MainActivity'
                    },
                },
            });
```

**Comment by helenaford** [comment]
@Markuson sorry you faced this issue! I'm glad you found a fix! The way you've set it to 'com.myapp. MainActivity' is actually the way it's [documented](https://notifee.app/react-native/docs/android/interaction#advanced-android-custom-activity) but `launchActivity` should only be used if you want a custom activity to launch instead of your `MainActivity` (https://notifee.app/react-native/reference/notificationpressaction#launchactivity).

So you could also try removing that property altogether. 

@mikehardy is spot on regarding this is still an issue with the library,  as we should put some things in place so the issue is highlighted in development easier so thanks for bringing this to our attention 👍
