### ISSUE TITLE
Building for iOS, but linking in object file built for Mac Catalyst - Vanilla RN project running against device

### ISSUE THREAD

**Issue by dlockwo** [notifee/react-native-notifee#265]
When attempting to run a vanilla RN project with notifee on a device in debug, I receive the following build error:

ld: in /Users/damon/Source/AwesomeTSProject/ios/DerivedData/AwesomeTSProject/Build/Products/Debug-iphoneos/NotifeeCore.framework/NotifeeCore(NotifeeCore+NSNotificationCenter.o), building for iOS, but linking in object file built for Mac Catalyst, file '/Users/damon/Source/AwesomeTSProject/ios/DerivedData/AwesomeTSProject/Build/Products/Debug-iphoneos/NotifeeCore.framework/NotifeeCore' for architecture arm64

Steps to reproduce:
* Create new vanilla RN project using npx react-native init AwesomeTSProject --template react-native-template-typescript
* Run yarn install 
* Run yarn add @notifee/react-native
* Run cd ios && pod install && cd ..
* Run yarn run ios, the app should correctly open in the simulator
* Connect a device (in my case an iPad)
* Run yarn run ios -- --device, the build will fail with the message above

Note that running on a device fails only in debug with vanilla project. In my production project it also fails in release but I haven't figured out the difference thus far.

**Comment by dlockwo** [comment]
[AwesomeTSProject.zip](https://github.com/notifee/react-native-notifee/files/6103134/AwesomeTSProject.zip)
Excludes node_modules and pods

**Comment by mikehardy** [comment]
This path is suspicious:

> Users/damon/Source/AwesomeTSProject/ios/DerivedData/AwesomeTSProject/Build/Products/Debug-iphoneos/NotifeeCore.framework/

We did a lot of work on this #215  / #162 / #224 

The path should be `NotifeeCore.xcframework` I believe, if you have the correct versions ?

Can you reproduce from our bare-bones skeleton-project builder? https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh - we have one dev (me) on x86_64 still but Helena is on an M1 mac now and we've not had any problems since #224 went in

**Comment by dlockwo** [comment]
I can confirm I receive the same message using the notifee demo and running npm run ios -- --device.

ld: in /Users/damon/Source/rnfbdemo/notifeedemo/ios/DerivedData/notifeedemo/Build/Products/Debug-iphoneos/NotifeeCore.framework/NotifeeCore(NotifeeCore+NSNotificationCenter.o), building for iOS, but linking in object file built for Mac Catalyst, file '/Users/damon/Source/rnfbdemo/notifeedemo/ios/DerivedData/notifeedemo/Build/Products/Debug-iphoneos/NotifeeCore.framework/NotifeeCore' for architecture arm64

**Comment by mikehardy** [comment]
Well, that's no good. Thanks for double-checking, beauty of knowing it reproduces with that script is that...it's a script - I can keep bending it as needed for reproduction, you can see it, and we can get this thing fixed quickly I hope.

**Comment by mikehardy** [comment]
Quick question - can you give me your host machine type and ipad device type? In case those are important I want to make sure I/we know what we're dealing with. The Intel vs Apple silicon difference is quite large for instance

**Comment by dlockwo** [comment]
Sure, here's my machine and device:
Mac Book Pro 2015, Big Sur, XCode 12.4
iPad 7th Generation, IOS 14.4

**Comment by mikehardy** [comment]
Very strange, I just ran it from a MacBook Pro (Retina, 15-inch, Mid 2015) (our machines are kin I think), macOS 11.2.2, Xcode 12.4 onto an iPhone SE (1st Generation) iOS 14.4 and it ran. I had to open Xcode to tell it to use my development team for the real device but that was it. I tested it from Xcode after verifying the scheme for run was debug even.

So I can't reproduce this 🤔 

Suggest `npx react-native-clean-project` and retry perhaps?

**Comment by dlockwo** [comment]
I believe I tracked this down to multiple installs of ruby on my machine (system vs homebrew) that resulted in the wrong version of cocoapods being used for the install. Either that or 1.2.0 fixed it. Either way I can't reproduce. Closing.

**Comment by mikehardy** [comment]
Oh no! That's a very subtle problem, and a frustrating loss of time.

We have actually made a change that would cause those sorts of problems to be very obvious instead of subtle:

https://github.com/notifee/react-native-notifee/blob/e41a4e20a5fafca557d0cf22ebe99711793d2ec1/RNNotifee.podspec#L17

But it was made just after the last release and has not been released yet. This should not happen to future people though, assuming we make a release shortly (@helenaford :-) )
