### ISSUE TITLE
[iOS] - createCategory is not a function

### ISSUE THREAD

**Issue by jpudysz** [notifee/react-native-notifee#27]
Prerequisites:
```
@notifee/react-native: 0.4.0
iPhone simulator
```

Steps to reproduce:
```
import notifee from '@notifee/react-native'

notifee.createCategory({
    id: 'test'
})
```

Result:
```
Unhandled JS Exception: TypeError: this.native.createCategory is not a function. (In 'this.native.createCategory(options)', 'this.native.createCategory' is undefined)
```

**Comment by Ehesp** [comment]
Could you try using: `setNotificationCategories` instead? See docs: https://notifee.app/react-native/docs/ios/categories

Looks like `createCategory` was a left-over we forgot to remove whilst building the API. Will get it removed.

**Comment by Ehesp** [comment]
https://github.com/notifee/react-native-notifee/pull/28

**Comment by jpudysz** [comment]
Thanks, I'm not using it for now. I wanted to let you know that there is a crash as notifee is in the alpha phase.
