### ISSUE TITLE
Remote Notification support - how to receive any event in JS after clicking on the notification?

### ISSUE THREAD

**Issue by pro-nasa** [notifee/react-native-notifee#273]
I'm following this guide:
https://notifee.app/react-native/docs/ios/remote-notification-support

When the app is in foreground state - everything is fine. I get remote notifications and display local notifications (with actions).

When the app is in background or quit state, remote notifications are displayed (without actions), but  could you give an example of how to receive any event in JS after clicking on the notification? E.g. after clicking on the notification, I want to show the right view after launching the app

My index.js file:

```js
import notifee from '@notifee/react-native'
import messaging from '@react-native-firebase/messaging'
import { fcm } from './utils'

messaging().onMessage(fcm.handleMessageReceived)
messaging().setBackgroundMessageHandler(fcm.handleMessageReceived)
notifee.onBackgroundEvent(fcm.handleBackgroundEvent)

function HeadlessCheck({ isHeadless }) {
  if (isHeadless) {
    return null
  }
  const App = require('./src/App').default
  return <App />
}

AppRegistry.registerComponent('MyApp', () => HeadlessCheck)
```

I set all categories and listeners for foreground inside the `<App />`

_________

```
// notifee_options, ios
{
    ...
    categoryId: 'post', // A category that's already been created by your app
    ...
};
```

So, what is this fragment "A category that's already been created by your app" about? How does it work when the app is in quit state?

________

My payload:
```js
{
    "to": "TOKEN",
    "notification": {
        "title": "Do you want to approve this login?",
        "body": "Someone's trying to log into your account"
    },
    "data": {
        // this additional data is here to display local notification with the right categoryId when the app is in foreground state (onMessage)
        "notifee": "{\"ios\":{\"categoryId\":\"TWO_FACTOR_AUTH\"}}",
    },
    "apns": {
        "payload": {
            "aps": {
                "content-available": 1,
                "mutable-content": 1
            },
            "notifee_options": {
                "ios": {
                    "categoryId": "TWO_FACTOR_AUTH"
                }
            }
        }
    }
}
```

_______

Categories (currently only for local notifications when the app is in foreground state)
```json
[
  {
     "id": "TWO_FACTOR_AUTH",
     "actions": [
        {
          "id": "approve",
          "title": "Approve",
          "foreground": false
        },
        {
          "id": "deny",
          "title": "Deny",
          "foreground": true
        }
     ]
  }
]
```

**Comment by mikehardy** [comment]
I think the pattern is:

- have some kind of storage for state where you may register "a notification click happened, with this info", and you can ask "did any notification clicks happen? can you give me info?"
- register a background notification click handler that registers the click into your state storage
- on startup, once the app is about to render it's main view, see if you have notification clicks to handle, and if so go there instead of your default view

? Not sure that's on target, but that's the pattern I use - the "category" you mention is like a navigation route or something, it is something that will be app-specific and you are in control of it I think?

**Comment by pro-nasa** [comment]
@mikehardy Will I have to do most of these things on the native side?

**Comment by mikehardy** [comment]
I do all of these things in JS, state solutions include redux etc (I use ReSub, and it works), click handlers are as documented but wire in to that, then you put a wrapper around your main app render that checks and renders a different route if needed?

**Comment by pro-nasa** [comment]
@mikehardy Thank you for the answer, let me describe my issue in more detail

My previous problem for iOS was that I never received (or with a long delay) notifications. If the app was in the background for some time - I didn't receive any notifications either.

That's why I decided to use NotificationServiceExtension, now notifications come immediately because they are not silent and don't require displaying a local notification (by JS). They are extended by this service and displayed. I have agreed that now when the app is killed, the displayed notification will not contain actions (unless I can somehow add categories/actions in native code?)

When the app is in the foreground, it easily gets a message and display local notification with the actions and handle the event for press action.

But if the app is killed and I get a notification, I don't get any events/initial-notification in JS when I click the notification and launch the app.

BTW. Everything works fine on Android but it uses HeadlessJS, iOS uses EventEmitter and I don't know exactly how "notifee.onBackgroundEvent" works here when the app is killed (but I don't think this handler is used for non-local/non-notifee notification)

______

At least that's how I understand it working

**Comment by mikehardy** [comment]
Oh ! I'm not as familiar with the notification extension as that is brand new and on my weak side (objective-C / iOS) so I think I went off-target there, sorry. I believe I understand what you want now I just can't personally answer - perhaps @helenaford has some thoughts on how to implement hooks into JS-land from the extension?

**Comment by helenaford** [comment]
Hi @pro-nasa, the events should be coming in as normal as any other `notifee` notification via `notifee.onBackgroundEvent`. From testing, events should be coming through 🤔 

The actions should be displaying too. What I mean by this `A category that's already been created by your app` is that you have to create the category beforehand. So, create the category when the app is open (for example. when the app is first opened), and then you can send notifications. 

Maybe we could look into create the category via the extension but at the moment it mimics the behaviour of `displayNotification`, where it's expected the category has already been created.

I will do some more tests around the events when the app is in the quit-state. maybe the js isn't waking up as expected. Is there a particular event you require? is it mainly the PRESS & ACTION_PRESS events? It will help for when I'm testing to know more about your particular scenario.

**Comment by helenaford** [comment]
Hi @pro-nasa, please can you let us know if this is still an issue?

If no events are still failing to come through, please can you provide some more details, and we will try and help debug the problem.

**Comment by helenaford** [comment]
Close due to lack of activity.
