### ISSUE TITLE
FCM Android - backwards compatible

### ISSUE THREAD

**Issue by pro-nasa** [notifee/react-native-notifee#274]
Do you plan to add support for standard notifications (contains title and body) in future versions? Anything like "Notification Service Extension" for iOS. It's just about to get such a notification with `notifee.getInitialNotification()` and catch it if the user clicks on it. 

**Context:**
We need to support notifications sent the old way (with title and body, but without actions). At least for a while. We currently support both `react-native-push-notification` and `notifee`. And it works. But it requires some extra tangled code along with notifee.

Notifications sent the old way:
```
{
  notification: {
    title: 'TITLE',
    body: 'BODY'
  },
  data: {
    ...
  }
}
```
Data-only notifications:
```
{
  data: {
    notifee: {
      title: 'TITLE',
      body: 'BODY',
      ...
    }
  }
}
```

**Comment by mikehardy** [comment]
I *think* that was just released? https://notifee.app/react-native/docs/release-notes#120

Hopefully that's what you mean, and if so it is brand new so feedback is welcome, to know if it's working well or not

**Comment by pro-nasa** [comment]
@mikehardy Yup, this is for iOS, it would be nice to have something like this for Android as well. Currently, the integration with FCM focuses on sending a silent notification and displaying a local one. Non-silent notifications are displayed immediately. That's why it would be nice to handle such notifications as well.

**Comment by pro-nasa** [comment]
So all that is needed is to deliver such a notification to JS

**Comment by pro-nasa** [comment]
so to support the old notifications you still need to use the old library:

```js
import notifee from '@notifee/react-native'
import messaging, { FirebaseMessagingTypes } from '@react-native-firebase/messaging'
import RNPN from 'react-native-push-notification'

...

if (Platform.OS === 'android') {
  RNPN.configure({
    popInitialNotification: false,
    requestPermissions: false,
    onNotification: handleRNPNotification,
    onRegistrationError,
    onRegister,
   })
 }
 
 messaging().onMessage(handleMessageReceived)
 messaging().setBackgroundMessageHandler(handleMessageReceived)
 notifee.onBackgroundEvent(handleBackgroundEvent)
 
 ...
```

**Comment by helenaford** [comment]
Hey, thanks for the question. This is something that I've been looking into to because I understand by having data-only for android and not iOS could produce platform-dependent code.

I'm not sure if I understand the issue around having to still use `RNPN` as Firebase message provide `getInitialNotification`. That should remove the need for that package, right?

**Comment by helenaford** [comment]
Closes this in favour of https://github.com/notifee/react-native-notifee/issues/183
