### ISSUE TITLE
Name to use for android foreground service in AndroidManifest.xml

### ISSUE THREAD

**Issue by gpfunk** [notifee/react-native-notifee#282]
From what I can tell in the android [docs](https://developer.android.com/guide/components/foreground-services#types) I need to set something like this -> `<service android:name="" android:foregroundServiceType="location" />` to get location updates while the app is backgrounded (and the foreground service is active)

I know the core android code isn't open source, could you provide the name to use for this?

**Comment by gpfunk** [comment]
Did some digging, looks like pointing it to `app.notifee.core.ForegroundService` seems to work. May be worth while to add to the docs for others?

Thanks again for the great lib!

**Comment by helenaford** [comment]
Thank you. That looks like something we can add 😎 , and even add support to restrict access to types when the foreground service is started. 🤔

**Comment by helenaford** [comment]
Docs have been updated 😎 https://notifee.app/react-native/docs/android/foreground-service#specifying-foreground-service-types
