### ISSUE TITLE
Can I put notifee.config.json file in my version control?

### ISSUE THREAD

**Issue by shubhamdeol** [notifee/react-native-notifee#284]
One possible solution can be to create notifee.config.example.json file and add to git. 

What are common best practices please share.

**Comment by mikehardy** [comment]
My notifee.config.json is definitely in source control, the test app we use for internal library development definitely has it in source control, I imagine there are other ways to do it (as with all things software), but I'd put it in source control just like any other config file (`firebase.json` for react-native-firebase, prettier configs, etc etc)
