### ISSUE TITLE
Recurring weekly notifications for the future will trigger one week early if set to >1 week in the future

### ISSUE THREAD

**Issue by kttien** [notifee/react-native-notifee#289]
I have a similar issue to the one discussed [here](https://github.com/notifee/react-native-notifee/issues/241) but for the weekly repeating frequency when trying to use the suggested workaround. 
Ultimately, I need to schedule a daily notification to begin more than 24 hours from now. We're already aware of the iOS bug that causes a daily notification scheduled for tomorrow to fire early at the same time on the current day. The suggested workaround was to create multiple weekly notifications starting with tomorrow. However, I've found the same early firing pattern for this solution. For example, if the current time is 10AM Monday and I'm trying to create a weekly notification to start next Monday at 11AM, it will still fire today at 11AM. Are there any suggested solutions to this?

```///* Create the date for the next week at 11am */
const date = new Date(Date.now());
date.setHours(11);
date.setMinutes(0);
date.setDate(date.getDate() + 7);
   
const trigger: TimestampTrigger = {
  type: TriggerType.TIMESTAMP,
  timestamp: date.getTime(),
  repeatFrequency: RepeatFrequency.WEEKLY, // repeat once a week
};```

**Comment by kttien** [comment]
@helenaford I think you were the one helping out on the previous issue when this was first brought up. Any help would be greatly appreciated!

**Comment by helenaford** [comment]
Hey @kttien, I think this sounds like the similar issue to the daily one like you mentioned. I'll add a note in docs this happens for all 'RepeatFrequency' issues with iOS. Maybe you could send a remote notification to that schedule one when needed
