### ISSUE TITLE
Foreground notifications not shown prior to API 26

### ISSUE THREAD

**Issue by mars-lan** [notifee/react-native-notifee#291]
Normal notifications are displayed correctly but not [foreground notifications](https://notifee.app/react-native/docs/android/foreground-service). Calling `notifee.displayNotification` with `android.asForegroundService` set to `true` doesn't seem to do anything on API 22-25. The same code works fine in API 27+ ([crashes on API 26](https://github.com/notifee/react-native-notifee/issues/290) though).

It might have something to do with with [Notification Channel](https://developer.android.com/training/notify-user/channels) which was introduced since API 26.

**Comment by helenaford** [comment]
Think we can group this issue with #290.
