### ISSUE TITLE
Flowjs types?

### ISSUE THREAD

**Issue by compojoom** [notifee/react-native-notifee#294]
Are there any plans to have flowjs types?

**Comment by mikehardy** [comment]
There are no plans for Flow typing no - typescript appears to be the way of the future.
However, as a developer I support any typing vs no typing, and another project had easy success with this:
https://github.com/joarwilk/flowgen

Perhaps putting that in your package.json post-install could work? Then if it worked you could submit to flow-typed?

**Comment by compojoom** [comment]
Thanks Mike. Will check it out.
