### ISSUE TITLE
[ANDROID] Fail task native:bundleReleaseAar with react-native version 0.64.0

### ISSUE THREAD

**Issue by khoaluu2021** [notifee/react-native-notifee#295]
Hi all,
I got this issue after upgrade to react-native 0.64.0
I'm using "@notifee/react-native": "^1.6.0"
I try to run the task :notifee_react-native:bundleReleaseAar' and got that fail too

`Execution failed for task ':notifee_react-native:bundleReleaseAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :notifee_react-native project caused this error: `

Do you have any suggestion?

**Comment by mikehardy** [comment]
Hi there! This is a known issue -

Priors: https://github.com/notifee/react-native-notifee/issues?q=is%3Aissue+bundleReleaseAar

Solution discovery https://github.com/notifee/react-native-notifee/issues/68#issuecomment-682117223

Documentation addition https://notifee.app/react-native/docs/environment-support#additional-requirements

> Use `./gradlew :app:assembleRelease`

We're tracking the complete solution (not yet implemented) here if you want to follow https://github.com/notifee/documentation/issues/8#issuecomment-790820950
