### ISSUE TITLE
Is the license a once-off cost?

### ISSUE THREAD

**Issue by pjivers-bom** [notifee/react-native-notifee#296]
Is the pricing a once-off payment or per app? It doesn't seem clear to me.

**Comment by mikehardy** [comment]
I suppose the documentation or wording could be made more clear this comes up a surprising amount.

> Lifetime Updates Included
> Lifetime access to any product updates.

This is intended to indicate that yes, it is a one-time perpetual license, with future updates included.
It is a paid product of course but the intention with that licensing scheme is to be as uncomplicated as possible.

Hope this helps! Cheers

**Comment by pjivers-bom** [comment]
Thanks @mikehardy. That clears it up. :)
