### ISSUE TITLE
Build Issue: Cannot find symbol .cancelAllNotifictions (mistyped?)

### ISSUE THREAD

**Issue by tad3j** [notifee/react-native-notifee#3]
I've created my project off of [@react-native-firebase/template](https://invertase.io/oss/react-native-firebase/quick-start/new-project) and I've installed notifee with `yarn add @notifee/react-native` (running this on Windows, Node v12.14.1, react-native v0.61.5). 

When I run `react-native run-android` the build fails with exception:
```
Execution failed for task ':@notifee_react-native:compileDebugJavaWithJavac'.

....

...\node_modules\@notifee\react-native\android\src\main\java\io\invertase\notifee\NotifeeApiModule.java:45: error: cannot find symbol
      .cancelAllNotifictions((e, aVoid) -> NotifeeReactUtils.promiseResolver(promise, e));
      ^
  symbol:   method cancelAllNotifictions((e,aVoid)-[...]e, e))
  location: class Notifee
```

It seems like there is a typo in `cancelAllNotifictions`, should be cancelAllNotific**A**tions.

**Comment by Salakar** [comment]
Thank you for flagging - 0.0.3 is up on NPM now with this fixed.
