### ISSUE TITLE
[Android] Notification isn't displayed in full-screen mode

### ISSUE THREAD

**Issue by MitinDmytro** [notifee/react-native-notifee#305]
Hello everyone!
I have difficulties with full-screen mode notifications on my android 11 (Model: Samsung A51).
I used a sample from documentation.

Steps to reproduce:
**index.js**
```
function CustomComponent() {
  return (
    <View>
      <Text>A custom component</Text>
    </View>
  );
}

AppRegistry.registerComponent('custom-component', () => CustomComponent);

// Display a notification
      await notifee.displayNotification({
        body: 'Full-screen notification',
        android: {
          channelId: 'default',
          category: AndroidCategory.CALL,
          importance: AndroidImportance.HIGH,
          fullScreenAction: {
                  id: 'default',
                  mainComponent: 'custom-component',
          },
        },
      });
```
#### `package.json`:
```json
"@notifee/react-native": "^1.7.0",
```

But I didn't see any full-screen notification.

![496acb92-ebab-4576-8e16-0ee3e57d4d7e](https://user-images.githubusercontent.com/59180806/118802283-9f360200-b8aa-11eb-8f3a-0b68c5c0cd3c.jpg)

**Comment by helenaford** [comment]
@MitinDmytro hey, are these flags on your activity in your `AndroidManifest.xml:`
```
  <activity
    ...
    android:showWhenLocked="true"
    android:turnScreenOn="true"
  />
```

**Comment by MitinDmytro** [comment]
I have tried to use react native component and set these flags to Main Activity.
It not works. 
Am I doing something wrong? 

**AndroidManifest.xml**
```
 <activity 
         android:name=".MainActivity"
         android:label="@string/app_name"
         android:screenOrientation="portrait"
         android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
         android:windowSoftInputMode="adjustResize"
         android:showWhenLocked="true"
         android:turnScreenOn="true">
            <intent-filter>
               <action android:name="android.intent.action.MAIN" />
               <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
      </activity>
```

**Comment by helenaford** [comment]
@MitinDmytro what are your channel settings, and are you putting the app in the background when the notification is delivered?

**Comment by MitinDmytro** [comment]
@helenaford, my application was in the background.

This is my android channel settings

**index.js**
```
notifee.createChannel({
  id: 'default',
  name: 'default',
  sound: "default",
  vibration: true,
  importance: AndroidImportance.DEFAULT
});
```

**Comment by helenaford** [comment]
Ah yeah, your channel needs to have importance set to HIGH. There's an example app about to be merged to master which demonstrates this. https://github.com/notifee/react-native-notifee/blob/27a1dccbe86c8fbcbafe6462d8ea53c991ad7291/example/src/utils/notifications.ts#L22

**Comment by helenaford** [comment]
@MitinDmytro example app has been merged, hopefully, that can help. There's also a video of how to make the notification display full-screen.

https://github.com/notifee/react-native-notifee/tree/master/example
