### ISSUE TITLE
How do you check that a licence is valid ?

### ISSUE THREAD

**Issue by maximerenaud7** [notifee/react-native-notifee#306]
Hello,
We would like to know how do you check that the licence is a valid one ?
We have to put the licence in an environment variable and we want to know if it's a sensitive information.
Thanks :)

**Comment by helenaford** [comment]
Hey 👋 Thanks for the question.

There are some debugging notes in the [docs](https://notifee.app/react-native/docs/license-keys#debugging), Let me know if that resolves you're question around checking if it's valid.

On the note about the license key is sensitive, someone else had the same concern [here](https://github.com/notifee/react-native-notifee/issues/284). Hope that answers your question.
