### ISSUE TITLE
How to add press action on notification to open the file.

### ISSUE THREAD

**Issue by shubhamdeol** [notifee/react-native-notifee#308]
I want to show local notification on successful file download. 

Here is how I am trying 

```js
const contentUri = await FileSystem.getContentUriAsync(filePath);

const notificationId = await notifee.displayNotification({
    title: 'Excel Report',
    body: 'File Successfully downloaded',
    android: {
      channelId: NotificationChannelNames.DownloadProgress,
      pressAction: {
        id: 'default',
        launchActivity: contentUri,
      },
    },
  });
```

What is correct way to pass an intent which opens file in mobile.

**Comment by shubhamdeol** [comment]
One way can be to send pressAction id as 
```
 pressAction: {
        id: 'download',
      },
```

and inside app listeners.

In press event handle it like
```js
if (detail.notification?.android?.pressAction?.id === 'download') {
  FileSystem.getContentUriAsync(uri).then((cUri) => {
    console.log(cUri);
    IntentLauncher.startActivityAsync('android.intent.action.VIEW', {
      data: cUri,
      flags: 1,
    });
  });
}
```

This required me to save fileUri in AsyncStorage and clear async on press action action. More better way could be if I could pass the intent from the place I am creating the notificaiton.

**Comment by helenaford** [comment]
Hey, this is an interesting use case! At the moment we only support launching a react activity. I'm not sure if it's possible but it could be something we look into.

**Comment by helenaford** [comment]
Closing as it's not something on the roadmap as there's no clear solution right now.
