### ISSUE TITLE
"TypeError: this.native.cancelDisplayedNotifications is not a function" when using jest mock

### ISSUE THREAD

**Issue by mars-lan** [notifee/react-native-notifee#310]
When using the jest mock suggestion in https://github.com/notifee/react-native-notifee#jest-testing, I still ended up getting this error.

**Comment by mikehardy** [comment]
The mock itself is likely out of date and does not define it - indeed I just looked - you are at this moment in there with #309 probably easiest thing - specifically because you'll be testing it right now and will *know* it works for you is to post a quick PR that stubs that function as well

**Comment by helenaford** [comment]
Fixed merged into master in #318, will be out in the next release.

**Comment by helenaford** [comment]
thanks for your help @mars-lan with this, the jest-mock.js has been updated and included in the latest release 1.8.1.
