### ISSUE TITLE
When Phone is locked and clicked on action button lock is not opened before navigating to application

### ISSUE THREAD

**Issue by vandana87** [notifee/react-native-notifee#322]
When notification received on lock screen and If I click on notification action button ,the app gets opened but still lock screen is not disappeared . we need to manually open the screen to see that the on click on action button application is opened.

**Comment by mikehardy** [comment]
Hi there! There is very little information here that would lead us to reproduce this (versions of code+dependencies, version of platform - not even sure if this is ios or android much less what version), some idea of how you are opening the notification.

In my experience on android at least if you interact with a notification on the lock screen the interaction happens but no, the phone is not unlocked. Why would it unlock? No authentication has happened.

**Comment by helenaford** [comment]
you could try the full-screen action, which will open the app up even if the device is locked but it automatically is shown not when the user clicks the notification. Or maybe you could listen to it when the user clicks on the notification, and display another as a full-screen action. Both are workarounds to your issue but other than that it's not possible to bypass someone's lock screen.

**Comment by helenaford** [comment]
Closing this for now, please re-open with more information - possibly sample code and screenshots/video of the issue.
