### ISSUE TITLE
How to override ios push permission settings

### ISSUE THREAD

**Issue by aklevko** [notifee/react-native-notifee#325]
I’m trying to override ios push permission settings for remote notifications. My app already has _authorizationStatus_ is **ENABLED** i.e. the user has accepted permission.
After that I tried to use _notifee.requestPermission({ sound: false })_ but it didn't work… 
notifee.getNotificationSettings() always returns sound with _status_ **1**

How to override already installed settings for ios? My goal is to enable/disable sound for push notification from one of my user settings screens inside the app.

**Comment by helenaford** [comment]
From what I understand about permissions, it's not possible to reset them. But, you could navigate the user to the settings screen and ask them to manually reset the sound, or store something in your app that remembers their preference.

So if user A wants sound disabled, don't set the sound when calling `displayNotification`, or if you need to know it for remote notifications, store their preference remotely in your database. 

Hope that answers your question.
