### ISSUE TITLE
Scheduled local notification were not fired when app is force closed

### ISSUE THREAD

**Issue by ericta** [notifee/react-native-notifee#335]
- I tried the example app from my Android device(One Plus), I schedule a notification by next 5 mins base on local timezone. Then I force close the app, and the notification never came. I don't know if the library is covering this case?
Thanks sir!

**Comment by helenaford** [comment]
Hey, I see you closed this. Did you manage to get the notifications to come through?

**Comment by SamiChab** [comment]
@ericta I'm facing the same issue. How have you solved this ?

**Comment by helenaford** [comment]
@ericta @SamiChab have you tried using setting the notifications with the alarm manager, it's a recent addition but so far we've heard great things. 

E.G. (example [here]( https://github.com/notifee/react-native-notifee/blob/bb70c8f52561623d264c282b523c9d58d766b498/example/src/utils/triggers.ts#L31)):

{
   timestamp: date,
   type: TriggerType.TIMESTAMP,
   alarmManager: {
     allowWhileIdle: true
   }
 }

Also, please check out this thread (https://github.com/notifee/react-native-notifee/issues/126#issuecomment-858900623).
