### ISSUE TITLE
Cannot find getDeliveredNotifications in Notifee v1.10.0

### ISSUE THREAD

**Issue by VivienTournie** [notifee/react-native-notifee#348]
Hello !

I've been able to find all the new APIs included in v1.10.0 except getDeliveredNotifications. Neither in the code nor in the Notifee's documentation.

Can we expect to get it the next release ? I would like to try to see if I can use it for my use case on iOS.

I'm assuming this is an implementation of [ this method ](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649520-getdeliverednotifications?changes=latest_minor) , so we have still no way to detect when a trigger notification is delivered (as we can do on Android with the DELIVERED event) ? 😞

**Comment by helenaford** [comment]
Hey there, there was a typo in the docs -  You should be able to use `getDisplayedNotificaitons`.
