### ISSUE TITLE
Push Notification sent through firebase do not trigger in foreground in Android release build

### ISSUE THREAD

**Issue by vtn-dev-sameer** [notifee/react-native-notifee#35]
Hi, This code is working fine when tested on debug build. But on the release build local push notification generated by notifee not working.

Here is my package.json :
     "@notifee/react-native": "^0.4.0",
    "@react-native-firebase/analytics": "6.4.1-alpha.0",
    "@react-native-firebase/app": "6.4.1-alpha.0",
    "@react-native-firebase/auth": "6.4.1-alpha.0",
    "@react-native-firebase/crashlytics": "6.4.1-alpha.0",
    "@react-native-firebase/dynamic-links": "6.4.1-alpha.0",
    "@react-native-firebase/iid": "6.4.1-alpha.0",
    "@react-native-firebase/messaging": "6.4.1-alpha.0",

Code used to trigger local notification:

async unsubscribe() {
    firebase.messaging().onMessage(async remoteMessage => {
      try {
        const channelId = await notifee.createChannel({
          id: "default",
          name: "Default Channel"
        });
        // Display a notification
        await notifee.displayNotification({
          title: remoteMessage.notification.title,
          body: remoteMessage.notification.body,
          ios: {
            importance: Importance.HIGH
          },
          android: {
            channelId
          }
        });
      } catch (e) {
        console.log(e);
      }
    });

**Comment by Ehesp** [comment]
Have you added the license? See [here](https://notifee.app/react-native/docs/license-keys). The bundle ID needs to match up.

**Comment by Eralyne** [comment]
I actually have this same issue. Works perfectly on emulator but doesn't show any foreground notifications on release. I have the licenses added with bundle ids matching. 

I'm still haven't properly gone through and debugged this so I don't have any other info at this moment.

**Comment by helenaford** [comment]
Closing this as it seems to be resolved but please reopen if it's still causing an issue.
