### ISSUE TITLE
Android custom sound not found with extension (`sound.mp3`) is found with no extension (`sound`)

### ISSUE THREAD

**Issue by mikehardy** [notifee/react-native-notifee#350]
Found the root cause of sound not playing. Previously the custom sound should include the file extension as shown in the [doc](https://notifee.app/react-native/docs/android/behaviour#custom-sound), e.g. `custom_sound.mp3`. Starting 1.10.0 the extension shouldn't be included, e.g. `custom_sound`. Please update the documentation & releate note to reflect that.

_Originally posted by @mars-lan in https://github.com/notifee/react-native-notifee/issues/341#issuecomment-890600319_

**Comment by helenaford** [comment]
Fixed docs to reflect changes and also to mark the release as a breaking change - updates will be live on the website shortly https://github.com/notifee/documentation/commit/9f7a10b93ff2bc56f558164ac221b366575143f8

**Comment by mars-lan** [comment]
I wonder if we can do the same for iOS (i.e. without the file extension) for consistency?

**Comment by mikehardy** [comment]
Yes - sorry I didn't have time to investigate this myself, but @helenaford I was thinking this was more an unintentional regression and not using the extension is bad practice since extensions are really just a convention and the full file name should  be used, apart from the idea that iOS should behave the same.

I was hoping to have time to actually post a fix for this so it used the whole file name (again?) + behaved the same as iOS
