### ISSUE TITLE
[iOS] Help troubleshooting with the service extension?

### ISSUE THREAD

**Issue by bperlman** [notifee/react-native-notifee#351]
Hello! 

Just getting started with a new Notifee license, so far so good. However, I seem to be stuck on getting the Notification Service Extension to work. I've followed the guide in the documentation [here](https://notifee.app/react-native/docs/ios/remote-notification-support) but it doesn't seem to be firing when a notification comes in.

I have tried the suggestion referenced at https://github.com/notifee/react-native-notifee/issues/287#issuecomment-825658731 and can confirm that the title is not being modified.

Is there any kind of troubleshooting documentation or example of this that might be available anywhere so I can try to figure out where I've gone wrong? Not really even sure where to start with that one as I'm not much of an iOS native developer.

Thanks!

**Comment by helenaford** [comment]
@bperlman thanks for your question, I see you've just closed it.  Did you manage to resolve the issue? We appreciate any feedback, if there's anything we can make clearer on the docs, please let us know.

**Comment by bperlman** [comment]
Was a stupid mistake on my part :) was sending a data-only notification with FCM so it wasn't triggering. I still haven't got it working properly so I'll likely be reaching out again but, at least I know the Service Extension is firing! Thanks for checking in!

**Comment by helenaford** [comment]
@bperlman ah nice, no problem at all, glad you got further. And, please do. Anything we can do to make it easier or help, don't hesitate to reach out again :)
