### ISSUE TITLE
Installation alongside react-native-firebase - android_background_activity_names needed?

### ISSUE THREAD

**Issue by liamjones** [notifee/react-native-notifee#366]
I think the answer to this one is no but just to check - if we have Notifee and react-native-firebase in the same app, we don't need to set any `android_background_activity_names` in rn-firebase for Notifee specifically, right?

https://rnfirebase.io/app/json-config#android_background_activity_names

**Comment by mikehardy** [comment]
Hi there! That's a maybe. It's for brownfield /mixed native + react-native apps that may have a few activities, and some of them should not be considered for foreground status. It's a pretty rare case I think
