### ISSUE TITLE
Error: Notifee native module not found.

### ISSUE THREAD

**Issue by AyoubMoustahfid** [notifee/react-native-notifee#375]
I installed the package, but when I want to run the application it shows me this problem "" Error: Notifee native module not found. "", please give me a solution to this problem

![image](https://user-images.githubusercontent.com/47373251/131524885-ae172c1d-ddf8-4905-b4e6-bcd670d326dc.png)

**Comment by AyoubMoustahfid** [comment]
Error: Notifee native module not found

**Comment by mikehardy** [comment]
Hi there!
You have not installed the package correctly / completely.
This is a common issue with react-native native modules (like Notifee) and not really a notifee bug, it's a problem with your process.
You have not included any version information or platform so I'm not certain what the solution is and will close this as lacking information, but it probably involves remembering to do `pod install`

Here's an example script that shows the complete integration steps required along with a few extras (all with comments) in case it helps

https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh

**Comment by AyoubMoustahfid** [comment]
Hi there!
I used these steps but same problem
[image: image.png]

>

**Comment by helenaford** [comment]
@AyoubMoustahfid `notifee` does not work for expo apps that aren't ejected, unfortunately. Hope that helps

**Comment by AyoubMoustahfid** [comment]
Ok, thanks for the clarification.

Le mar. 31 août 2021 à 16:38, Helena Ford ***@***.***> a
écrit :

**Comment by helenaford** [comment]
no problem, sorry for the inconvenience. I'm looking at how we can add a note somewhere in the docs.

**Comment by AyoubMoustahfid** [comment]
No problem, thanks!

Le mar. 31 août 2021 à 17:11, Helena Ford ***@***.***> a
écrit :

**Comment by AyoubMoustahfid** [comment]
Hello
Will the package be suitable for expo ??

**Comment by mikehardy** [comment]
We've seen the config plugins effort and a community member contributed an implementation of same for react-native-firebase (also an Invertase effort) so it's possible, but you're the first and only to ask, so it hasn't been a priority so far. Perhaps with react-native-firebase having that capability it makes more sense at this point, since they work together. Not sure how you would handle the notification service extension, which is pretty important though. It may never be truly practical.

**Comment by AyoubMoustahfid** [comment]
Ok thanks you


Le jeu. 2 sept. 2021 à 14:43, Mike Hardy ***@***.***> a
écrit :

**Comment by AyoubMoustahfid** [comment]
Hello
Is the package programmed to expo cli

**Comment by mikehardy** [comment]
No it is not configured to use expo in any way, I believe you must eject from expo to use it.
