### ISSUE TITLE
Website "My account" - cannot change user role

### ISSUE THREAD

**Issue by liamjones** [notifee/react-native-notifee#379]
I hope this is the right project to report this on?

There's someone in our account who I am trying to change from 'Admin' to 'User'. It says 'Updating...' but never completes. JS console says:

` Uncaught (in promise) You have specified an invalid role, role must be one of "10,5".`

And the PATCH payload shows:

`{"role":null}`

I _think_ there might be a second bug too but I invited the user over a week ago so maybe I'm remembering incorrectly:

I thought I invited the user with role 'User' initially but they've ended up as an 'Admin' (which is why I was trying to change their role). Is this something you can test easily? I don't have another user I need to invite right now.

**Comment by mikehardy** [comment]
Hey - not sure what's going on or why but commenting to let you know I/we've got :eyes: on this, thanks for raising it. Will try to find root cause

**Comment by Salakar** [comment]
Thanks for the report @liamjones - @mikehardy just pinged this over to me; could you give me the team id and the user who's role you're trying to lower and I'll manually update it for you whilst this bug is looked into

**Comment by liamjones** [comment]
Thanks @Salakar, team ID is `HNzY0xx2XMWHeU6YQV70` and the user is dorisaward.

**Comment by liamjones** [comment]
@Salakar would you also be able to confirm that the outstanding invites on that team are for the User role when they're accepted? They should all be.

**Comment by Salakar** [comment]
Fix was quicker than I thought it'd be so deployed a fix - you should be able to set the role now yourself - please try it out.

> @Salakar would you also be able to confirm that the outstanding invites on that team are for the User role when they're accepted? They should all be.

I've also deployed an update to the invites list - it now states the role the user was invited with. Hope it helps.

Mike

**Comment by liamjones** [comment]
> you should be able to set the role now yourself - please try it out

That's working for me now.

> I've also deployed an update to the invites list - it now states the role the user was invited with.

Awesome!

Thanks very much for the quick fix!
