### ISSUE TITLE
Foreground notification not working in android build release

### ISSUE THREAD

**Issue by programmer-RN** [notifee/react-native-notifee#40]
Hi, I'm facing issue of failed to display foreground notification in android build release, background is working.Now I'm using notifee.displayNotification to display notification received. 
Hope someone can help me, because I have been stuck in this problem many days

"@react-native-firebase/app": "^6.4.0",
"@react-native-firebase/crashlytics": "^6.4.0",
"@react-native-firebase/messaging": "^6.4.0",

notifee.displayNotification({
  title: title,
  body: body,
  android: {
    channelId: 'Default',
    asForegroundService: true,
    style: { type: AndroidStyle.BIGPICTURE, picture: android.imageUrl},
  },
})

**Comment by Ehesp** [comment]
Hello, have you added the license key? Check the native logs too when calling the display method too.
