### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by pyeonjaesik** [notifee/react-native-notifee#41]
When I  write "pod install".
I just get the following error.

[!] CocoaPods could not find compatible versions for pod "RNNotifee":
  In Podfile:
    RNNotifee (from `../node_modules/@notifee/react-native`)

Specs satisfying the `RNNotifee (from `../node_modules/@notifee/react-native`)` dependency were found, but they required a higher minimum deployment target.

**Comment by Ehesp** [comment]
Could you show the entire Podfile please?

**Comment by romainmarchand** [comment]
Hi, I think I also encountered this error when installing Notifee for iOS. Notifee requires 10.0 as a minimal iOS Version:
https://notifee.app/react-native/docs/environment-support

For me, it was set to 9 and changing it to 10 made it work. Did you ensure you set version to 10.0 at the top of your podfile and in your XCode project ?

**Comment by sarpere** [comment]
I have the same error.

**Comment by Ehesp** [comment]
@sarpere: 

> Could you show the entire Podfile please?

**Comment by sarpere** [comment]
# use_frameworks!

platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'udentify' do
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  # pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

  target 'udentifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'udentify-tvOS' do
  # Pods for udentify-tvOS

  target 'udentify-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
  rnfirebase.build_configurations.each do |config|
    config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
  end
end

**Comment by Salakar** [comment]
> platform :ios, '9.0'

This needs to be `platform :ios, '10.0'` as @romainmarchand mentioned above
