### ISSUE TITLE
onForegroundEvent not fired

### ISSUE THREAD

**Issue by pyeonjaesik** [notifee/react-native-notifee#44]
Android
debug
onForegroundEvent not fired

          notifee.onForegroundEvent((type,detail)=>{
            alert('a')
            console.log('Nothing happen');
            console.log(type);
            console.log(detail)

          })

**Comment by Ehesp** [comment]
Please show it in some wider scope of code - does anything show up in console logs?

**Comment by pyeonjaesik** [comment]
No, Nothing happen. even console logs.

Following is my backend code.

            var FCM = require('fcm-node');
             var fcm = new FCM(config.serverKey);

                  var client_token=find_tk[0]._doc.tk
                  var push_data = {
                    to: client_token,
                    notification: {
                      title: myid,
                      body: text,
                      sound: "default",
                      icon: "fcm_push_icon"
                    },
                    priority: "high",
                    restricted_package_name: "com.yomencity.puppy",
                    data: {
                      id:myid,
                      img:my_img,
                      text,
                      type:'message'
                    }
                  };
                  fcm.send(push_data, function(err, response) {
                    if (err) {
                      console.log(err)
                      output.status=700;
                      return;
                    }
                    console.log('talk: push success')
                  }); 

And Following is my client code.

import notifee, { EventType } from '@notifee/react-native';
        <TouchableOpacity style={{width:100,height:100,backgroundColor:'green',position:'absolute',top:30,left:30}} onPress={()=>{
          notifee.onForegroundEvent((type,detail)=>{
            alert('a')
            console.log('Nothing happen');
            console.log(type);
            console.log(detail)

          })
          
        }}>

        </TouchableOpacity>

**Comment by pyeonjaesik** [comment]
that is all my code.

**Comment by Ehesp** [comment]
```
<TouchableOpacity onPress={()=>{
      notifee.onForegroundEvent((type,detail)=>{
        alert('a')
        console.log('Nothing happen');
        console.log(type);
        console.log(detail)

      })
      
    }}>

    </TouchableOpacity>
```

Are you pressing the button? That code within the `onPress` will only create a listener if the button is pressed - try putting it within a components `useEffect` instead.

**Comment by pyeonjaesik** [comment]
Are you pressing the button? - Yes, of course.

But I changed my code as you advise. 

constructor(){
              useEffect(() => {
                return notifee.onForegroundEvent(({ type, detail }) => {
                  switch (type){
                    case EventType.DISMISSED:
                      console.log('User dismissed notification', detail.notification);
                      break;
                    case EventType.PRESS:
                      console.log('User pressed notification', detail.notification);
                      break;
                    }
                });
              }, []);
}
 But I got the following error.

invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.

**Comment by Ehesp** [comment]
Yes, in that case it would be `componentDidMount`.

Also looking at the above, you're sending a payload from a server, but Notifee is local notifications only. If you want to receive remote messages you need to connect with FCM - see these docs: https://notifee.app/react-native/docs/integrations/fcm

You can test whether the foreground event is working though using `displayNotification` from Notifee.

**Comment by pyeonjaesik** [comment]
Thnaks.
But.. what does it means.  -- "local notifications only."?

**Comment by Ehesp** [comment]
Remote: A message is sent to the device from an external service (e.g. FCM, APNs). FCM supports displaying basic notifications automatically if the message payload contains certain values.

Local: The device creates and shows the notification (in the case of Notifee, with `displayNotification`). This allows you to create rich notifications with better interaction and handling than in possible via remote ones.

You can combine remote messages to create local notifications if you follow the guide I linked above.
