### ISSUE TITLE
Feature request: FullScreenIntent (Android)

### ISSUE THREAD

**Issue by ochrstn** [notifee/react-native-notifee#45]
For an incoming (video) call I would like to present an high priority notification with an FullScreenIntent like in this example: https://developer.android.com/training/notify-user/time-sensitive#create-high-priority-notification

I haven't found anything about this in the notifee documentation.

Is it planned to implement this feature?

**Comment by Salakar** [comment]
This is almost possible; the Android example you linked above translates into the following on our API:

```ts
import notifee, {
  AndroidCategory,
  Importance,
} from '@notifee/react-native';

await notifee.displayNotification({
  title: 'Incoming Call',
  body: '(919) 555-1234',
  android: {
    category: AndroidCategory.CALL,
    importance: Importance.HIGH,
    pressAction: {
      id: 'default',
      // fullscreen: true,
    },
  },
});
```

The only bit missing currently is fullscreen support - we did have it on the original alpha but it needed a bit more work doing to it, so we removed it to look at it in a later release.

**Comment by ochrstn** [comment]
> This is almost possible; the Android example you linked above translates into the following on our API:
> 
> ```ts
> import notifee, {
>   AndroidCategory,
>   Importance,
> } from '@notifee/react-native';
> 
> await notifee.displayNotification({
>   title: 'Incoming Call',
>   body: '(919) 555-1234',
>   android: {
>     category: AndroidCategory.CALL,
>     importance: Importance.HIGH,
>     pressAction: {
>       id: 'default',
>       // fullscreen: true,
>     },
>   },
> });
> ```
> 
> The only bit missing currently is fullscreen support - we did have it on the original alpha but it needed a bit more work doing to it, so we removed it to look at it in a later release.

Thanks for your response. Looking forward for the missing bit 👍

**Comment by joelso** [comment]
This is super interesting for us, is there a ETA for when full screen intents will be supported?

**Comment by whenmoon** [comment]
I will use this as soon as it's available! :)

**Comment by helenaford** [comment]
Feature support added in the latest release (1.4.0). Please view the [Full-screen Action docs](https://notifee.app/react-native/docs/android/behaviour#full-screen) to learn more.
