### ISSUE TITLE
Using summaryArguments in iOS displayNotification causes notifications not to appear

### ISSUE THREAD

**Issue by Eralyne** [notifee/react-native-notifee#47]
Whenever I use summaryArgument and summaryArgumentCount (I have not attempted with just one defined but since summaryArgumentCount defaults whereas summaryArgument does not, I assume summaryArgument is the issue.), displayNotification does not show any notifications in neither background nor foreground.

For a reference of my code, I followed the FCM intergration guide to a T, meaning both onMessage and setBackgroundMessageHandler both direct to a function listed as onMessageReceived that goes through message types and displays notifications based on the types as well as different variables. This code is located in my index.js file.

Some direct reference of my code below is an example of the issue iOS category and the code that had the problem directly. As far as I know, nothing outside of what I listed interacts with the segment of execution.

```Javascript
   await notifee.setNotificationCategories([
    {
      id: 'newConversation',
    },
    {
      id: 'message',
      summaryFormat: 'You have %u+ unread messages from %@.',
      actions: [{
        id: 'reply',
        title: 'Reply',
        input: true,
      }]
    }
```

```Javascript
        notifee.displayNotification({
          title: message.data.userName,
          body: message.data.messageText,
          data: message.data,
          android: {
            channelId: 'message',
            timestamp: Date.now(),
            showTimestamp: true,
            largeIcon: message.data.avatar ? message.data.avatar : '' // I use a direct link here as placeholder because local image throws an error, I omitted the link. I created a separate issue for this
          },
          ios: {
            categoryId: 'message',
            importance: Importance.DEFAULT,
            summaryArgument: message.data.userName,
            summaryArgumentCount: 3
          }
        })
```

With summaryArgument and summaryArgumentCount commented out, the notifications display properly in both background and foreground. It's only when I bring them in that they do not work.

**Comment by Ehesp** [comment]
Hey, thanks for the details. Could you let us know what device and ios version you're using?

**Comment by Eralyne** [comment]
I am using an iPhone 6 on version 12.4.4

**Comment by helenaford** [comment]
Hi, thanks for providing the version details. Are you still experience the issue? I tried to replicate the issue with iPhone 6 12.4 (simulator). If you have any log output, can paste here? Maybe ensure that summaryArgument is set to a string. If it's not, Notifee will throw a validation error.

**Comment by Eralyne** [comment]
I have not tested it since I posted as I preferred just it not crashing. I will try to see if I can replicate it again and get as much information as possible.

**Comment by helenaford** [comment]
Closing this. @Eralyne please feel free to open if you're not able to get `summaryArguments` to work.
