### ISSUE TITLE
Chronometer event

### ISSUE THREAD

**Issue by diegoavidal** [notifee/react-native-notifee#49]
Hi, 
I'm try to make a notification with a countdown, for that I used the follow configuration:
     {
      timestamp: Date.now() + 300000 ,
      showChronometer: true,
      chronometerDirection: 'down'
}
the chronometer, works well, but I don't have any event to make possible close the notification, or stop chronometer when the chronometre reaches 0. and if i try use a setTimeout doesn't work in background

do you have any solution or idea to solve that? 

thanks

**Comment by diegoavidal** [comment]
Sorry for the issue, 
I already found this parameter: 
https://notifee.app/react-native/reference/notificationandroid#timeoutafter

thanks

**Comment by Ehesp** [comment]
No problem!
