### ISSUE TITLE
There is no pop up notification in foreground on Android

### ISSUE THREAD

**Issue by motogod** [notifee/react-native-notifee#50]
Just use the sample code and send the notification from Firebase console. It work, but there is no pop up on Android.

Version:
```
  "dependencies": {
    "@notifee/react-native": "^0.4.0",
    "@react-native-firebase/app": "^6.7.1",
    "@react-native-firebase/messaging": "^6.7.1",
    "react": "16.8.6",
    "react-native": "0.60.5"
  },
```

Sample code:

```
    // Create a channel 
      const channelId = await notifee.createChannel({
        id: 'default',
        name: 'Default Channel',
      });
      
      await notifee.displayNotification({
        title: title,
        body: body,
        android: {
          channelId,
        },
      });
    });

```
I can get the notification on status bar. But there is no pop up notification like IOS.

I suppose I have a notification dialog on the red zone.
<img width="358" alt="截圖 2020-05-04 下午3 37 24" src="https://user-images.githubusercontent.com/17781603/80945351-36562600-8e1e-11ea-8709-d3996fc6f934.png">

Do I miss some steps or I have to use some libraries to achieve it ?

**Comment by Ehesp** [comment]
Hi - have you read: https://notifee.app/react-native/docs/android/appearance#high

**Comment by motogod** [comment]
Thanks for help, I miss the part !

It's not the problem now, thanks !

**Comment by JulioOrellana** [comment]
I am having the same issue. 

Using importance hight but pop up still not showing

```js
"dependencies": {
    "@notifee/react-native": "^0.5.1",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-error-boundary": "^1.1.0"
  },

const onDisplayNotification = async () => {
  // Create a channel
  const channelId = await notifee.createChannel({
    id: 'default',
    name: 'Default Channel',
    importance: Importance.HIGH,
    badge: true,
    visibility: AndroidVisibility.PUBLIC,
  });

  // Display a notification
  await notifee.displayNotification({
    title: 'Notification Title',
    body: 'Main body content of the notification',
    android: {
      channelId,
      importance: Importance.HIGH,
      visibility: AndroidVisibility.PUBLIC,
    },
  });
};
```

I can't make it work

**Comment by motogod** [comment]
@JulioOrellana 

Here is my code:

      ```
// Create a channel , id  name must be important and then show the Android  dialog
      const channelId = await notifee.createChannel({
        id: 'important',
        name: 'Important Notifications',
        importance: Importance.HIGH,
        badge: true,
      });
      // 增加 pressAction 才能支援通知欄位的點擊事件
      await notifee.displayNotification({
        title: title,
        body: body,
        data,
        android: {
          channelId,
          pressAction: {
            launchActivity: "default",
            id: "default",
          },
        },
        importance: Importance.HIGH,
        badgeIconType: AndroidBadgeIconType.SMALL,
        ios: {
          importance: Importance.HIGH,
        },
      });
    });
```

In my comment, id and name must be important.
Hope it can help.

**Comment by Ehesp** [comment]
Can you show a screenshot of the channel on the actual device app notification settings?

**Comment by JulioOrellana** [comment]
You mean this? 

![9124efde-f8d6-4afb-9db7-cb6aa2ddf5ef](https://user-images.githubusercontent.com/10372340/83773306-5ca3f700-a652-11ea-9c7b-174e1030217c.jpeg)

**Comment by Ehesp** [comment]
Yeah, what's inside of the Default Channel settings?

**Comment by JulioOrellana** [comment]
@Ehesp thanks for your time

![default_channel](https://user-images.githubusercontent.com/10372340/83776021-ac37f200-a655-11ea-8bf8-81fef89df645.jpeg)
![channel_name](https://user-images.githubusercontent.com/10372340/83776030-b0640f80-a655-11ea-81cb-cf2cfd6253ea.jpeg)
