### ISSUE TITLE
default/custom sound is not working 

### ISSUE THREAD

**Issue by mdrajibsk8** [notifee/react-native-notifee#51]
I'm trying to set a custom notification sound to my app. I have an mp3 file that I'm trying to use as the sound.

I tried adding the mp3 file to the res/raw directory, and then passing the reference to the 

        // Create a channel 
        const channelId = await notifee.createChannel({
          id: 'Firabsev6',
          name: 'Firabsev6',
          sound: 'glass'
        });
    
        // Display a notification
        await notifee.displayNotification({
          title: 'Notification Title 3',
          body: 'Main body content of the notification',
          android: {
            channelId,
            sound: 'glass'
          },
        });

I tried to look for a guide in the documentation, but little was said about custom notifications sound.
Any idea on how to make this work?
And also default notification sound is not working as well ?

**Comment by Salakar** [comment]
Have you tried the full file name, e.g. `glass.mp3`?

**Comment by mdrajibsk8** [comment]
It's not working on Xiaomi devices...
I have checked on other devices, it's working fine.
But not in Xiaomi ... 
please help me with this

**Comment by netbull** [comment]
For me on iOS the custom sound also does not work..

I added reminder.caf file /converted from mp3 via afconvert tool/ in `Library/Sounds` and tried with or without file extension in notifee.displayNotification(...), but with no success. It always plays the default sound.

**Comment by netbull** [comment]
Oooh. I just did it... included the file extension as well and it works now!

**Comment by helenaford** [comment]
@mdrajibsk8 wha's the Android version on your Xiaomi device?

**Comment by helenaford** [comment]
Closing this as the docs cover the file extensions and more details on how to work with sounds in general since this issue was opened. Please don't hesitate to reopen if you're still having an issue.
