### ISSUE TITLE
Add Image to iOS notifications is already supported?

### ISSUE THREAD

**Issue by cxrod** [notifee/react-native-notifee#56]
Hi, I'm migrating to notifee but I don't see this featured in the docs!

Do you have a roadmap to know what features you are planning to release soon?

**Comment by Salakar** [comment]
Hey, this is coming soon, it's listed here on the roadmap: https://github.com/notifee/react-native-notifee/issues/1#issuecomment-625808121

**Comment by cxrod** [comment]
@Salakar Thanks for the answer

**Comment by yotam-nots** [comment]
Hi @Salakar, can you share a rough timeline for this feature / v1?
