### ISSUE TITLE
Require cycles are allowed, but can result in uninitialized values.

### ISSUE THREAD

**Issue by admin2684** [notifee/react-native-notifee#57]
Hi there 
I using from react-native-notifee but when run my project I face some warning:

"Require cycles are allowed, but can result in uninitialized values."

![Screen Shot 2020-05-15 at 1 49 52 PM](https://user-images.githubusercontent.com/52445871/82043797-dfb9d900-96b4-11ea-8aaa-d9b63d29197d.png)

**Comment by Salakar** [comment]
Hello - these warnings are coming from your project and not from Notifee. Thanks
