### ISSUE TITLE
Which features do react-native-notifee have that react-native-firebase/messaging v7 doesn't?

### ISSUE THREAD

**Issue by roni-castro** [notifee/react-native-notifee#63]
Sorry if this is the wrong place, but I am very confused about the versions of `react-native-firebase/react-native-notifee` which works or not with push notifications. 
On this [thread](https://github.com/invertase/react-native-firebase/issues/2566) it says that v6 does not support firebase notifications, but now on v7 it has docs and have this [feature](https://github.com/invertase/react-native-firebase/tree/master/packages/messaging) back again. On the other side you have created a new paid lib (`react-native-notifee`) that apparently does the exact same thing that react-native-firebase v7 does at this moment, with some lack of some features (does not allow to integrate with any 3rd party messaging services), so my questions ares:
*  What are the differences between the lib `react-native-firebase` v5, v7 and `react-native-notifee`?

* Can I still use the `react-native-firebase` v7 on production to receive push notification on both Android/iOS platform? 

* Can I migrate `react-native-firebase` v7 to `react-native-notifee` on the future when it leaves the alpha phase?

**Comment by mikehardy** [comment]
I think if you re-read very carefully, but with the idea that "notifications" and "messaging" are entirely different things, it will make sense.

"messaging" == "firebase cloud messaging" == most people say "push notifications" although that's confusing. These are packets of JSON going between the cloud and your device.

"notifications" == OS-specific / Device-specific local notifications (or alerts, or popup notifications etc, as some call them). These are visible / audible things you actually see and hear on the device.

**Comment by mikehardy** [comment]
For the avoidance of doubt:

Messaging -> react-native-firebase
Notifications -> Notifee, or some other library that displays / handles local notifications

**Comment by roni-castro** [comment]
> For the avoidance of doubt:
> 
> Messaging -> react-native-firebase
> Notifications -> Notifee, or some other library that displays / handles local notifications

Thanks @mikehardy, now I think I understood the difference between these two libs. The `react-native-firebase/messaging` is necessary to be able to receive the push notification from Firebase (receives push notification when the app is in background/foreground for both Android/iOS platform), and the `react-native-notifee` is necessary to display the notification locally with some customization (change the icon, alert sound, priority, schedule notification, create channels on Android...). So my conclusion is that we will always need both libs if we need to construct our own notification as specified [here](https://notifee.app/react-native/docs/integrations/fcm#integrating-notifee) and commented [here](https://github.com/invertase/react-native-firebase/issues/3668), unless we use the deprecated v5

**Comment by mikehardy** [comment]
Indeed - sounds like you go it :-). 
And please note that the root problem is that it sounds so simple "just show a local notification", but in practice the APIs for this not-actually-simple thing are incredible in their number. And there are other libraries that attempted to cover them (like react-native-firebase v5) but covering them and testing them is a huge effort and in the end not sustainable. It's one of those things where people need to be paid if it's going to be a long-term, high-quality effort with support. And so Notifee exists.

Good luck with your project!
