### ISSUE TITLE
Incorrect iOS APNS Token

### ISSUE THREAD

**Issue by odesey** [notifee/react-native-notifee#66]
I am trying to implement this package (I purchased a license) along with `react-native-firebase`. After following all the steps in the documentation, I can receive notifications on Android and iOS using the Google FCM console. I can also get the device token for Android devices and receive sent notifications using AWS SNS.

I am having a problem with iOS and AWS SNS however. It appears that the token I am getting when I call `messaging().getAPNSToken()` is **NOT** correct.

I set the `FirebaseAppDelegateProxyEnabled` option to `NO` in my `Info.plist` file also, but the token appears to be incorrect.

When I register the token I get from my iOS device in SNS as an endpoint and publish a message to it, AWS disables it and generates the following failure message:

`"EventType":"DeliveryFailure","FailureMessage":"Platform token associated with the endpoint is not valid","FailureType":"InvalidPlatformToken"` 

I am trying the following code:

```javascript

messaging()
        .getToken()
        .then(token => {
          console.log('TOKEN: ', token); //gives me the FCM token...not good for iOS AWS SNS
        });

messaging()
            .getAPNSToken()
            .then(token => {
              console.log('iOS TOKEN: ', token.toLowerCase()); //if I dont make the token lowercase, I cannot register it as an endpoint in AWS. 
//Also this token is different than the FCM token but AWS SNS says it's not valid
            });
```

So the TLDR is, how can I get the correct iOS device token that will work with AWS SNS?

Also is the fact that the `getAPNSToken` needs to be converted to lowercase should be documented, took me quite a while to figure that out.

Thanks.

iOS 12 physical device (iPhone 6)
react native: **0.61.5**
notifee: **0.5.1**
react native fcm: **7.1.0**

**Comment by odesey** [comment]
Found the issue.

For anyone else with this problem, it was caused by AWS SNS using a production cert when it should have been using a development cert while testing.

Token worked fine in development.

**Comment by mikehardy** [comment]
Getting cloud messaging to work correctly is one of the hardest things I've ever done myself or watched people attempt in my 20+ years developing. It's *always* something...
