### ISSUE TITLE
Android 10 dark theme actions button style

### ISSUE THREAD

**Issue by gayanMadurapperuma** [notifee/react-native-notifee#78]
In the android 10 dark theme, the notification action button HTML style not working properly.
it's checked with an example of the given in official documentation. It's working fine in light theme.
https://notifee.app/react-native/docs/android/appearance

**Comment by Salakar** [comment]
Can you provide a screenshot of the issue?

Don't think there is much we can do here though, the html generation is built into android notifications, not something we have control over
