### ISSUE TITLE
Unable to build library as standalone project

### ISSUE THREAD

**Issue by SaeedZhiany** [notifee/react-native-notifee#8]
I wanted to open this library as a standalone project in IDE, so I tried to build the project on my PC, but I noticed some errors,

- `genversion` is not listed in `devDependencies` section to install automatically by `yarn install` or `npm install`.
- after installing it manually and run `npm install` I got this error that seems related to tsconfig file in the build phase.

```
> @notifee/react-native@0.0.6 prepare C:\Users\USER\Desktop\react-native-notifee
> npm run build


> @notifee/react-native@0.0.6 build C:\Users\USER\Desktop\react-native-notifee
> genversion --es6 --semi src/version.ts && tsc

tsconfig.json:12:5 - error TS5053: Option 'allowJs' cannot be specified with option 'declaration'.

12     "allowJs": true
       ~~~~~~~~~


tsconfig.json:17:6 - error TS5053: Option 'allowJs' cannot be specified with option 'declaration'.

17      "declaration": true,                   /* Generates corresponding '.d.ts' file. */
        ~~~~~~~~~~~~~


tsconfig.json:17:6 - error TS5053: Option 'declaration' cannot be specified with option 'isolatedModules'.

17      "declaration": true,                   /* Generates corresponding '.d.ts' file. */
        ~~~~~~~~~~~~~


tsconfig.json:26:5 - error TS5053: Option 'declaration' cannot be specified with option 'isolatedModules'.

26     "isolatedModules": true
```

**Comment by Salakar** [comment]
Hey, thanks for the report. We've not really tested it as a standalone repository, internally we actually run this in a lerna monorepo as a git submodule.

Will get this looked at though.

**Comment by Salakar** [comment]
Should all be fixed in latest commit, have moved eslint & prettier configs over too. Thanks
