### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.Importance.DEFAULT')

### ISSUE THREAD

**Issue by robertqin86** [notifee/react-native-notifee#84]
```
import notifee, { Importance } from "@notifee/react-native";

export const configureNotificationChannel = async () => {
  return await notifee.createChannel({
    id: "default",
    name: "Default Notifications",
    vibration: true,
    importance: Importance.DEFAULT,
  });
};
```
This is no longer working because it appears `Importance` is not longer exported. What is the correct variable to use to set a default channel importance? 

The documentation needs to be updated I think.

```
await notifee.createChannel({
  id: 'alarm',
  name: 'Firing alarms & timers',
  lights: false,
  vibration: true,
  importance: notifee.Importance.DEFAULT,
});
```

Notes: using ```@notifee/react-native: ^0.7.1```

**Comment by Salakar** [comment]
Sorry it's now `AndroidImportance`, docs will be updated this week

**Comment by Salakar** [comment]
Docs have now been updated, and this is also covered in the release notes: https://notifee.app/react-native/docs/release-notes#060

Thank you for reporting the issue
