### ISSUE TITLE
A way to contribute to the docs?

### ISSUE THREAD

**Issue by netbull** [notifee/react-native-notifee#85]
I faced an issue of understanding the custom sounds and I thought that I can contribute a little bit by improving the docs, but there is no repo for them.

Is there any option to do that?

**Comment by Salakar** [comment]
Hey @netbull - thanks for the interested in contributing to the docs - we're currently looking into moving the docs to Open Source, currently they're markdown files inside our internal mono-repo and things are currently heavily interlinked so I'm not sure when this will be done yet but it's on the todo :)

In the meantime if have any docs suggestions feel free to ping them here, thanks!

**Comment by Salakar** [comment]
Docs have now been open sourced: https://github.com/notifee/documentation

Thanks

**Comment by netbull** [comment]
That's great, thanks!
