### ISSUE TITLE
Could not get unknown property 'android' for project ':app' of type org.gradle.api.Project

### ISSUE THREAD

**Issue by vonovak** [notifee/react-native-notifee#88]
hello and thanks for the lib!

steps to reproduce

```
npx react-native init removeme --version 0.60.0
cd removeme
yarn add @notifee/react-native

echo "{
   "android": {
     "license": "XXXX.YYYY.ZZZZ"
   },
   "ios": {
     "license": "XXXX.YYYY.ZZZZ"
   }
 }" >> notifee.config.json

npx react-native run-android
```

output of build:

```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/vojta/_dev/removemee/node_modules/@notifee/react-native/android/notifee-json.gradle' line: 253

* What went wrong:
A problem occurred configuring project ':@notifee_react-native'.
> Could not get unknown property 'android' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
```

since RN 60 is supported, can this be fixed? Thanks!

**Comment by mikehardy** [comment]
Does it work with current (0.62.2)? Just curious, alternatively, does it work with 0.60.x if you update gradle to the gradle used on 0.62?

**Comment by vonovak** [comment]
> Does it work with current (0.62.2)

it does on a clean project, it's just this one project is not there 🙈 

I tried changing distributionUrl - `distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip` if that's what you're asking, but didn't work :/

If there's no other advice I guess I'll have to do the upgrade 😆

**Comment by Salakar** [comment]
Can you try locally patch this line: https://github.com/notifee/react-native-notifee/blob/master/android/notifee-json.gradle#L252

to:

```groovy
if (appProject && appProject.hasProperty('android')) {
```

Is weird though, do you perhaps have a non standard project/android setup?

**Comment by vonovak** [comment]
I'm getting `Notifee WARNING: Could not find your 'app' gradle project automatically, you may need to manually apply the notifee-json.gradle script.`

> Is weird though, do you perhaps have a non standard project structure/android setup?

yeah, I thought so too but I can reproduce even on a clean project ^

**Comment by Salakar** [comment]
How strange, seems to be working for most 😓 need to figure out how to repro locally

In the meantime, the warning means you can manually apply the script by adding the following to the bottom your `app/build.gradle`:

```
apply from: file('../../node_modules/@notifee/react-native/android/notifee-json.gradle')
```

**Comment by MamyChow** [comment]
Hi, juste let you know that i have the same problem, i am on react-native: 0.61.1, notifee: 0.9.1. (It's working with locally patch)

**Comment by lkwjohn** [comment]
just check is this fix gonna have a new release soon?
