### ISSUE TITLE
[Android] Small Icon on notifications does not work in release

### ISSUE THREAD

**Issue by Eralyne** [notifee/react-native-notifee#92]
Hey there, loving the library so far. Just have a little issue with the small icon notifications in release.

When I receive a notification on release build on Android, the icon is replaced with just a square that's the color defined by color. Here's a paste of example notification code below that can explain it better than my fairly confusing wording.

```Javascript
return notifee.displayNotification({
          title: Platform.OS === 'ios' ? message.data.userName : 
          `<p style="color: #9954BF;"><b>${message.data.userName}</span></p></b></p>`,
          subtitle: Platform.OS === 'ios' ? '' : 'messages',
          body: message.data.messageText,
          data: message.data,
          android: {
            channelId: 'message',
            timestamp: Date.now(),
            showTimestamp: true,
            smallIcon: 'ic_launcher_round', // This works properly on the emulator but doesn't on release
            largeIcon: message.data.avatar,
            pressAction: {
              launchActivity: 'default',
              id: 'default'
            },
            color: Colors.comelyPurple // The icon seems to be a square defined by this color, I just see this as my icon on release
          },
          ios: {
            categoryId: 'message',
            summaryArgument: message.data.userName,
            summaryArgumentCount: 3
          }
        })
```

I followed the outlined steps on the documentation about generating a small icon which is how I got mine. What I've seen for native applications relating to firebase messaging is that they also add meta-data to their manifest like so which resolves this issue:
```xml
<meta-data android:name="com.google.firebase.messaging.default_notification_icon"
          android:resource="@drawable/ic_launcher_round" />
```

Do I have to add something in my manifest as well or am I doing something else improperly?

Thank you

**Comment by Eralyne** [comment]
I'm going to test without the color property and see if that resolves the issue. Since my icon isn't white it might assume the replacement is needed everywhere.

**Comment by Eralyne** [comment]
My bad, I created and used the icons improperly.

**Comment by Eralyne** [comment]
Okay, so I'm going to reopen this because I was mistaken when I thought my usage of the icons was the cause of the problem. I'm still having the problem and I have no leads as to how to fix it.

When debugging and on an emulator, the icons for notifications work absolutely perfectly but when it comes to release, it just goes to this below: 
![20200629_005034](https://user-images.githubusercontent.com/7963271/85982197-06a14580-b9ab-11ea-9feb-409568dde5a4.png)

My notification code is as shown in my initial post. The thing is, this library isn't the only one that has this issue. The image above actually comes from another library (react-native-background-geolocation) but both seem to have the problem.

If I do not specify a `smallIcon` property, the icon replicates the app launch icon properly and works great but that's not the icon I'm looking for. 

Here's my android Manifest if it helps:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.comely.android">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.front" android:required="false" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:usesCleartextTraffic="true"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:windowSoftInputMode="adjustResize"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:screenOrientation="portrait"
      >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

My assets are generated through Android Studio 4.0 and are drawables.

I'm really having trouble with this issue and it's one of our last concerns prior to finishing it up and I would be really grateful for some help or at least a direction that I could follow to possibly figure it out.

**Comment by mikehardy** [comment]
Hi there :wave: - you have investigated this quite thoroughly, so this may be something you've already investigated, but just in case you haven't, have you investigated how resources are minimized when you do shrinking in release mode? I had a similar problem and learned that releases are pruned in a way I'd never thought was possible and many people might not think of - explanation and links here https://twitter.com/fastsquatch/status/1196475279688028160 - perhaps your resources are just being removed, leading to the symptoms you see?

**Comment by Eralyne** [comment]
Hmm, this could very well be it since I do have resource shrinking in release enabled and it is basically the only disparity between release and debug that could affect it.

Thank you, I'll take a look and see if this solves my issue.

**Comment by Eralyne** [comment]
It, unfortunately, didn't seem to have solved the problem.

**Comment by mikehardy** [comment]
I am sorry to hear that, I was hoping that hunch would lead somewhere. Well, it caused me to re-read the R8 resource shrinking stuff and maybe you learned some new stuff so not totally wasted time.

Sorry to say I have no other leads at the moment. I just re-confirmed that for me on a release build on android I see my miniature icon with my notifications but I am using the default launcher icon which I understand is not what you want.

@Salakar or @Ehesp  have you seen this in your projects or testing?

**Comment by Eralyne** [comment]
Thanks for the hunch. I'm going to keep reading into more about it to make sure I didn't miss anything.

**Comment by mikehardy** [comment]
You can open the APK in Android Studio for a good look at the resources included at least. That's how I confirmed I had retained my resources through the R8 process after learning resources were unexpectedly purged, for me clicking into the resources.arsc and then the mipmap part shows me what I expect (but similarly was missing things prior). Still might be a dead-end, but at least easy to inspect. Cheers

**Comment by Eralyne** [comment]
Oh wow, I didn't know I could do that (working with a bundle). This will definitely help figure it out. Right now it looks like the resource is there but is just a completely blank square. Let's see if I can figure out why it's like this.

I really appreciate all the help.

**Comment by Eralyne** [comment]
After messing with the keep.xml file a bit more, it finally works. Thanks for all your help, I would not have even thought of the compression being the problem. @mikehardy

**Comment by mikehardy** [comment]
Fantastic! Glad you got a positive result. I was similarly shocked when it bit me, one of those things where I see *why* it's doing what it's doing, and it's just shocking that purely by chance it works for most people without modification. Software is always out to get you it seems. Cheers

**Comment by puneetkansal04** [comment]
@Eralyne  @mikehardy I am facing the same issue and I am not able to resolve this. Can you tell me the exact steps you followed to resolve it.

**Comment by mikehardy** [comment]
All the info I used is in the link to my Twitter account posts above
