### ISSUE TITLE
[iOS, ?Android] notifications when the app is killed not displaying

### ISSUE THREAD

**Issue by netbull** [notifee/react-native-notifee#97]
There is something strange which I can't understand why is happening. When the app is killed the notifications are received without any issues, but if the app is killed for long time /can't tell how many minutes or hours/ the notifications are not displayed /again here I can't exactly say if the event is not triggered or the notificationDisplay does not work, because it's hard for me to debug it/.  If I open the app and then close/kill it then the notifications are displayed without any problem for I don't know what time until they stop again to work.

Any ideas what can cause such behaviour?

I'm using:
Notifee v0.8.0
React Native: 0.62.2

### Update
It looks like the time is about 15 minutes

**Comment by Ehesp** [comment]
Hello

Can you show some code? E.g. how are you triggering a background event etc?

**Comment by netbull** [comment]
I can't understand what the issue could be, because it's kind a random thing going on.. Yes I'm using FCM, and it could have a delay, but a send on 7 devices same FCM, the App version is the same on all devices, the permissions are given. On some devices the background event is not triggered or the notification is not displayed /i'm not sure which one/. After opening and killing the app on device which the background notifications worked they stopped to work.

The foreground notifications work on all devices.
After killing the app on all devices and waiting 10-15 min the background notifications stopped working on all of them.

The devices are 5 iPhones, 1 iPad, 1 Android tablet /the android tabled there is a bug that on the backgroundMessageHandler the channels are not created, so the notifications does not show, but it's fixed and will test after further later/.

NB: The FCM message is send as Data and the displaying is handled by Notifee

Here is the registering of the background listener.

file `index.js`
```js
import messaging from '@react-native-firebase/messaging';
...
messaging().setBackgroundMessageHandler(async remoteMessage => {
  await notifee.displayNotification({
    '_id': 'something',
    'type': ''something-else',
    'title': 'whatever',
    'body': 'body'
  });
});

function HeadlessCheck({isHeadless}) {
  if (isHeadless) {
    // App has been launched in the background by iOS, ignore
    return null;
  }

  return <App />;
}

AppRegistry.registerComponent(appName, () => HeadlessCheck);
```

**Comment by Ehesp** [comment]
If the background listener isn't triggering, I'd say that's an issue for the RNFB repo - there's a pretty big issue about iOS background events with various comments/solutions. Have you tried on Android?

**Comment by netbull** [comment]
I ended up sending Notification + Data and let the OS to display the message in background and Notifee to display the foreground notifications :/

Will post back the results after few days, but for now it is working good.
