### ISSUE TITLE
Error Build IOS NotifeeApiModule.h

### ISSUE THREAD

**Issue by naufanituharish** [notifee/react-native-notifee#99]
Error Build in NotifeeApiModule.h

<img width="911" alt="image" src="https://user-images.githubusercontent.com/32536762/86436253-1a8ed380-bd2c-11ea-8258-bf35cd656181.png">

**Comment by mikehardy** [comment]
Hi there! I've been compiling with Notifee integrated all day and have not seen a build error, though I'm working from the command line mostly. I am pretty sure I had it open in Xcode semi-recently though. Are you sure you did a pod install and followed all the install instructions? Did it ever build correctly for you and this is a new break, or are you just installing it now?

**Comment by naufanituharish** [comment]
Ya,, I did do follow the installation guide, and when i did pod install --repo-update i got error for the ios deployment target,, so I do search in the Issue and I found that have to be 10.0, so i do change the pod deployment target to 10.0,, and the pod installation working well,, but when i do run it using npx react-native run-ios the build were failed,. then i do run from the xcode and found that error,..

i do use notifee v 0.9.0
react native v 0.62.2
react native firebase v 8.0.0

**Comment by naufanituharish** [comment]
Just delete the package using yarn and reinstalling the package also install the pod again and it's working now,.. 
Thank you,..
